using System.Text.RegularExpressions;
using QuestPDF.Interop.Generator.Backends.Kotlin;
using QuestPDF.Interop.Generator.Core;
using QuestPDF.Interop.Generator.Core.Classification;
using QuestPDF.Interop.Generator.Core.Reporting;

namespace QuestPDF.Interop.Generator.Tests;

/// <summary>Cross-cutting guarantees the generator makes about its output.</summary>
[Collection("pipeline")]
public sealed partial class PipelineInvariantTests(PipelineFixture pipeline)
{
    [Fact]
    public void CoverageMeetsTheNinetyPercentTarget()
    {
        var effective = pipeline.Model.Report
            .GroupBy(r => r.DocId)
            .Select(g => g.Max(r => r.Classification switch
            {
                ApiClassification.Unsupported => 3,
                ApiClassification.ManualOverride => 2,
                ApiClassification.Infrastructure => 1,
                _ => 0,
            }))
            .ToList();

        var generated = effective.Count(s => s == 0);
        var denominator = effective.Count(s => s != 1);
        var coverage = 100.0 * generated / denominator;

        Assert.True(coverage >= 90.0, $"Coverage {coverage:0.0}% fell below the 90% target.");
    }

    [Fact]
    public void EveryUnsupportedEntryHasAReason()
    {
        var missingReasons = pipeline.Model.Report
            .Where(r => r.Classification == ApiClassification.Unsupported && string.IsNullOrWhiteSpace(r.Detail))
            .ToList();

        Assert.Empty(missingReasons);
    }

    [Fact]
    public void EveryGeneratedFileCarriesTheDoNotEditHeader()
    {
        foreach (var (path, content) in pipeline.Files)
        {
            Assert.StartsWith("// <auto-generated>", content);
            Assert.Contains("Do not edit", content.Split('\n')[2]);
            Assert.Contains($"\npackage ", content);
            _ = path;
        }

        foreach (var (path, content) in pipeline.NativeFiles)
        {
            Assert.StartsWith("// <auto-generated>", content);
            _ = path;
        }
    }

    [Fact]
    public void EmissionIsDeterministic()
    {
        var overrides = ManualOverrides.Load(Path.Combine(TestPaths.RepoRoot, pipeline.Backend.ManualOverridesFile));
        var second = KotlinBackend.Run(pipeline.Assembly, overrides);
        var secondFiles = second.Output.Files;
        var secondNative = GeneratorPipeline.EmitNative(second.Output.Interop);

        Assert.Equal(pipeline.Files.Count, secondFiles.Count);
        foreach (var (path, content) in pipeline.Files)
            Assert.Equal(content, secondFiles[path]);

        Assert.Equal(pipeline.NativeFiles.Count, secondNative.Count);
        foreach (var (path, content) in pipeline.NativeFiles)
            Assert.Equal(content, secondNative[path]);

        Assert.Equal(RenderCoverageReport(pipeline.Output), RenderCoverageReport(second.Output));
    }

    private string RenderCoverageReport(LanguageOutput output) =>
        CoverageReport.Render(pipeline.Backend.CoverageLabels, output.Report,
            output.Interop.SourceAssemblyName, output.Interop.SourceAssemblyVersion);

    [Fact]
    public void ExportEntryPointsAreUnique()
    {
        var duplicates = pipeline.Model.NativeExports
            .GroupBy(e => e.EntryPoint, StringComparer.Ordinal)
            .Where(g => g.Count() > 1)
            .Select(g => g.Key)
            .ToList();

        Assert.Empty(duplicates);
        Assert.All(pipeline.Model.NativeExports, e => Assert.False(string.IsNullOrEmpty(e.EntryPoint)));
    }

    /// <summary>
    /// The three emitters must agree on the ABI: every entry point the Kotlin
    /// sources call is declared in the JNA interface and exported by the
    /// generated C# sources.
    /// </summary>
    [Fact]
    public void KotlinCallsJnaDeclarationsAndCSharpExportsAgree()
    {
        var kotlinCalls = pipeline.Files
            .Where(f => !f.Key.EndsWith("QuestPdfNative.kt"))
            .SelectMany(f => EntryPointReference().Matches(f.Value).Select(m => m.Groups[1].Value))
            .ToHashSet(StringComparer.Ordinal);

        var jnaDeclarations = EntryPointDeclaration()
            .Matches(pipeline.Files["com/questpdf/interop/QuestPdfNative.kt"])
            .Select(m => m.Groups[1].Value)
            .ToHashSet(StringComparer.Ordinal);

        var csharpExports = pipeline.NativeFiles
            .SelectMany(f => ExportedEntryPoint().Matches(f.Value).Select(m => m.Groups[1].Value))
            .ToHashSet(StringComparer.Ordinal);

        Assert.True(kotlinCalls.IsSubsetOf(jnaDeclarations),
            "Kotlin calls without JNA declaration: " + string.Join(", ", kotlinCalls.Except(jnaDeclarations).Take(5)));
        Assert.True(jnaDeclarations.IsSubsetOf(csharpExports),
            "JNA declarations without C# export: " + string.Join(", ", jnaDeclarations.Except(csharpExports).Take(5)));
        Assert.True(csharpExports.IsSubsetOf(jnaDeclarations),
            "C# exports without JNA declaration: " + string.Join(", ", csharpExports.Except(jnaDeclarations).Take(5)));
    }

    [Fact]
    public void NoGeneratedFileContainsUnimplementedStubs()
    {
        foreach (var (path, content) in pipeline.Files)
            Assert.False(content.Contains("TODO("), $"{path} contains a TODO() stub.");
    }

    [Fact]
    public void ContainerExposesTheCoreCompositionSurface()
    {
        var container = pipeline.Files["com/questpdf/infrastructure/IContainer.kt"];

        Assert.Contains("val nativeHandle: Long", container);
        Assert.Contains("fun column(handler: ColumnDescriptor.() -> kotlin.Unit)", container);
        Assert.Contains("fun row(handler: RowDescriptor.() -> kotlin.Unit)", container);
        Assert.Contains("fun text(text: String?): TextBlockDescriptor", container);
        Assert.Contains("fun padding(value: Float, unit: com.questpdf.infrastructure.Unit = com.questpdf.infrastructure.Unit.Point): IContainer", container);
        Assert.Contains("NativeBridge.lib.QP_IContainer_padding_0(nativeHandle, value, unit.value)", container);
        Assert.Contains("internal class ContainerImpl internal constructor(handle: Long)", container);
    }

    [Fact]
    public void SelfGenericStylingPreservesTheFluentSelfType()
    {
        var block = pipeline.Files["com/questpdf/fluent/TextBlockDescriptor.kt"];
        Assert.Contains("override fun fontSize(value: Float): TextBlockDescriptor", block);

        var span = pipeline.Files["com/questpdf/fluent/TextSpanDescriptor.kt"];
        Assert.Contains("open fun fontSize(value: Float): TextSpanDescriptor", span);
    }

    [Fact]
    public void ConstantsBridgeToTheRealValues()
    {
        // Color and page-size constants read their values from the live
        // QuestPDF assembly through bridged accessors.
        var colors = pipeline.Files["com/questpdf/helpers/Colors.kt"];
        Assert.Contains("val Black: Color", colors);
        Assert.Contains("QP_Colors_getBlack_0()", colors);
        Assert.Contains("object Red {", colors);

        var pageSizes = pipeline.Files["com/questpdf/helpers/PageSizes.kt"];
        Assert.Contains("val A4: PageSize", pageSizes);
        Assert.Contains("QP_PageSizes_getA4_0()", pageSizes);

        // String constants stay client-side compile-time literals.
        var fonts = pipeline.Files["com/questpdf/helpers/Fonts.kt"];
        Assert.Contains("= \"Lato\"", fonts);
    }

    [Fact]
    public void EnumsCarryUnderlyingValuesForMarshaling()
    {
        var unit = pipeline.Files["com/questpdf/infrastructure/Unit.kt"];
        Assert.Contains("enum class Unit(val value: Int)", unit);
        Assert.Contains("Point(0),", unit);
        Assert.Contains("fun fromValue(value: Int): Unit", unit);
    }

    [Fact]
    public void UserImplementedInterfacesStayAbstract()
    {
        var component = pipeline.Files["com/questpdf/infrastructure/IComponent.kt"];
        Assert.Contains("fun compose(container: IContainer)", component);
        Assert.DoesNotContain("nativeHandle", component);
        Assert.DoesNotContain("ComponentImpl", component);

        // The proxy export exists on both sides of the bridge.
        Assert.Contains("QP_Proxy_Component_new", pipeline.Files["com/questpdf/interop/QuestPdfNative.kt"]);
        Assert.Contains(pipeline.NativeFiles.Keys, k => k == "Exports/Proxies.g.cs");
        Assert.Contains("class ComponentProxy : global::QuestPDF.Infrastructure.IComponent", pipeline.NativeFiles["Exports/Proxies.g.cs"]);
    }

    [Fact]
    public void ManuallyOverriddenTypesAreNotEmitted()
    {
        // Placeholders is listed in manual-overrides.txt and hand-written in the
        // manual/ source set; emitting it too would be a duplicate declaration.
        Assert.DoesNotContain("com/questpdf/helpers/Placeholders.kt", pipeline.Files.Keys);

        var entries = pipeline.Model.Report
            .Where(r => r.DocId.Contains("QuestPDF.Helpers.Placeholders"))
            .ToList();

        Assert.NotEmpty(entries);
        Assert.All(entries, e => Assert.Equal(ApiClassification.ManualOverride, e.Classification));
    }

    [GeneratedRegex(@"NativeBridge\.lib\.(QP_[A-Za-z0-9_]+)\(")]
    private static partial Regex EntryPointReference();

    [GeneratedRegex(@"fun (QP_[A-Za-z0-9_]+)\(")]
    private static partial Regex EntryPointDeclaration();

    [GeneratedRegex(@"EntryPoint = ""(QP_[A-Za-z0-9_]+)""")]
    private static partial Regex ExportedEntryPoint();
}
