using System.Text.RegularExpressions;
using QuestPDF.Interop.Generator.Backends.TypeScript;
using QuestPDF.Interop.Generator.Core.Classification;
using QuestPDF.Interop.Generator.Core.Reporting;

namespace QuestPDF.Interop.Generator.Tests;

/// <summary>Cross-cutting guarantees the TypeScript backend makes about its output.</summary>
[Collection("ts-pipeline")]
public sealed partial class TsPipelineInvariantTests(TsPipelineFixture pipeline)
{
    [Fact]
    public void CoverageMeetsTheNinetyPercentTarget()
    {
        var effective = pipeline.Model.Report
            .GroupBy(r => r.DocId)
            .Select(g => g.Max(r => r.Classification switch
            {
                ApiClassification.Unsupported => 3,
                ApiClassification.ManualOverride => 2,
                ApiClassification.Infrastructure => 1,
                _ => 0,
            }))
            .ToList();

        var generated = effective.Count(s => s == 0);
        var denominator = effective.Count(s => s != 1);
        var coverage = 100.0 * generated / denominator;

        Assert.True(coverage >= 90.0, $"Coverage {coverage:0.0}% fell below the 90% target.");
    }

    [Fact]
    public void EveryUnsupportedEntryHasAReason()
    {
        var missingReasons = pipeline.Model.Report
            .Where(r => r.Classification == ApiClassification.Unsupported && string.IsNullOrWhiteSpace(r.Detail))
            .ToList();

        Assert.Empty(missingReasons);
    }

    [Fact]
    public void EveryGeneratedFileCarriesTheDoNotEditHeader()
    {
        foreach (var (path, content) in pipeline.Files)
        {
            Assert.StartsWith("// <auto-generated>", content);
            Assert.Contains("Do not edit", content.Split('\n')[2]);
            _ = path;
        }
    }

    [Fact]
    public void EmissionIsDeterministic()
    {
        var overrides = ManualOverrides.Load(Path.Combine(TestPaths.RepoRoot, pipeline.Backend.ManualOverridesFile));
        var second = TypeScriptBackend.Run(pipeline.Assembly, overrides);
        var secondFiles = second.Output.Files;
        var secondNative = GeneratorPipeline.EmitNative(second.Output.Interop);

        Assert.Equal(pipeline.Files.Count, secondFiles.Count);
        foreach (var (path, content) in pipeline.Files)
            Assert.Equal(content, secondFiles[path]);

        Assert.Equal(pipeline.NativeFiles.Count, secondNative.Count);
        foreach (var (path, content) in pipeline.NativeFiles)
            Assert.Equal(content, secondNative[path]);

        Assert.Equal(RenderCoverageReport(pipeline.Output), RenderCoverageReport(second.Output));
    }

    private string RenderCoverageReport(Core.LanguageOutput output) =>
        CoverageReport.Render(pipeline.Backend.CoverageLabels, output.Report,
            output.Interop.SourceAssemblyName, output.Interop.SourceAssemblyVersion);

    [Fact]
    public void ExportEntryPointsAreUnique()
    {
        var duplicates = pipeline.Model.NativeExports
            .GroupBy(e => e.EntryPoint, StringComparer.Ordinal)
            .Where(g => g.Count() > 1)
            .Select(g => g.Key)
            .ToList();

        Assert.Empty(duplicates);
        Assert.All(pipeline.Model.NativeExports, e => Assert.False(string.IsNullOrEmpty(e.EntryPoint)));
    }

    /// <summary>
    /// The three emitters must agree on the ABI: every entry point the fluent
    /// sources call is declared as a koffi function and exported by the
    /// generated C# sources.
    /// </summary>
    [Fact]
    public void FluentCallsKoffiDeclarationsAndCSharpExportsAgree()
    {
        var fluentCalls = pipeline.Files
            .Where(f => !f.Key.StartsWith("interop/", StringComparison.Ordinal))
            .SelectMany(f => EntryPointReference().Matches(f.Value).Select(m => m.Groups[1].Value))
            .ToHashSet(StringComparer.Ordinal);

        var koffiDeclarations = KoffiDeclaration()
            .Matches(pipeline.Files["interop/native-functions.ts"])
            .Select(m => m.Groups[1].Value)
            .ToHashSet(StringComparer.Ordinal);

        var csharpExports = pipeline.NativeFiles
            .SelectMany(f => ExportedEntryPoint().Matches(f.Value).Select(m => m.Groups[1].Value))
            .ToHashSet(StringComparer.Ordinal);

        Assert.True(fluentCalls.IsSubsetOf(koffiDeclarations),
            "Fluent calls without koffi declaration: " + string.Join(", ", fluentCalls.Except(koffiDeclarations).Take(5)));
        Assert.True(koffiDeclarations.IsSubsetOf(csharpExports),
            "koffi declarations without C# export: " + string.Join(", ", koffiDeclarations.Except(csharpExports).Take(5)));
        Assert.True(csharpExports.IsSubsetOf(koffiDeclarations),
            "C# exports without koffi declaration: " + string.Join(", ", csharpExports.Except(koffiDeclarations).Take(5)));
    }

    [Fact]
    public void ContainerExposesTheCoreCompositionSurface()
    {
        var container = pipeline.Files["questpdf/infrastructure/IContainer.ts"];

        Assert.Contains("readonly nativeHandle: number;", container);
        Assert.Contains("column(handler: (column: ColumnDescriptor) => void): void;", container);
        Assert.Contains("row(handler: (row: RowDescriptor) => void): void;", container);
        Assert.Contains("text(text: string | null): TextBlockDescriptor;", container);
        Assert.Contains("padding(value: number, unit?: Unit): IContainer;", container);
        Assert.Matches(@"Native\.lib\.QP_IContainer_padding_0\(this\.nativeHandle, value, unit\)", container);
        Assert.Contains("export class ContainerImpl extends NativeObject implements IContainer {", container);
    }

    [Fact]
    public void SelfGenericStylingPreservesTheFluentSelfType()
    {
        var block = pipeline.Files["questpdf/fluent/TextBlockDescriptor.ts"];
        Assert.Contains("fontSize(value: number): TextBlockDescriptor {", block);

        var span = pipeline.Files["questpdf/fluent/TextSpanDescriptor.ts"];
        Assert.Contains("fontSize(value: number): TextSpanDescriptor {", span);
    }

    [Fact]
    public void OverloadsDispatchOnArgumentShapes()
    {
        var container = pipeline.Files["questpdf/infrastructure/IContainer.ts"];

        // text(string) vs text(handler) — runtime dispatch on typeof tests.
        Assert.Contains("text(...args: any[]): any {", container);
        Assert.Contains("typeof args[0] === \"function\"", container);
        Assert.Contains("typeof args[0] === \"string\"", container);
        Assert.Contains("throw new TypeError(\"No overload of 'text' matches the provided arguments.\");", container);
    }

    [Fact]
    public void InterfaceHierarchiesCompleteInheritedOverloads()
    {
        // ITableCellContainer redeclares column/row (cell coordinates) and must
        // therefore restate the inherited composition overloads.
        var cell = pipeline.Files["questpdf/elements/table/ITableCellContainer.ts"];
        Assert.Contains("column(value: number): ITableCellContainer;", cell);
        Assert.Contains("column(handler: (column: ColumnDescriptor) => void): void;", cell);
        Assert.Contains("export class TableCellContainerImpl extends ContainerImpl implements ITableCellContainer {", cell);
    }

    [Fact]
    public void ClassesImplementTheirInterfacesCompletely()
    {
        // Document implements IDocument including the extension-placed members
        // (TypeScript has no default interface bodies).
        var document = pipeline.Files["questpdf/fluent/Document.ts"];
        Assert.Contains("export class Document extends NativeObject implements IDocument {", document);
        Assert.Contains("generatePdf(): Uint8Array;", document);
        Assert.Contains("generatePdf(filePath: string): void;", document);
    }

    [Fact]
    public void EnumsAreConstObjectsWithLiteralUnionTypes()
    {
        var unit = pipeline.Files["questpdf/infrastructure/Unit.ts"];
        Assert.Contains("export const Unit = {", unit);
        Assert.Contains("Point: 0,", unit);
        Assert.Contains("} as const;", unit);
        Assert.Contains("export type Unit = (typeof Unit)[keyof typeof Unit];", unit);
    }

    [Fact]
    public void UserImplementedInterfacesStayAbstract()
    {
        var component = pipeline.Files["questpdf/infrastructure/IComponent.ts"];
        Assert.Contains("compose(container: IContainer): void;", component);
        Assert.DoesNotContain("nativeHandle", component);
        Assert.DoesNotContain("ComponentImpl", component);

        // The proxy export exists on both sides of the bridge.
        Assert.Contains("QP_Proxy_Component_new", pipeline.Files["interop/native-functions.ts"]);
        Assert.Contains(pipeline.NativeFiles.Keys, k => k == "Exports/Proxies.g.cs");
    }

    [Fact]
    public void ConstantsBridgeToTheRealValues()
    {
        var colors = pipeline.Files["questpdf/helpers/Colors.ts"];
        Assert.Contains("static get Black(): Color {", colors);
        Assert.Contains("QP_Colors_getBlack_0()", colors);
        Assert.Contains("static readonly Red = {", colors);

        var fonts = pipeline.Files["questpdf/helpers/Fonts.ts"];
        Assert.Contains("= \"Lato\";", fonts);
    }

    [Fact]
    public void InternalBarrelEvaluatesBasesBeforeSubclasses()
    {
        var barrel = pipeline.Files["internal.ts"];
        var lines = barrel.Split('\n').ToList();

        int LineOf(string module) => lines.FindIndex(l => l.Contains($"'./{module}'"));

        // Impl inheritance: ContainerImpl (IContainer) precedes TableCellContainerImpl.
        Assert.True(LineOf("questpdf/infrastructure/IContainer") < LineOf("questpdf/elements/table/ITableCellContainer"),
            "IContainer must be evaluated before ITableCellContainer.");

        // Class inheritance: TextSpanDescriptor precedes TextBlockDescriptor.
        Assert.True(LineOf("questpdf/fluent/TextSpanDescriptor") < LineOf("questpdf/fluent/TextBlockDescriptor"),
            "TextSpanDescriptor must be evaluated before TextBlockDescriptor.");
    }

    [GeneratedRegex(@"Native\.lib\.(QP_[A-Za-z0-9_]+)\(")]
    private static partial Regex EntryPointReference();

    [GeneratedRegex(@"(QP_[A-Za-z0-9_]+): lib\.func\(")]
    private static partial Regex KoffiDeclaration();

    [GeneratedRegex(@"EntryPoint = ""(QP_[A-Za-z0-9_]+)""")]
    private static partial Regex ExportedEntryPoint();
}
