// <auto-generated>
// Generated by QuestPDF.Interop.Generator from QuestPDF 2026.7.1.0.
// Do not edit — this file is wiped and recreated on every generator run.
// </auto-generated>

import { Native } from '../../manual/native-bridge';
import { LicenseType } from '../internal';

export class Settings {
    private constructor() {}

    /**
     * This flag enables checking the font glyph availability.
     * If your text contains glyphs that are not present in the specified font,
     * 1) when this flag is enabled: the DocumentDrawingException is thrown. OR
     * 2) when this flag is disabled: placeholder characters are visible in the produced PDF file.
     * Enabling this flag may slightly decrease document generation performance.
     * However, it provides hints that used fonts are not sufficient to produce correct results.
     *
     * By default, this flag is enabled only when the debugger IS attached.
     */
    static get checkIfAllTextGlyphsAreAvailable(): boolean {
        return (Native.checked(Native.lib.QP_Settings_getCheckIfAllTextGlyphsAreAvailable_0()) !== 0);
    }
    static set checkIfAllTextGlyphsAreAvailable(value: boolean) {
        Native.lib.QP_Settings_setCheckIfAllTextGlyphsAreAvailable_0((value ? 1 : 0));
        Native.check();
    }

    /**
     * @deprecated This setting is ignored since the 2023.10 version. The new infinite layout detection algorithm works automatically. You can safely remove this setting from your codebase.
     */
    static get documentLayoutExceptionThreshold(): number {
        return Native.checked(Native.lib.QP_Settings_getDocumentLayoutExceptionThreshold_0());
    }
    static set documentLayoutExceptionThreshold(value: number) {
        Native.lib.QP_Settings_setDocumentLayoutExceptionThreshold_0(value);
        Native.check();
    }

    /**
     * This flag generates additional document elements to cache layout calculation results.
     * In the vast majority of cases, this significantly improves performance, while slightly increasing memory consumption.
     *
     * Enabled by default.
     */
    static get enableCaching(): boolean {
        return (Native.checked(Native.lib.QP_Settings_getEnableCaching_0()) !== 0);
    }
    static set enableCaching(value: boolean) {
        Native.lib.QP_Settings_setEnableCaching_0((value ? 1 : 0));
        Native.check();
    }

    /**
     * This flag generates additional document elements to improve layout debugging experience.
     * When the provided content contains size constraints impossible to meet, the library generates an enhanced exception message with additional location and layout measurement details.
     *
     * By default, this flag is enabled only when the debugger IS attached.
     */
    static get enableDebugging(): boolean {
        return (Native.checked(Native.lib.QP_Settings_getEnableDebugging_0()) !== 0);
    }
    static set enableDebugging(value: boolean) {
        Native.lib.QP_Settings_setEnableDebugging_0((value ? 1 : 0));
        Native.check();
    }

    /**
     * Selects the QuestPDF license tier that applies to your usage. Set this once at application startup, before generating the first document.
     *
     * For more details, please check the [QuestPDF Pricing webpage](https://www.questpdf.com/pricing) and [QuestPDF License webpage](https://www.questpdf.com/license).
     */
    static get license(): LicenseType | null {
        const outHasValue: number[] = [0];
        const rawResult = Native.lib.QP_Settings_getLicense_0(outHasValue);
        Native.check();
        return outHasValue[0] !== 0 ? (rawResult as LicenseType) : null;
    }
    static set license(value: LicenseType | null) {
        Native.lib.QP_Settings_setLicense_0((value != null ? 1 : 0), (value ?? 0));
        Native.check();
    }

    /**
     * Gets or sets the file path used for temporary storage during the document generation process.
     * This path is used by various operations that require temporary files.
     */
    static get temporaryStoragePath(): string | null {
        return Native.takeString(Native.checked(Native.lib.QP_Settings_getTemporaryStoragePath_0()));
    }
    static set temporaryStoragePath(value: string | null) {
        Native.lib.QP_Settings_setTemporaryStoragePath_0(value);
        Native.check();
    }

    /**
     * Decides whether the application should use the fonts available in the environment.
     *
     * When set to `true`, the application will use the fonts installed on the system where it is running. This is the default behavior.
     *
     * When set to `false`, the application will only use the fonts that have been registered using the `FontManager` class in the QuestPDF library.
     *
     * This property is useful when you want to control the fonts used by your application, especially in cases where the environment might not have the necessary fonts installed.
     */
    static get useEnvironmentFonts(): boolean {
        return (Native.checked(Native.lib.QP_Settings_getUseEnvironmentFonts_0()) !== 0);
    }
    static set useEnvironmentFonts(value: boolean) {
        Native.lib.QP_Settings_setUseEnvironmentFonts_0((value ? 1 : 0));
        Native.check();
    }
}
