// <auto-generated>
// Generated by QuestPDF.Interop.Generator from QuestPDF 2026.7.1.0.
// Do not edit — this file is wiped and recreated on every generator run.
// </auto-generated>

import { Native } from '../../../../manual/native-bridge';
import { NATIVE_HANDLE } from '../../../../manual/native-object';
import { NativeCallbackJToV } from '../../../interop/callback-shapes';
import { ColumnDescriptor, ContainerImpl, IContainer, RowDescriptor } from '../../../internal';

export interface ITableCellContainer extends IContainer {
    /**
     * Marks the specified table cell as a semantic horizontal header.
     * This allows assistive technologies to recognize the cell as a header, improving accessibility and semantic structure.
     */
    asSemanticHorizontalHeader(): ITableCellContainer;

    /**
     * Draws a collection of elements vertically (from top to bottom).
     * [Learn more](https://www.questpdf.com/api-reference/column.html)
     *
     * Supports paging.
     *
     * @param handler The action to configure the column's content.
     */
    column(handler: (column: ColumnDescriptor) => void): void;

    /**
     * Specifies the column position (horizontal axis) of the cell.
     * [Learn more](https://www.questpdf.com/api-reference/table/basics.html)
     *
     * @param value Columns are numbered starting with 1.
     */
    column(value: number): ITableCellContainer;

    /**
     * Defines the number of columns a cell spans in the horizontal axis.
     * [Learn more](https://www.questpdf.com/api-reference/table/basics.html#manual-cell-placement)
     *
     * Useful when creating complex layouts.
     */
    columnSpan(value: number): ITableCellContainer;

    /**
     * Draws a collection of elements horizontally.
     * Depending on the content direction mode, elements will be drawn from left to right, or from right to left.
     *
     * [Learn more](https://www.questpdf.com/api-reference/row.html)
     *
     * Supports paging.
     *
     * Depending on its content, the Row element may repeatedly draw certain items across multiple pages. Use the {@link ElementExtensions.ShowOnce} element to modify this behavior if it's not desired.
     *
     * @param handler The action to configure the row's content.
     */
    row(handler: (row: RowDescriptor) => void): void;

    /**
     * Specifies the row position (vertical axis) of the cell.
     * [Learn more](https://www.questpdf.com/api-reference/table/basics.html)
     *
     * @param value Rows are numbered starting with 1.
     */
    row(value: number): ITableCellContainer;

    /**
     * Defines the number of rows a cell spans in the vertical axis.
     * [Learn more](https://www.questpdf.com/api-reference/table/basics.html#manual-cell-placement)
     *
     * Useful when creating complex layouts.
     */
    rowSpan(value: number): ITableCellContainer;
}

/** Wraps a native ITableCellContainer handle. @internal */
export class TableCellContainerImpl extends ContainerImpl implements ITableCellContainer {
    asSemanticHorizontalHeader(): ITableCellContainer {
        return new TableCellContainerImpl(Native.checked(Native.lib.QP_ITableCellContainer_asSemanticHorizontalHeader_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    column(handler: (column: ColumnDescriptor) => void): void;
    column(value: number): ITableCellContainer;
    column(...args: any[]): any {
        if (args.length === 1 && typeof args[0] === "function") {
            const handler = args[0] as (column: ColumnDescriptor) => void;
            Native.lib.QP_IContainer_column_0(this.nativeHandle, Native.retain(NativeCallbackJToV, (p0: number) => Native.guard(undefined, () => { handler(new ColumnDescriptor(p0, NATIVE_HANDLE)); })));
            Native.check();
            return;
        }
        if (args.length === 1 && typeof args[0] === "number") {
            const value = args[0] as number;
            return new TableCellContainerImpl(Native.checked(Native.lib.QP_ITableCellContainer_column_0(this.nativeHandle, ((value) | 0))), NATIVE_HANDLE);
        }
        throw new TypeError("No overload of 'column' matches the provided arguments.");
    }

    columnSpan(value: number): ITableCellContainer {
        return new TableCellContainerImpl(Native.checked(Native.lib.QP_ITableCellContainer_columnSpan_0(this.nativeHandle, ((value) | 0))), NATIVE_HANDLE);
    }

    row(handler: (row: RowDescriptor) => void): void;
    row(value: number): ITableCellContainer;
    row(...args: any[]): any {
        if (args.length === 1 && typeof args[0] === "function") {
            const handler = args[0] as (row: RowDescriptor) => void;
            Native.lib.QP_IContainer_row_0(this.nativeHandle, Native.retain(NativeCallbackJToV, (p0: number) => Native.guard(undefined, () => { handler(new RowDescriptor(p0, NATIVE_HANDLE)); })));
            Native.check();
            return;
        }
        if (args.length === 1 && typeof args[0] === "number") {
            const value = args[0] as number;
            return new TableCellContainerImpl(Native.checked(Native.lib.QP_ITableCellContainer_row_0(this.nativeHandle, ((value) | 0))), NATIVE_HANDLE);
        }
        throw new TypeError("No overload of 'row' matches the provided arguments.");
    }

    rowSpan(value: number): ITableCellContainer {
        return new TableCellContainerImpl(Native.checked(Native.lib.QP_ITableCellContainer_rowSpan_0(this.nativeHandle, ((value) | 0))), NATIVE_HANDLE);
    }
}
