using System.Text;
using QuestPDF.Interop.Generator.Backends.Kotlin;
using QuestPDF.Interop.Generator.Core;
using QuestPDF.Interop.Generator.Core.Bridge;

namespace QuestPDF.Interop.Generator.Backends.Kotlin.Emission;

/// <summary>
/// Emits the generated half of the Kotlin interop layer: the JNA library
/// interface declaring every native export, and the callback fun-interfaces
/// for each deduplicated callback shape. The handwritten half (NativeBridge,
/// NativeObject, the runtime exports interface) lives in the manual source set.
/// </summary>
public static class InteropKotlinEmitter
{
    public static void Emit(KotlinModel model, IDictionary<string, string> files)
    {
        files["com/questpdf/interop/QuestPdfNative.kt"] = EmitLibraryInterface(model);
        if (model.CallbackShapes.Count > 0)
            files["com/questpdf/interop/NativeCallbacks.kt"] = EmitCallbackShapes(model);
    }

    private static string Header(KotlinModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"// Generated by {GeneratorInfo.ToolName} from QuestPDF {model.SourceAssemblyVersion}.");
        sb.AppendLine("// Do not edit — this file is wiped and recreated on every generator run.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("package com.questpdf.interop");
        sb.AppendLine();
        return sb.ToString();
    }

    private static string EmitLibraryInterface(KotlinModel model)
    {
        var sb = new StringBuilder(Header(model));
        sb.AppendLine("import com.sun.jna.Pointer");
        sb.AppendLine("import com.sun.jna.ptr.ByteByReference");
        sb.AppendLine("import com.sun.jna.ptr.IntByReference");
        sb.AppendLine("import com.sun.jna.ptr.PointerByReference");
        sb.AppendLine();
        sb.AppendLine("/**");
        sb.AppendLine(" * JNA declarations for every UnmanagedCallersOnly export of the");
        sb.AppendLine(" * QuestPDF.Native shared library. Method names equal entry-point names.");
        sb.AppendLine(" */");
        sb.AppendLine("@Suppress(\"FunctionName\", \"LongLine\")");
        sb.AppendLine("internal interface QuestPdfNative : QuestPdfNativeRuntime {");

        foreach (var export in model.NativeExports)
        {
            var parameters = new List<string>();
            if (export.Receiver is not null)
                parameters.Add("self: Long");

            foreach (var parameter in export.Parameters)
                foreach (var abi in BridgeAbi.ParameterLayout(parameter.Name, parameter.Marshal))
                    parameters.Add($"{abi.Name}: {JnaType(abi)}");

            var returnSlot = BridgeAbi.ReturnLayout(export.Return);
            if (returnSlot == AbiSlot.BufferOut)
            {
                parameters.Add("outData: PointerByReference");
                parameters.Add("outLength: IntByReference");
            }
            else if (BridgeAbi.IsFlaggedReturn(export.Return))
            {
                parameters.Add("outHasValue: ByteByReference");
            }

            var returnSuffix = returnSlot switch
            {
                AbiSlot.Void or AbiSlot.BufferOut => "",
                AbiSlot.TextReturn => ": Pointer?",
                _ => ": " + JnaScalarType(returnSlot),
            };

            sb.AppendLine($"    fun {export.EntryPoint}({string.Join(", ", parameters)}){returnSuffix}");
        }

        foreach (var proxy in model.Proxies)
            sb.AppendLine($"    fun {proxy.ProxyExportEntryPoint}(callback: {proxy.Method.Shape.Name}): Long");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string EmitCallbackShapes(KotlinModel model)
    {
        var sb = new StringBuilder(Header(model));
        sb.AppendLine("import com.sun.jna.Callback");
        sb.AppendLine();
        sb.AppendLine("// One fun-interface per callback ABI shape. JNA builds a native");
        sb.AppendLine("// trampoline per instance; NativeBridge.retain keeps instances alive");
        sb.AppendLine("// while native code may still call them.");

        foreach (var shape in model.CallbackShapes)
        {
            var parameters = shape.ParameterSlots
                .Select((slot, i) => $"p{i}: {CallbackSlotType(slot)}");
            var returnSuffix = shape.ReturnSlot == AbiSlot.Void ? "" : ": " + JnaScalarType(shape.ReturnSlot);

            sb.AppendLine();
            sb.AppendLine($"internal fun interface {shape.Name} : Callback {{");
            sb.AppendLine($"    fun invoke({string.Join(", ", parameters)}){returnSuffix}");
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string JnaType(AbiParameter parameter) => parameter.Slot switch
    {
        AbiSlot.Text => "String?",
        AbiSlot.Bytes => "ByteArray?",
        AbiSlot.FloatArray => "FloatArray?",
        AbiSlot.LongArray => "LongArray?",
        // out-projected so vararg parameters (Array<out String>) pass directly
        AbiSlot.TextArray => "Array<out String>?",
        AbiSlot.Callback => parameter.Shape!.Name + "?",
        _ => JnaScalarType(parameter.Slot),
    };

    private static string CallbackSlotType(AbiSlot slot) => slot switch
    {
        AbiSlot.Text => "String?",
        _ => JnaScalarType(slot),
    };

    private static string JnaScalarType(AbiSlot slot) => slot switch
    {
        AbiSlot.Byte => "Byte",
        AbiSlot.Short => "Short",
        AbiSlot.Int => "Int",
        AbiSlot.Long => "Long",
        AbiSlot.Float => "Float",
        AbiSlot.Double => "Double",
        _ => throw new InvalidOperationException($"Slot {slot} is not a scalar"),
    };
}
