using System.Text;
using System.Text.RegularExpressions;
using QuestPDF.Interop.Generator.Core;
using QuestPDF.Interop.Generator.Core.Bridge;

namespace QuestPDF.Interop.Generator.Backends.Kotlin.Emission;

/// <summary>
/// Stage 3: renders the classified Kotlin model as source files. Pure
/// rendering — every mapping decision was already made in Stage 2; Kotlin
/// projections of the neutral bridge marshals come from
/// <see cref="KotlinBridgeViews"/>. Output is deterministic: one file per
/// top-level declaration, stable ordering, stable imports. Function bodies
/// marshal arguments, call the native export through <c>NativeBridge.lib</c>,
/// re-throw recorded errors and wrap results.
/// </summary>
public sealed partial class KotlinEmitter(KotlinBridgeViews views)
{
    public IReadOnlyDictionary<string, string> Emit(KotlinModel model)
    {
        var files = new SortedDictionary<string, string>(StringComparer.Ordinal);

        // Top-level names per package: a package-local declaration shadows
        // kotlin.* default imports (QuestPDF's Unit enum vs kotlin.Unit), so the
        // resolver must qualify foreign types with a shadowed simple name.
        var packageLocals = model.Declarations
            .GroupBy(d => d.PackageName, StringComparer.Ordinal)
            .ToDictionary(
                g => g.Key,
                g => g.Select(d => d.Name)
                    .Concat(g.OfType<KotlinTypeDeclaration>()
                        .Where(t => t.ImplClassName is not null)
                        .Select(t => t.ImplClassName!))
                    .ToHashSet(StringComparer.Ordinal),
                StringComparer.Ordinal);

        foreach (var declaration in model.Declarations)
        {
            var path = declaration.PackageName.Replace('.', '/') + "/" + declaration.Name + ".kt";
            files[path] = EmitFile(declaration, model, packageLocals[declaration.PackageName]);
        }

        return files;
    }

    private string EmitFile(KotlinDeclaration declaration, KotlinModel model, IReadOnlySet<string> packageLocalNames)
    {
        var resolver = ImportResolver.For(declaration, views, packageLocalNames);
        var body = new CodeWriter();

        switch (declaration)
        {
            case KotlinTypeAlias alias:
                EmitTypeAlias(body, alias, resolver);
                break;

            case KotlinTypeDeclaration type:
                EmitType(body, type, resolver);
                if (type.ImplClassName is not null)
                {
                    body.Line();
                    body.Line($"internal class {type.ImplClassName} internal constructor(handle: Long) : " +
                              $"{resolver.ResolveName("com.questpdf.interop", "NativeObject")}(handle), {type.Name}");
                }
                break;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"// Generated by {GeneratorInfo.ToolName} from QuestPDF {model.SourceAssemblyVersion}.");
        sb.AppendLine("// Do not edit — this file is wiped and recreated on every generator run.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.Append("package ").AppendLine(declaration.PackageName);

        var imports = resolver.ImportStatements();
        if (imports.Count > 0)
        {
            sb.AppendLine();
            foreach (var import in imports)
                sb.Append("import ").AppendLine(import);
        }

        sb.AppendLine();
        sb.Append(body);
        return sb.ToString();
    }

    // ---- Declarations ----

    private static void EmitTypeAlias(CodeWriter writer, KotlinTypeAlias alias, ImportResolver resolver)
    {
        EmitKDoc(writer, alias.KDoc);
        EmitDeprecated(writer, alias.DeprecationMessage);
        writer.Line($"typealias {alias.Name} = {RenderType(alias.AliasedType, resolver)}");
    }

    private void EmitType(CodeWriter writer, KotlinTypeDeclaration type, ImportResolver resolver)
    {
        EmitKDoc(writer, type.KDoc);
        EmitDeprecated(writer, type.DeprecationMessage);

        switch (type.Kind)
        {
            case KotlinTypeKind.Enum:
                EmitEnum(writer, type);
                return;

            case KotlinTypeKind.Object:
                writer.Line($"object {type.Name} {{");
                break;

            case KotlinTypeKind.Interface:
            {
                var supertypes = type.SuperInterfaces.Select(i => RenderType(i, resolver)).ToList();
                var suffix = supertypes.Count > 0 ? " : " + string.Join(", ", supertypes) : "";
                writer.Line($"interface {type.Name}{TypeParameterList(type)}{suffix} {{");
                break;
            }

            case KotlinTypeKind.Class:
            {
                var header = new StringBuilder();
                if (type.IsAbstract)
                    header.Append("abstract ");
                else if (type.IsOpen)
                    header.Append("open ");

                header.Append("class ").Append(type.Name).Append(TypeParameterList(type));

                if (type.IsHandleBacked)
                {
                    header.Append(" internal constructor(handle: Long)");
                }
                else if (type.PrimaryConstructor is { } constructor)
                {
                    if (constructor.IsInternal)
                        header.Append(" internal constructor");

                    if (constructor.Parameters.Count > 0 || constructor.IsInternal)
                    {
                        header.Append('(');
                        header.Append(string.Join(", ", constructor.Parameters.Select(p => RenderParameter(p, resolver))));
                        header.Append(')');
                    }
                }

                var supertypes = new List<string>();
                if (type.SuperClass is not null)
                    supertypes.Add(RenderTypeBare(type.SuperClass, resolver) + (type.SuperClassCall ?? "()"));
                supertypes.AddRange(type.SuperInterfaces.Select(i => RenderType(i, resolver)));

                if (supertypes.Count > 0)
                    header.Append(" : ").Append(string.Join(", ", supertypes));

                var isEmpty = type.Properties.Count == 0 && type.Functions.Count == 0 &&
                              type.CompanionProperties.Count == 0 && type.CompanionFunctions.Count == 0 &&
                              type.SecondaryConstructors.Count == 0 && type.NestedTypes.Count == 0;

                if (isEmpty)
                {
                    writer.Line(header.ToString());
                    return;
                }

                header.Append(" {");
                writer.Line(header.ToString());
                break;
            }
        }

        writer.Indent();
        var needsSeparator = false;

        if (type.DeclaresNativeHandle)
        {
            writer.Line("/** Handle of the native object backing this instance. */");
            writer.Line("val nativeHandle: Long");
            needsSeparator = true;
        }

        foreach (var ctor in type.SecondaryConstructors)
        {
            if (needsSeparator)
                writer.Line();
            EmitSecondaryConstructor(writer, ctor, resolver);
            needsSeparator = true;
        }

        foreach (var property in type.Properties)
        {
            if (needsSeparator && (property.Getter is not null || property.KDoc is not null))
                writer.Line();
            EmitProperty(writer, property, resolver, abstractContext: type.Kind == KotlinTypeKind.Interface);
            needsSeparator = true;
        }

        foreach (var function in type.Functions)
        {
            if (needsSeparator)
                writer.Line();
            EmitFunction(writer, function, resolver);
            needsSeparator = true;
        }

        if (type.CompanionProperties.Count > 0 || type.CompanionFunctions.Count > 0)
        {
            if (needsSeparator)
                writer.Line();
            writer.Line("companion object {");
            writer.Indent();

            var companionSeparator = false;
            foreach (var property in type.CompanionProperties)
            {
                if (companionSeparator && (property.Getter is not null || property.KDoc is not null))
                    writer.Line();
                EmitProperty(writer, property, resolver, abstractContext: false);
                companionSeparator = true;
            }

            foreach (var function in type.CompanionFunctions)
            {
                if (companionSeparator)
                    writer.Line();
                EmitFunction(writer, function, resolver);
                companionSeparator = true;
            }

            writer.Outdent();
            writer.Line("}");
            needsSeparator = true;
        }

        foreach (var nested in type.NestedTypes)
        {
            if (needsSeparator)
                writer.Line();
            EmitType(writer, nested, resolver);
            needsSeparator = true;
        }

        writer.Outdent();
        writer.Line("}");
    }

    private static void EmitEnum(CodeWriter writer, KotlinTypeDeclaration type)
    {
        writer.Line($"enum class {type.Name}(val value: Int) {{");
        writer.Indent();

        foreach (var entry in type.EnumEntries)
        {
            EmitKDoc(writer, entry.KDoc);
            EmitDeprecated(writer, entry.DeprecationMessage);
            writer.Line($"{entry.Name}({entry.Value}),");
        }

        writer.Line(";");
        writer.Line();
        writer.Line("companion object {");
        writer.Indent();
        writer.Line("@JvmStatic");
        writer.Line($"fun fromValue(value: Int): {type.Name} = entries.first {{ it.value == value }}");
        writer.Outdent();
        writer.Line("}");

        writer.Outdent();
        writer.Line("}");
    }

    private void EmitSecondaryConstructor(CodeWriter writer, KotlinSecondaryConstructor ctor, ImportResolver resolver)
    {
        EmitKDoc(writer, ctor.KDoc);
        EmitDeprecated(writer, ctor.DeprecationMessage);
        if (ctor.IsJvmOverloads)
            writer.Line("@JvmOverloads");

        var arguments = BuildCallArguments(ctor.Export, ctor.Parameters, resolver);
        var raw = $"NativeBridge.lib.{ctor.Export.EntryPoint}({string.Join(", ", arguments)})";

        var parameters = string.Join(", ", ctor.Parameters.Select(p => RenderParameter(p, resolver)));
        writer.Line($"constructor({parameters}) :");
        writer.Indent();
        writer.Line($"this(NativeBridge.checked({raw}))");
        writer.Outdent();
    }

    // ---- Members ----

    private void EmitProperty(CodeWriter writer, KotlinProperty property, ImportResolver resolver, bool abstractContext)
    {
        EmitKDoc(writer, property.KDoc);
        EmitDeprecated(writer, property.DeprecationMessage);
        if (property.IsJvmStatic)
            writer.Line("@JvmStatic");

        var sb = new StringBuilder();
        if (property.IsOverride)
            sb.Append("override ");
        if (property.IsConst)
            sb.Append("const ");

        sb.Append(property.IsMutable ? "var " : "val ");
        sb.Append(property.Name).Append(": ").Append(RenderType(property.Type, resolver));

        if (property.Initializer is not null)
        {
            writer.Line(sb.Append(" = ").Append(RenderExpr(property.Initializer, resolver)).ToString());
            return;
        }

        if (property.Getter is null)
        {
            // Abstract property (user-implemented interfaces).
            writer.Line(sb.ToString());
            return;
        }

        writer.Line(sb.ToString());
        writer.Indent();

        var getter = property.Getter;
        var getterArguments = BuildCallArguments(getter, [], resolver);
        var raw = $"NativeBridge.lib.{getter.EntryPoint}({string.Join(", ", getterArguments)})";

        if (getter.Return is BridgeMarshal.Blob)
        {
            writer.Line("get() {");
            writer.Indent();
            EmitBufferReturn(writer, getter, getterArguments, resolver);
            writer.Outdent();
            writer.Line("}");
        }
        else if (BridgeAbi.IsFlaggedReturn(getter.Return))
        {
            writer.Line("get() {");
            writer.Indent();
            EmitFlaggedReturn(writer, getter, getterArguments, resolver);
            writer.Outdent();
            writer.Line("}");
        }
        else
        {
            writer.Line($"get() = {WrapReturn(getter.Return, raw, resolver)}");
        }

        if (property.Setter is { } setter)
        {
            var setterArguments = BuildCallArguments(setter,
                [new KotlinParameter("value", property.Type, null, false)], resolver);
            writer.Line("set(value) {");
            writer.Indent();
            writer.Line($"NativeBridge.lib.{setter.EntryPoint}({string.Join(", ", setterArguments)})");
            writer.Line("NativeBridge.check()");
            writer.Outdent();
            writer.Line("}");
        }

        writer.Outdent();
    }

    private void EmitFunction(CodeWriter writer, KotlinFunction function, ImportResolver resolver)
    {
        EmitKDoc(writer, function.KDoc);
        EmitDeprecated(writer, function.DeprecationMessage);
        if (function.IsJvmStatic)
            writer.Line("@JvmStatic");
        if (function.IsJvmOverloads)
            writer.Line("@JvmOverloads");

        var sb = new StringBuilder();
        if (function.IsOverride)
            sb.Append("override ");
        else if (function.IsOpen)
            sb.Append("open ");

        sb.Append("fun ");

        var inlineConstraints = function.TypeConstraints
            .GroupBy(c => c.TypeParameter)
            .ToDictionary(g => g.Key, g => g.ToList());
        var useWhereClause = inlineConstraints.Values.Any(list => list.Count > 1);

        if (function.TypeParameters.Count > 0)
        {
            sb.Append('<');
            sb.Append(string.Join(", ", function.TypeParameters.Select(p =>
                !useWhereClause && inlineConstraints.TryGetValue(p, out var bounds) && bounds.Count == 1
                    ? $"{p} : {RenderType(bounds[0].Bound, resolver)}"
                    : p)));
            sb.Append("> ");
        }

        sb.Append(function.Name).Append('(');
        sb.Append(string.Join(", ", function.Parameters.Select(p => RenderParameter(p, resolver))));
        sb.Append(')');

        if (!function.ReturnType.IsKotlinUnit)
            sb.Append(": ").Append(RenderType(function.ReturnType, resolver));

        if (useWhereClause)
        {
            sb.Append(" where ");
            sb.Append(string.Join(", ", function.TypeConstraints.Select(c =>
                $"{c.TypeParameter} : {RenderType(c.Bound, resolver)}")));
        }

        if (function.Body is KotlinBody.Delegate delegation)
        {
            var call = $"{delegation.TargetName}({string.Join(", ", delegation.Arguments.Select(a => RenderDelegateArg(a, resolver)))})";

            if (function.ReturnType.IsKotlinUnit)
            {
                writer.Line(sb + " {");
                writer.Indent();
                writer.Line(call);
                writer.Outdent();
                writer.Line("}");
            }
            else
            {
                writer.Line(sb + " =");
                writer.Indent();
                writer.Line(call);
                writer.Outdent();
            }

            return;
        }

        if (function.Body is not KotlinBody.Bridge bridge)
        {
            writer.Line(sb.ToString());
            return;
        }

        var export = bridge.Export;
        var arguments = BuildCallArguments(export, function.Parameters, resolver);
        var raw = $"NativeBridge.lib.{export.EntryPoint}({string.Join(", ", arguments)})";

        switch (export.Return)
        {
            case BridgeMarshal.Nothing:
                writer.Line(sb + " {");
                writer.Indent();
                writer.Line(raw);
                writer.Line("NativeBridge.check()");
                writer.Outdent();
                writer.Line("}");
                return;

            case BridgeMarshal.Blob:
                writer.Line(sb + " {");
                writer.Indent();
                EmitBufferReturn(writer, export, arguments, resolver);
                writer.Outdent();
                writer.Line("}");
                return;

            case var flagged when BridgeAbi.IsFlaggedReturn(flagged):
                writer.Line(sb + " {");
                writer.Indent();
                EmitFlaggedReturn(writer, export, arguments, resolver);
                writer.Outdent();
                writer.Line("}");
                return;

            default:
                writer.Line(sb + " =");
                writer.Indent();
                writer.Line(WrapReturn(export.Return, raw, resolver));
                writer.Outdent();
                return;
        }
    }

    private static string RenderDelegateArg(KDelegateArg argument, ImportResolver resolver) => argument switch
    {
        KDelegateArg.Ref reference => (reference.Spread ? "*" : "") + reference.Name,
        KDelegateArg.Default def => RenderExpr(def.Value, resolver),
        KDelegateArg.ConsumerAccept consumer => $"{{ {consumer.Name}.accept(this) }}",
        KDelegateArg.Converted converted => $"{converted.Name}.{converted.Conversion}()",
        _ => throw new InvalidOperationException($"Unknown delegate argument {argument.GetType().Name}"),
    };

    /// <summary>Nullable scalar/enum returns: value plus a has-value out-parameter.</summary>
    private void EmitFlaggedReturn(
        CodeWriter writer,
        NativeExport export,
        IReadOnlyList<string> arguments,
        ImportResolver resolver)
    {
        var convert = export.Return switch
        {
            BridgeMarshal.NullableScalar scalar => ScalarIn("raw", scalar.Kind),
            BridgeMarshal.EnumValue enumValue => $"{RenderTypeBare(views.EnumType(enumValue), resolver)}.fromValue(raw)",
            _ => throw new InvalidOperationException($"Marshal {export.Return.GetType().Name} is not a flagged return"),
        };

        var byteRef = resolver.ResolveName("com.sun.jna.ptr", "ByteByReference");
        writer.Line($"val outHasValue = {byteRef}()");
        writer.Line($"val raw = NativeBridge.lib.{export.EntryPoint}({string.Join(", ", arguments.Concat(["outHasValue"]))})");
        writer.Line("NativeBridge.check()");
        writer.Line($"return if (outHasValue.value.toInt() != 0) {convert} else null");
    }

    private void EmitBufferReturn(CodeWriter writer, NativeExport export, IReadOnlyList<string> arguments, ImportResolver resolver)
    {
        var pointerRef = resolver.ResolveName("com.sun.jna.ptr", "PointerByReference");
        var intRef = resolver.ResolveName("com.sun.jna.ptr", "IntByReference");

        writer.Line($"val outData = {pointerRef}()");
        writer.Line($"val outLength = {intRef}()");
        writer.Line($"NativeBridge.lib.{export.EntryPoint}({string.Join(", ", arguments.Concat(["outData", "outLength"]))})");
        writer.Line("NativeBridge.check()");
        writer.Line("return NativeBridge.takeBuffer(outData, outLength)");
    }

    // ---- Bridge argument marshaling ----

    private IReadOnlyList<string> BuildCallArguments(
        NativeExport export,
        IReadOnlyList<KotlinParameter> parameters,
        ImportResolver resolver)
    {
        var arguments = new List<string>();

        if (export.Receiver is not null)
            arguments.Add("nativeHandle");

        for (var i = 0; i < export.Parameters.Count; i++)
        {
            var marshal = export.Parameters[i].Marshal;
            var name = export.Parameters[i].Name;
            arguments.AddRange(ArgumentExpressions(name, marshal, resolver));
        }

        return arguments;
    }

    private IEnumerable<string> ArgumentExpressions(string name, BridgeMarshal marshal, ImportResolver resolver)
    {
        switch (marshal)
        {
            case BridgeMarshal.Scalar s:
                yield return ScalarOut(name, s.Kind);
                break;

            case BridgeMarshal.NullableScalar n:
                yield return $"(if ({name} != null) 1 else 0).toByte()";
                yield return NullableScalarValue(name, n.Kind);
                break;

            case BridgeMarshal.EnumValue enumValue:
                if (enumValue.Nullable)
                {
                    yield return $"(if ({name} != null) 1 else 0).toByte()";
                    yield return $"({name}?.value ?: 0)";
                }
                else
                {
                    yield return $"{name}.value";
                }
                break;

            case BridgeMarshal.Text:
                yield return name;
                break;

            case BridgeMarshal.DateTimeText d:
                yield return d.Nullable ? $"{name}?.toString()" : $"{name}.toString()";
                break;

            case BridgeMarshal.Blob b:
                yield return name;
                yield return b.Nullable ? $"({name}?.size ?: 0)" : $"{name}.size";
                break;

            case BridgeMarshal.Handle h:
                yield return h.Nullable ? $"({name}?.nativeHandle ?: 0L)" : $"{name}.nativeHandle";
                break;

            case BridgeMarshal.HandleSequence hs:
                if (hs.Container is SequenceContainer.Vararg or SequenceContainer.Array)
                {
                    yield return $"LongArray({name}.size) {{ {name}[it].nativeHandle }}";
                    yield return $"{name}.size";
                }
                else
                {
                    yield return $"{name}.map {{ it.nativeHandle }}.toLongArray()";
                    yield return $"{name}.count()";
                }
                break;

            case BridgeMarshal.TextSequence ts:
                if (ts.Container is SequenceContainer.Vararg or SequenceContainer.Array)
                {
                    yield return name;
                    yield return $"{name}.size";
                }
                else
                {
                    yield return $"{name}.toList().toTypedArray()";
                    yield return $"{name}.count()";
                }
                break;

            case BridgeMarshal.ScalarArray sa:
                if (sa.Container is SequenceContainer.Vararg or SequenceContainer.Array)
                {
                    yield return name;
                    yield return $"{name}.size";
                }
                else
                {
                    yield return $"{name}.toList().toFloatArray()";
                    yield return $"{name}.count()";
                }
                break;

            case BridgeMarshal.CallbackValue callback:
                yield return CallbackExpression(name, callback, resolver);
                break;

            case BridgeMarshal.UserImplValue user:
                yield return ProxyExpression(name, user, resolver);
                break;

            default:
                throw new InvalidOperationException($"Marshal {marshal.GetType().Name} cannot appear as an argument");
        }
    }

    private string CallbackExpression(string name, BridgeMarshal.CallbackValue callback, ImportResolver resolver)
    {
        if (!callback.Nullable)
            return CallbackAdapterExpression(name, callback.Adapter, resolver);

        return $"{name}?.let {{ cb -> {CallbackAdapterExpression("cb", callback.Adapter, resolver)} }}";
    }

    private string ProxyExpression(string name, BridgeMarshal.UserImplValue user, ImportResolver resolver)
    {
        string Create(string target)
        {
            var adapter = UserMethodAdapterExpression(target, user.Proxy, resolver);
            return $"NativeBridge.lib.{user.Proxy.ProxyExportEntryPoint}({adapter})";
        }

        return user.Nullable
            ? $"({name}?.let {{ obj -> {Create("obj")} }} ?: 0L)"
            : Create(name);
    }

    /// <summary>Adapter turning a Kotlin lambda value into a JNA callback of the planned shape.</summary>
    private string CallbackAdapterExpression(string lambdaReference, CallbackAdapter adapter, ImportResolver resolver)
    {
        var (parameterList, unwrapped) = UnwrapCallbackParameters(adapter, resolver);

        string invocation;
        if (adapter.FirstParameterIsDslScope)
        {
            var rest = unwrapped.Skip(1).ToList();
            invocation = $"{unwrapped[0]}.{lambdaReference}({string.Join(", ", rest)})";
        }
        else
        {
            invocation = $"{lambdaReference}({string.Join(", ", unwrapped)})";
        }

        var body = GuardedResult(adapter.ReturnWrap, invocation, resolver);
        var shapeName = resolver.ResolveName("com.questpdf.interop", adapter.Shape.Name);
        var arrow = parameterList.Count == 0 ? "" : string.Join(", ", parameterList) + " -> ";

        return $"NativeBridge.retain({shapeName} {{ {arrow}{body} }})";
    }

    /// <summary>Adapter forwarding a user object's method (IComponent.compose) as a JNA callback.</summary>
    private string UserMethodAdapterExpression(string objectReference, ProxyPlan proxy, ImportResolver resolver)
    {
        var adapter = proxy.Method;
        var (parameterList, unwrapped) = UnwrapCallbackParameters(adapter, resolver);
        var invocation = $"{objectReference}.{views.ProxyMethodName(proxy)}({string.Join(", ", unwrapped)})";
        var body = GuardedResult(adapter.ReturnWrap, invocation, resolver);
        var shapeName = resolver.ResolveName("com.questpdf.interop", adapter.Shape.Name);
        var arrow = parameterList.Count == 0 ? "" : string.Join(", ", parameterList) + " -> ";

        return $"NativeBridge.retain({shapeName} {{ {arrow}{body} }})";
    }

    private (IReadOnlyList<string> ParameterNames, IReadOnlyList<string> Unwrapped) UnwrapCallbackParameters(
        CallbackAdapter adapter, ImportResolver resolver)
    {
        var parameterNames = Enumerable.Range(0, adapter.Shape.ParameterSlots.Count).Select(i => $"p{i}").ToList();
        var unwrapped = new List<string>();
        var slot = 0;

        foreach (var wrap in adapter.ParameterWraps)
        {
            switch (wrap)
            {
                case BridgeMarshal.Scalar s:
                    unwrapped.Add(ScalarIn($"p{slot}", s.Kind));
                    slot += 1;
                    break;

                case BridgeMarshal.NullableScalar n:
                    unwrapped.Add($"(if (p{slot}.toInt() != 0) {ScalarIn($"p{slot + 1}", n.Kind)} else null)");
                    slot += 2;
                    break;

                case BridgeMarshal.EnumValue { Nullable: true } e:
                    unwrapped.Add($"(if (p{slot}.toInt() != 0) {RenderTypeBare(views.EnumType(e), resolver)}.fromValue(p{slot + 1}) else null)");
                    slot += 2;
                    break;

                case BridgeMarshal.EnumValue e:
                    unwrapped.Add($"{RenderTypeBare(views.EnumType(e), resolver)}.fromValue(p{slot})");
                    slot += 1;
                    break;

                case BridgeMarshal.Text:
                    unwrapped.Add($"p{slot}");
                    slot += 1;
                    break;

                case BridgeMarshal.Handle h:
                    var wrapName = RenderTypeBare(views.WrapType(h), resolver);
                    unwrapped.Add(h.Nullable
                        ? $"(if (p{slot} == 0L) null else {wrapName}(p{slot}))"
                        : $"{wrapName}(p{slot})");
                    slot += 1;
                    break;

                default:
                    throw new InvalidOperationException($"Marshal {wrap.GetType().Name} cannot cross into a callback");
            }
        }

        return (parameterNames, unwrapped);
    }

    private static string GuardedResult(BridgeMarshal returnWrap, string invocation, ImportResolver resolver) => returnWrap switch
    {
        // The Unit reference must resolve: QuestPDF's Unit enum shadows kotlin.Unit.
        BridgeMarshal.Nothing =>
            $"NativeBridge.guard({resolver.ResolveName("kotlin", "Unit")}) {{ {invocation} }}",
        BridgeMarshal.Scalar s =>
            $"NativeBridge.guard({SlotDefault(BridgeAbi.ScalarSlot(s.Kind))}) {{ {ScalarOut($"({invocation})", s.Kind)} }}",
        BridgeMarshal.EnumValue =>
            $"NativeBridge.guard(0) {{ ({invocation}).value }}",
        BridgeMarshal.Handle h =>
            h.Nullable
                ? $"NativeBridge.guard(0L) {{ ({invocation})?.nativeHandle ?: 0L }}"
                : $"NativeBridge.guard(0L) {{ ({invocation}).nativeHandle }}",
        BridgeMarshal.Text t =>
            t.Nullable
                ? $"NativeBridge.guard(0L) {{ ({invocation})?.let {{ s -> NativeBridge.registerString(s) }} ?: 0L }}"
                : $"NativeBridge.guard(0L) {{ NativeBridge.registerString({invocation}) }}",
        BridgeMarshal.Blob b =>
            b.Nullable
                ? $"NativeBridge.guard(0L) {{ ({invocation})?.let {{ bytes -> NativeBridge.registerBuffer(bytes) }} ?: 0L }}"
                : $"NativeBridge.guard(0L) {{ NativeBridge.registerBuffer({invocation}) }}",
        _ => throw new InvalidOperationException($"Marshal {returnWrap.GetType().Name} cannot be returned from a callback"),
    };

    private string WrapReturn(BridgeMarshal marshal, string raw, ImportResolver resolver) => marshal switch
    {
        BridgeMarshal.Scalar s => ScalarIn($"NativeBridge.checked({raw})", s.Kind),
        BridgeMarshal.EnumValue e => $"{RenderTypeBare(views.EnumType(e), resolver)}.fromValue(NativeBridge.checked({raw}))",
        BridgeMarshal.Handle h => h.Nullable
            ? $"NativeBridge.checked({raw}).let {{ if (it == 0L) null else {RenderTypeBare(views.WrapType(h), resolver)}(it) }}"
            : $"{RenderTypeBare(views.WrapType(h), resolver)}(NativeBridge.checked({raw}))",
        BridgeMarshal.Text t => $"NativeBridge.takeString(NativeBridge.checked({raw}))" + (t.Nullable ? "" : "!!"),
        BridgeMarshal.DateTimeText d =>
            $"NativeBridge.takeString(NativeBridge.checked({raw}))?.let {{ {RenderTypeBare(views.TemporalType(d), resolver)}.parse(it) }}" +
            (d.Nullable ? "" : "!!"),
        _ => throw new InvalidOperationException($"Marshal {marshal.GetType().Name} cannot be a direct return"),
    };

    private static string ScalarOut(string expression, ScalarKind kind) => kind switch
    {
        ScalarKind.Boolean => $"(if ({expression}) 1 else 0)",
        ScalarKind.UByte => $"{expression}.toByte()",
        ScalarKind.UShort => $"{expression}.toShort()",
        ScalarKind.UInt => $"{expression}.toInt()",
        ScalarKind.ULong => $"{expression}.toLong()",
        _ => expression,
    };

    private static string ScalarIn(string expression, ScalarKind kind) => kind switch
    {
        ScalarKind.Boolean => $"({expression} != 0)",
        ScalarKind.UByte => $"{expression}.toUByte()",
        ScalarKind.UShort => $"{expression}.toUShort()",
        ScalarKind.UInt => $"{expression}.toUInt()",
        ScalarKind.ULong => $"{expression}.toULong()",
        _ => expression,
    };

    private static string NullableScalarValue(string name, ScalarKind kind) => kind switch
    {
        ScalarKind.Boolean => $"(if ({name} == true) 1 else 0)",
        ScalarKind.Byte => $"({name} ?: 0.toByte())",
        ScalarKind.UByte => $"({name}?.toByte() ?: 0.toByte())",
        ScalarKind.Short => $"({name} ?: 0.toShort())",
        ScalarKind.UShort => $"({name}?.toShort() ?: 0.toShort())",
        ScalarKind.Int => $"({name} ?: 0)",
        ScalarKind.UInt => $"({name}?.toInt() ?: 0)",
        ScalarKind.Long => $"({name} ?: 0L)",
        ScalarKind.ULong => $"({name}?.toLong() ?: 0L)",
        ScalarKind.Float => $"({name} ?: 0f)",
        ScalarKind.Double => $"({name} ?: 0.0)",
        _ => throw new InvalidOperationException($"Unknown scalar kind {kind}"),
    };

    private static string SlotDefault(AbiSlot slot) => slot switch
    {
        AbiSlot.Byte => "0.toByte()",
        AbiSlot.Short => "0.toShort()",
        AbiSlot.Int => "0",
        AbiSlot.Long => "0L",
        AbiSlot.Float => "0f",
        AbiSlot.Double => "0.0",
        _ => throw new InvalidOperationException($"Slot {slot} has no default"),
    };

    private static string RenderParameter(KotlinParameter parameter, ImportResolver resolver)
    {
        var sb = new StringBuilder();
        if (parameter.IsVararg)
            sb.Append("vararg ");

        sb.Append(parameter.Name).Append(": ").Append(RenderType(parameter.Type, resolver));

        if (parameter.DefaultValue is not null)
            sb.Append(" = ").Append(RenderExpr(parameter.DefaultValue, resolver));

        return sb.ToString();
    }

    // ---- Types and expressions ----

    private static string RenderType(KType type, ImportResolver resolver)
    {
        if (type.IsFunctionType)
        {
            var sb = new StringBuilder();
            if (type.LambdaReceiver is not null)
                sb.Append(RenderType(type.LambdaReceiver, resolver)).Append('.');

            sb.Append('(');
            sb.Append(string.Join(", ", type.FunctionParameters.Select(p =>
                AutoName().IsMatch(p.Name)
                    ? RenderType(p.Type, resolver)
                    : p.Name + ": " + RenderType(p.Type, resolver))));
            sb.Append(") -> ");
            sb.Append(RenderType(type.FunctionReturn ?? KType.Unit, resolver));

            return type.IsNullable ? "(" + sb + ")?" : sb.ToString();
        }

        return RenderTypeBare(type, resolver) + (type.IsNullable ? "?" : "");
    }

    private static string RenderTypeBare(KType type, ImportResolver resolver)
    {
        if (type.IsGenericParameter)
            return type.Name;

        var name = resolver.Resolve(type);
        if (type.TypeArguments.Count == 0)
            return name;

        return name + "<" + string.Join(", ", type.TypeArguments.Select(a => RenderType(a, resolver))) + ">";
    }

    private static string RenderExpr(KExpr expr, ImportResolver resolver) => expr switch
    {
        KExpr.Null => "null",
        KExpr.Literal literal => literal.Text,
        KExpr.StringLiteral s => Quote(s.Value),
        KExpr.EnumEntry entry => RenderTypeBare(entry.EnumType, resolver) + "." + entry.EntryName,
        _ => throw new InvalidOperationException($"Unknown expression {expr.GetType().Name}"),
    };

    private static string Quote(string value)
    {
        var sb = new StringBuilder("\"");
        foreach (var c in value)
        {
            sb.Append(c switch
            {
                '\\' => "\\\\",
                '"' => "\\\"",
                '$' => "\\$",
                '\n' => "\\n",
                '\r' => "\\r",
                '\t' => "\\t",
                _ => c.ToString(),
            });
        }

        return sb.Append('"').ToString();
    }

    private static void EmitKDoc(CodeWriter writer, string? rawXml)
    {
        var lines = KDocConverter.ToKDocLines(rawXml);
        if (lines.Count == 0)
            return;

        writer.Line("/**");
        foreach (var line in lines)
            writer.Line((" * " + line).TrimEnd());
        writer.Line(" */");
    }

    private static void EmitDeprecated(CodeWriter writer, string? message)
    {
        if (message is null)
            return;

        var escaped = message.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", " ").Replace("\r", " ").Replace("$", "\\$");
        writer.Line($"@Deprecated(\"{escaped}\")");
    }

    private static string TypeParameterList(KotlinTypeDeclaration type) =>
        type.TypeParameters.Count == 0 ? "" : "<" + string.Join(", ", type.TypeParameters) + ">";

    [GeneratedRegex("^arg\\d+$")]
    private static partial Regex AutoName();
}
