// <auto-generated>
// Generated by QuestPDF.Interop.Generator from QuestPDF 2026.7.1.0.
// Do not edit — this file is wiped and recreated on every generator run.
// </auto-generated>

import koffi from 'koffi';

// One koffi prototype per callback ABI shape. The manual runtime
// registers JS functions against these prototypes (Native.retain) and
// keeps the registrations alive while native code may still call them.

export const NativeCallbackBIToJ = koffi.proto('int64_t NativeCallbackBIToJ(int8_t p0, int32_t p1)');

export const NativeCallbackIToJ = koffi.proto('int64_t NativeCallbackIToJ(int32_t p0)');

export const NativeCallbackJToI = koffi.proto('int32_t NativeCallbackJToI(int64_t p0)');

export const NativeCallbackJToJ = koffi.proto('int64_t NativeCallbackJToJ(int64_t p0)');

export const NativeCallbackJToV = koffi.proto('void NativeCallbackJToV(int64_t p0)');
