using System.Text;
using QuestPDF.Interop.Generator.Core.Bridge;

namespace QuestPDF.Interop.Generator.Core.NativeEmission;

/// <summary>
/// Emits the C# side of the bridge from the language-neutral interop model:
/// one static class of UnmanagedCallersOnly exports per client type group,
/// plus proxy classes for user-implemented interfaces. Every export resolves
/// handles, converts arguments, invokes the real QuestPDF member and reports
/// exceptions through the error callback instead of letting them cross the
/// native boundary. This single emission serves every language backend.
/// </summary>
public static class NativeExportsEmitter
{
    public static IReadOnlyDictionary<string, string> Emit(InteropModel model)
    {
        var files = new SortedDictionary<string, string>(StringComparer.Ordinal);

        foreach (var group in model.Exports.GroupBy(e => e.Group).OrderBy(g => g.Key, StringComparer.Ordinal))
            files[$"Exports/{group.Key}.g.cs"] = EmitGroup(model, group.Key, group.OrderBy(e => e.EntryPoint, StringComparer.Ordinal).ToList());

        if (model.Proxies.Count > 0)
            files["Exports/Proxies.g.cs"] = EmitProxies(model);

        return files;
    }

    private static string FileHeader(InteropModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"// Generated by {GeneratorInfo.ToolName} from QuestPDF {model.SourceAssemblyVersion}.");
        sb.AppendLine("// Do not edit — this file is wiped and recreated on every generator run.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0612, CS0618, CS0619 // deliberate calls to [Obsolete] members: the bridge mirrors the full public surface");
        sb.AppendLine("#pragma warning disable CS8604, CS8600, CS8625 // the client side enforces non-null contracts; nulls crossing anyway surface as .NET exceptions on the error channel");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();
        sb.AppendLine("namespace QuestPDF.Native;");
        sb.AppendLine();
        return sb.ToString();
    }

    private static string EmitGroup(InteropModel model, string group, IReadOnlyList<NativeExport> exports)
    {
        var sb = new StringBuilder(FileHeader(model));
        sb.AppendLine($"public static unsafe class Exports_{group}");
        sb.AppendLine("{");

        for (var i = 0; i < exports.Count; i++)
        {
            if (i > 0)
                sb.AppendLine();
            EmitExport(sb, exports[i]);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitExport(StringBuilder sb, NativeExport export)
    {
        var signatureParameters = new List<string>();
        if (export.Receiver is not null)
            signatureParameters.Add("long self");

        foreach (var parameter in export.Parameters)
            foreach (var abi in BridgeAbi.ParameterLayout(parameter.Name, parameter.Marshal))
                signatureParameters.Add($"{CSharpSlotType(abi)} {abi.Name}");

        var returnSlot = BridgeAbi.ReturnLayout(export.Return);
        if (returnSlot == AbiSlot.BufferOut)
        {
            signatureParameters.Add("byte** outData");
            signatureParameters.Add("int* outLength");
        }
        else if (BridgeAbi.IsFlaggedReturn(export.Return))
        {
            signatureParameters.Add("byte* outHasValue");
        }

        var returnType = returnSlot switch
        {
            AbiSlot.Void or AbiSlot.BufferOut => "void",
            AbiSlot.TextReturn => "nint",
            _ => CSharpScalarType(returnSlot),
        };

        sb.AppendLine($"    [UnmanagedCallersOnly(EntryPoint = \"{export.EntryPoint}\")]");
        sb.AppendLine($"    public static {returnType} {export.EntryPoint}({string.Join(", ", signatureParameters)})");
        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");

        var body = new List<string>();

        if (export.Receiver is not null)
            body.Add($"var receiver = Interop.Handles.Get<global::{export.Receiver.CSharpType}>(self);");

        // Callback parameters become delegate adapter locals before the call.
        var argumentExpressions = new List<string>();
        foreach (var parameter in export.Parameters)
        {
            if (parameter.Marshal is BridgeMarshal.CallbackValue callback)
            {
                EmitCallbackAdapterLocal(body, parameter.Name, callback);
                argumentExpressions.Add(parameter.Name + "Adapter");
            }
            else
            {
                argumentExpressions.Add(ParameterInExpression(parameter.Name, parameter.Marshal));
            }
        }

        var call = RenderInvocation(export.Invocation, export.Receiver is not null ? "receiver" : null, argumentExpressions);

        switch (export.Return)
        {
            case BridgeMarshal.Nothing:
                body.Add(call + ";");
                break;

            case BridgeMarshal.Blob:
                body.Add($"var result = {call};");
                body.Add("Interop.WriteBuffer(result, outData, outLength);");
                break;

            case BridgeMarshal.NullableScalar nullableScalar:
                body.Add($"var result = {call};");
                body.Add("*outHasValue = (byte)(result.HasValue ? 1 : 0);");
                body.Add($"return {ScalarOut("result.GetValueOrDefault()", nullableScalar.Kind)};");
                break;

            case BridgeMarshal.EnumValue { Nullable: true }:
                body.Add($"var result = {call};");
                body.Add("*outHasValue = (byte)(result.HasValue ? 1 : 0);");
                body.Add("return (int)result.GetValueOrDefault();");
                break;

            default:
                body.Add($"var result = {call};");
                body.Add($"return {ReturnOutExpression("result", export.Return)};");
                break;
        }

        foreach (var line in body)
            sb.AppendLine("            " + line);

        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception exception)");
        sb.AppendLine("        {");
        sb.AppendLine("            Interop.ReportError(exception);");

        switch (returnSlot)
        {
            case AbiSlot.Void:
                break;
            case AbiSlot.BufferOut:
                sb.AppendLine("            *outData = null;");
                sb.AppendLine("            *outLength = 0;");
                break;
            case AbiSlot.TextReturn:
                sb.AppendLine("            return 0;");
                break;
            default:
                if (BridgeAbi.IsFlaggedReturn(export.Return))
                    sb.AppendLine("            *outHasValue = 0;");
                sb.AppendLine("            return default;");
                break;
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    // ---- callback adapters (C# delegate wrapping the client function pointer) ----

    private static void EmitCallbackAdapterLocal(List<string> body, string name, BridgeMarshal.CallbackValue callback)
    {
        var adapter = callback.Adapter;
        var lambdaParameters = adapter.ParameterWraps.Select((_, i) => $"x{i}").ToList();
        var functionPointer = FunctionPointerType(adapter.Shape);

        var lines = new List<string>();
        var callArguments = new List<string>();
        var preludes = new List<string>();
        var cleanups = new List<string>();

        for (var i = 0; i < adapter.ParameterWraps.Count; i++)
        {
            var wrap = adapter.ParameterWraps[i];
            var argument = $"x{i}";
            switch (wrap)
            {
                case BridgeMarshal.Scalar s:
                    callArguments.Add(ScalarOut(argument, s.Kind));
                    break;

                case BridgeMarshal.NullableScalar n:
                    callArguments.Add($"(byte)({argument}.HasValue ? 1 : 0)");
                    callArguments.Add(ScalarOut($"{argument}.GetValueOrDefault()", n.Kind));
                    break;

                case BridgeMarshal.EnumValue { Nullable: true }:
                    callArguments.Add($"(byte)({argument}.HasValue ? 1 : 0)");
                    callArguments.Add($"(int){argument}.GetValueOrDefault()");
                    break;

                case BridgeMarshal.EnumValue:
                    callArguments.Add($"(int){argument}");
                    break;

                case BridgeMarshal.Text:
                    preludes.Add($"var text{i} = Interop.AllocUtf8({argument});");
                    cleanups.Add($"Interop.FreeUtf8(text{i});");
                    callArguments.Add($"(byte*)text{i}");
                    break;

                case BridgeMarshal.Handle:
                    preludes.Add($"var handle{i} = Interop.Handles.Register({argument});");
                    cleanups.Add($"Interop.Handles.Release(handle{i});");
                    callArguments.Add($"handle{i}");
                    break;

                default:
                    throw new InvalidOperationException($"Marshal {wrap.GetType().Name} cannot cross into a callback");
            }
        }

        lines.Add($"var fn = ({functionPointer})cb;");
        lines.AddRange(preludes);

        var invocation = $"fn({string.Join(", ", callArguments)})";
        string coreStatement;
        var hasReturn = adapter.ReturnWrap is not BridgeMarshal.Nothing;
        coreStatement = hasReturn ? $"var r = {invocation};" : $"{invocation};";

        if (cleanups.Count > 0)
        {
            lines.Add("try");
            lines.Add("{");
            lines.Add("    " + coreStatement);
            if (hasReturn)
                lines.Add($"    return {CallbackReturnInExpression("r", adapter.ReturnWrap)};");
            lines.Add("}");
            lines.Add("finally");
            lines.Add("{");
            foreach (var cleanup in cleanups)
                lines.Add("    " + cleanup);
            lines.Add("}");
        }
        else
        {
            lines.Add(coreStatement);
            if (hasReturn)
                lines.Add($"return {CallbackReturnInExpression("r", adapter.ReturnWrap)};");
        }

        var lambdaHeader = lambdaParameters.Count == 1 ? lambdaParameters[0] : "(" + string.Join(", ", lambdaParameters) + ")";
        var delegateCast = $"(global::{callback.CSharpDelegateType})";

        body.Add($"var {name}Adapter = {name} == 0 ? null : {delegateCast}({lambdaHeader} =>");
        body.Add("{");
        body.Add($"    var cb = {name};");
        foreach (var line in lines)
            body.Add("    " + line);
        body.Add("});");
    }

    private static string FunctionPointerType(CallbackShape shape)
    {
        var slots = shape.ParameterSlots.Select(CSharpCallbackSlotType).ToList();
        slots.Add(shape.ReturnSlot == AbiSlot.Void ? "void" : CSharpScalarType(shape.ReturnSlot));
        return $"delegate* unmanaged[Cdecl]<{string.Join(", ", slots)}>";
    }

    private static string CallbackReturnInExpression(string value, BridgeMarshal wrap) => wrap switch
    {
        BridgeMarshal.Scalar s => ScalarIn(value, s.Kind),
        BridgeMarshal.EnumValue e => $"(global::{e.CSharpEnum}){value}",
        BridgeMarshal.Handle h => h.Nullable
            ? $"({value} == 0 ? null : Interop.Handles.Get<global::{h.CSharpType}>({value}))"
            : $"Interop.Handles.Get<global::{h.CSharpType}>({value})",
        BridgeMarshal.Text t => $"Interop.Handles.TakeString({value})" + (t.Nullable ? "" : "!"),
        BridgeMarshal.Blob b => $"Interop.Handles.TakeBuffer({value})" + (b.Nullable ? "" : "!"),
        _ => throw new InvalidOperationException($"Marshal {wrap.GetType().Name} cannot be returned from a callback"),
    };

    // ---- parameter/return conversions ----

    private static string ParameterInExpression(string name, BridgeMarshal marshal) => marshal switch
    {
        BridgeMarshal.Scalar s => ScalarIn(name, s.Kind),
        BridgeMarshal.NullableScalar n => $"({name}HasValue != 0 ? {ScalarIn(name, n.Kind)} : ({NullableScalarCSharpType(n.Kind)}?)null)",
        BridgeMarshal.EnumValue { Nullable: true } e => $"({name}HasValue != 0 ? (global::{e.CSharpEnum}?)(global::{e.CSharpEnum}){name} : null)",
        BridgeMarshal.EnumValue e => $"(global::{e.CSharpEnum}){name}",
        BridgeMarshal.Text => $"Interop.ToStringUtf8({name})" ,
        BridgeMarshal.DateTimeText d => d.CSharpType == "System.DateTime"
            ? (d.Nullable ? $"Interop.ParseDateTime({name})" : $"Interop.ParseDateTime({name})!.Value")
            : (d.Nullable ? $"Interop.ParseDateTimeOffset({name})" : $"Interop.ParseDateTimeOffset({name})!.Value"),
        BridgeMarshal.Blob b => $"Interop.ToByteArray({name}, {name}Length)" + (b.Nullable ? "" : "!"),
        BridgeMarshal.Handle h => h.Nullable
            ? $"({name} == 0 ? null : Interop.Handles.Get<global::{h.CSharpType}>({name}))"
            : $"Interop.Handles.Get<global::{h.CSharpType}>({name})",
        BridgeMarshal.HandleSequence hs => $"Interop.ToObjectArray<global::{hs.Element.CSharpType}>({name}, {name}Count)",
        BridgeMarshal.TextSequence => $"Interop.ToStringArray({name}, {name}Count)",
        BridgeMarshal.ScalarArray => $"Interop.ToFloatArray({name}, {name}Count)",
        BridgeMarshal.UserImplValue u => u.Nullable
            ? $"({name} == 0 ? null : Interop.Handles.Get<global::{u.Proxy.CSharpInterface}>({name}))"
            : $"Interop.Handles.Get<global::{u.Proxy.CSharpInterface}>({name})",
        _ => throw new InvalidOperationException($"Marshal {marshal.GetType().Name} cannot appear as a parameter"),
    };

    private static string ReturnOutExpression(string value, BridgeMarshal marshal) => marshal switch
    {
        BridgeMarshal.Scalar s => ScalarOut(value, s.Kind),
        BridgeMarshal.EnumValue => $"(int){value}",
        BridgeMarshal.Handle h => h.Nullable
            ? $"({value} is null ? 0L : Interop.Handles.Register({value}))"
            : $"Interop.Handles.Register({value})",
        BridgeMarshal.Text => $"Interop.AllocUtf8Return({value})",
        BridgeMarshal.DateTimeText => $"Interop.AllocUtf8Return(Interop.FormatRoundTrip({value}))",
        _ => throw new InvalidOperationException($"Marshal {marshal.GetType().Name} cannot be a direct return"),
    };

    private static string RenderInvocation(CSharpInvocation invocation, string? receiver, IReadOnlyList<string> arguments)
    {
        var generics = invocation.GenericArguments.Count == 0
            ? ""
            : "<" + string.Join(", ", invocation.GenericArguments.Select(a => "global::" + a)) + ">";

        return invocation.Kind switch
        {
            InvocationKind.ExtensionMethod =>
                $"global::{invocation.DeclaringType}.{invocation.MemberName}{generics}({string.Join(", ", new[] { receiver! }.Concat(arguments))})",
            InvocationKind.InstanceMethod =>
                $"{receiver}.{invocation.MemberName}{generics}({string.Join(", ", arguments)})",
            InvocationKind.StaticMethod =>
                $"global::{invocation.DeclaringType}.{invocation.MemberName}{generics}({string.Join(", ", arguments)})",
            InvocationKind.Constructor =>
                $"new global::{invocation.DeclaringType}({string.Join(", ", arguments)})",
            InvocationKind.PropertyGet =>
                $"{receiver}.{invocation.MemberName}",
            InvocationKind.StaticPropertyGet =>
                $"global::{invocation.DeclaringType}.{invocation.MemberName}",
            InvocationKind.PropertySet =>
                $"{receiver}.{invocation.MemberName} = {arguments[0]}",
            InvocationKind.StaticPropertySet =>
                $"global::{invocation.DeclaringType}.{invocation.MemberName} = {arguments[0]}",
            InvocationKind.ConversionFromSelf =>
                $"(global::{invocation.MemberName}){receiver}",
            InvocationKind.ConversionToSelf =>
                $"(global::{invocation.DeclaringType})({arguments[0]})",
            _ => throw new InvalidOperationException($"Unknown invocation kind {invocation.Kind}"),
        };
    }

    // ---- proxies ----

    private static string EmitProxies(InteropModel model)
    {
        var sb = new StringBuilder(FileHeader(model));
        sb.AppendLine("// Proxy classes implementing user-implementable QuestPDF interfaces by");
        sb.AppendLine("// forwarding to callbacks supplied by the client.");

        foreach (var proxy in model.Proxies)
        {
            var adapter = proxy.Method;
            var parameters = proxy.CSharpParameterTypes
                .Select((type, i) => $"global::{type} x{i}")
                .ToList();
            var returnType = proxy.CSharpReturnType is null ? "void" : "global::" + proxy.CSharpReturnType;

            sb.AppendLine();
            sb.AppendLine($"internal sealed unsafe class {proxy.CSharpClassName} : global::{proxy.CSharpInterface}");
            sb.AppendLine("{");
            sb.AppendLine("    private readonly nint callback;");
            sb.AppendLine();
            sb.AppendLine($"    public {proxy.CSharpClassName}(nint callback) => this.callback = callback;");
            sb.AppendLine();
            sb.AppendLine($"    public {returnType} {proxy.CSharpMethodName}({string.Join(", ", parameters)})");
            sb.AppendLine("    {");
            sb.AppendLine($"        var fn = ({FunctionPointerType(adapter.Shape)})callback;");

            var callArguments = new List<string>();
            var cleanups = new List<string>();
            for (var i = 0; i < adapter.ParameterWraps.Count; i++)
            {
                switch (adapter.ParameterWraps[i])
                {
                    case BridgeMarshal.Scalar s:
                        callArguments.Add(ScalarOut($"x{i}", s.Kind));
                        break;
                    case BridgeMarshal.EnumValue:
                        callArguments.Add($"(int)x{i}");
                        break;
                    case BridgeMarshal.Handle:
                        sb.AppendLine($"        var handle{i} = Interop.Handles.Register(x{i});");
                        cleanups.Add($"Interop.Handles.Release(handle{i});");
                        callArguments.Add($"handle{i}");
                        break;
                    default:
                        throw new InvalidOperationException($"Proxy parameter marshal {adapter.ParameterWraps[i].GetType().Name} is not supported");
                }
            }

            var invocation = $"fn({string.Join(", ", callArguments)})";
            var hasReturn = adapter.ReturnWrap is not BridgeMarshal.Nothing;

            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine(hasReturn ? $"            var r = {invocation};" : $"            {invocation};");
            if (hasReturn)
                sb.AppendLine($"            return {CallbackReturnInExpression("r", adapter.ReturnWrap)};");
            sb.AppendLine("        }");
            sb.AppendLine("        finally");
            sb.AppendLine("        {");
            foreach (var cleanup in cleanups)
                sb.AppendLine("            " + cleanup);
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            sb.AppendLine();
            sb.AppendLine($"public static unsafe class ProxyExports_{proxy.CSharpClassName}");
            sb.AppendLine("{");
            sb.AppendLine($"    [UnmanagedCallersOnly(EntryPoint = \"{proxy.ProxyExportEntryPoint}\")]");
            sb.AppendLine($"    public static long {proxy.ProxyExportEntryPoint}(nint callback)");
            sb.AppendLine("    {");
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine($"            return Interop.Handles.Register(new {proxy.CSharpClassName}(callback));");
            sb.AppendLine("        }");
            sb.AppendLine("        catch (Exception exception)");
            sb.AppendLine("        {");
            sb.AppendLine("            Interop.ReportError(exception);");
            sb.AppendLine("            return 0;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    // ---- slot/type rendering ----

    private static string CSharpSlotType(AbiParameter parameter) => parameter.Slot switch
    {
        AbiSlot.Text => "byte*",
        AbiSlot.Bytes => "byte*",
        AbiSlot.FloatArray => "float*",
        AbiSlot.LongArray => "long*",
        AbiSlot.TextArray => "byte**",
        AbiSlot.Callback => "nint",
        _ => CSharpScalarType(parameter.Slot),
    };

    private static string CSharpCallbackSlotType(AbiSlot slot) => slot switch
    {
        AbiSlot.Text => "byte*",
        _ => CSharpScalarType(slot),
    };

    private static string CSharpScalarType(AbiSlot slot) => slot switch
    {
        AbiSlot.Byte => "byte",
        AbiSlot.Short => "short",
        AbiSlot.Int => "int",
        AbiSlot.Long => "long",
        AbiSlot.Float => "float",
        AbiSlot.Double => "double",
        _ => throw new InvalidOperationException($"Slot {slot} is not a scalar"),
    };

    private static string NullableScalarCSharpType(ScalarKind kind) => kind switch
    {
        ScalarKind.Boolean => "bool",
        ScalarKind.Byte => "sbyte",
        ScalarKind.UByte => "byte",
        ScalarKind.Short => "short",
        ScalarKind.UShort => "ushort",
        ScalarKind.Int => "int",
        ScalarKind.UInt => "uint",
        ScalarKind.Long => "long",
        ScalarKind.ULong => "ulong",
        ScalarKind.Float => "float",
        ScalarKind.Double => "double",
        _ => throw new InvalidOperationException($"Unknown scalar kind {kind}"),
    };

    /// <summary>Slot value → C# value (parameters coming in from the ABI).</summary>
    private static string ScalarIn(string expression, ScalarKind kind) => kind switch
    {
        ScalarKind.Boolean => $"({expression} != 0)",
        ScalarKind.Byte => $"unchecked((sbyte){expression})",
        ScalarKind.UShort => $"unchecked((ushort){expression})",
        ScalarKind.UInt => $"unchecked((uint){expression})",
        ScalarKind.ULong => $"unchecked((ulong){expression})",
        _ => expression,
    };

    /// <summary>C# value → slot value (returns and callback arguments going out).</summary>
    private static string ScalarOut(string expression, ScalarKind kind) => kind switch
    {
        ScalarKind.Boolean => $"({expression} ? 1 : 0)",
        ScalarKind.Byte => $"unchecked((byte){expression})",
        ScalarKind.UShort => $"unchecked((short){expression})",
        ScalarKind.UInt => $"unchecked((int){expression})",
        ScalarKind.ULong => $"unchecked((long){expression})",
        _ => expression,
    };
}
