// <auto-generated>
// Generated by QuestPDF.Interop.Generator from QuestPDF 2026.7.1.0.
// Do not edit — this file is wiped and recreated on every generator run.
// </auto-generated>
#nullable enable
#pragma warning disable CS0612, CS0618, CS0619 // deliberate calls to [Obsolete] members: the bridge mirrors the full public surface
#pragma warning disable CS8604, CS8600, CS8625 // the client side enforces non-null contracts; nulls crossing anyway surface as .NET exceptions on the error channel

using System;
using System.Runtime.InteropServices;

namespace QuestPDF.Native;

public static unsafe class Exports_Color
{
    [UnmanagedCallersOnly(EntryPoint = "QP_Color_ctor_0")]
    public static long QP_Color_ctor_0(int hex)
    {
        try
        {
            var result = new global::QuestPDF.Infrastructure.Color(unchecked((uint)hex));
            return Interop.Handles.Register(result);
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
            return default;
        }
    }

    [UnmanagedCallersOnly(EntryPoint = "QP_Color_fromARGB_0")]
    public static long QP_Color_fromARGB_0(byte alpha, byte red, byte green, byte blue)
    {
        try
        {
            var result = global::QuestPDF.Infrastructure.Color.FromARGB(alpha, red, green, blue);
            return Interop.Handles.Register(result);
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
            return default;
        }
    }

    [UnmanagedCallersOnly(EntryPoint = "QP_Color_fromHex_0")]
    public static long QP_Color_fromHex_0(byte* hex)
    {
        try
        {
            var result = global::QuestPDF.Infrastructure.Color.FromHex(Interop.ToStringUtf8(hex));
            return Interop.Handles.Register(result);
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
            return default;
        }
    }

    [UnmanagedCallersOnly(EntryPoint = "QP_Color_fromRGB_0")]
    public static long QP_Color_fromRGB_0(byte red, byte green, byte blue)
    {
        try
        {
            var result = global::QuestPDF.Infrastructure.Color.FromRGB(red, green, blue);
            return Interop.Handles.Register(result);
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
            return default;
        }
    }

    [UnmanagedCallersOnly(EntryPoint = "QP_Color_from_0")]
    public static long QP_Color_from_0(byte* hex)
    {
        try
        {
            var result = (global::QuestPDF.Infrastructure.Color)(Interop.ToStringUtf8(hex));
            return Interop.Handles.Register(result);
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
            return default;
        }
    }

    [UnmanagedCallersOnly(EntryPoint = "QP_Color_from_1")]
    public static long QP_Color_from_1(int hex)
    {
        try
        {
            var result = (global::QuestPDF.Infrastructure.Color)(unchecked((uint)hex));
            return Interop.Handles.Register(result);
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
            return default;
        }
    }

    [UnmanagedCallersOnly(EntryPoint = "QP_Color_getAlpha_0")]
    public static byte QP_Color_getAlpha_0(long self)
    {
        try
        {
            var receiver = Interop.Handles.Get<global::QuestPDF.Infrastructure.Color>(self);
            var result = receiver.Alpha;
            return result;
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
            return default;
        }
    }

    [UnmanagedCallersOnly(EntryPoint = "QP_Color_getBlue_0")]
    public static byte QP_Color_getBlue_0(long self)
    {
        try
        {
            var receiver = Interop.Handles.Get<global::QuestPDF.Infrastructure.Color>(self);
            var result = receiver.Blue;
            return result;
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
            return default;
        }
    }

    [UnmanagedCallersOnly(EntryPoint = "QP_Color_getGreen_0")]
    public static byte QP_Color_getGreen_0(long self)
    {
        try
        {
            var receiver = Interop.Handles.Get<global::QuestPDF.Infrastructure.Color>(self);
            var result = receiver.Green;
            return result;
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
            return default;
        }
    }

    [UnmanagedCallersOnly(EntryPoint = "QP_Color_getHex_0")]
    public static int QP_Color_getHex_0(long self)
    {
        try
        {
            var receiver = Interop.Handles.Get<global::QuestPDF.Infrastructure.Color>(self);
            var result = receiver.Hex;
            return unchecked((int)result);
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
            return default;
        }
    }

    [UnmanagedCallersOnly(EntryPoint = "QP_Color_getRed_0")]
    public static byte QP_Color_getRed_0(long self)
    {
        try
        {
            var receiver = Interop.Handles.Get<global::QuestPDF.Infrastructure.Color>(self);
            var result = receiver.Red;
            return result;
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
            return default;
        }
    }

    [UnmanagedCallersOnly(EntryPoint = "QP_Color_toUInt32_0")]
    public static int QP_Color_toUInt32_0(long self)
    {
        try
        {
            var receiver = Interop.Handles.Get<global::QuestPDF.Infrastructure.Color>(self);
            var result = (global::System.UInt32)receiver;
            return unchecked((int)result);
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
            return default;
        }
    }

    [UnmanagedCallersOnly(EntryPoint = "QP_Color_withAlpha_0")]
    public static long QP_Color_withAlpha_0(long self, byte alpha)
    {
        try
        {
            var receiver = Interop.Handles.Get<global::QuestPDF.Infrastructure.Color>(self);
            var result = receiver.WithAlpha(alpha);
            return Interop.Handles.Register(result);
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
            return default;
        }
    }

    [UnmanagedCallersOnly(EntryPoint = "QP_Color_withAlpha_1")]
    public static long QP_Color_withAlpha_1(long self, float alpha)
    {
        try
        {
            var receiver = Interop.Handles.Get<global::QuestPDF.Infrastructure.Color>(self);
            var result = receiver.WithAlpha(alpha);
            return Interop.Handles.Register(result);
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
            return default;
        }
    }
}
