// <auto-generated>
// Generated by QuestPDF.Interop.Generator from QuestPDF 2026.7.1.0.
// Do not edit — this file is wiped and recreated on every generator run.
// </auto-generated>
#nullable enable
#pragma warning disable CS0612, CS0618, CS0619 // deliberate calls to [Obsolete] members: the bridge mirrors the full public surface
#pragma warning disable CS8604, CS8600, CS8625 // the client side enforces non-null contracts; nulls crossing anyway surface as .NET exceptions on the error channel

using System;
using System.Runtime.InteropServices;

namespace QuestPDF.Native;

public static unsafe class Exports_IDocument
{
    [UnmanagedCallersOnly(EntryPoint = "QP_IDocument_compose_0")]
    public static void QP_IDocument_compose_0(long self, long container)
    {
        try
        {
            var receiver = Interop.Handles.Get<global::QuestPDF.Infrastructure.IDocument>(self);
            receiver.Compose(Interop.Handles.Get<global::QuestPDF.Infrastructure.IDocumentContainer>(container));
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
        }
    }

    [UnmanagedCallersOnly(EntryPoint = "QP_IDocument_generateImages_0")]
    public static void QP_IDocument_generateImages_0(long self, nint imagePathSource, long settings)
    {
        try
        {
            var receiver = Interop.Handles.Get<global::QuestPDF.Infrastructure.IDocument>(self);
            var imagePathSourceAdapter = imagePathSource == 0 ? null : (global::QuestPDF.Fluent.GenerateExtensions.GenerateDocumentImagePath)(x0 =>
            {
                var cb = imagePathSource;
                var fn = (delegate* unmanaged[Cdecl]<int, long>)cb;
                var r = fn(x0);
                return Interop.Handles.TakeString(r)!;
            });
            global::QuestPDF.Fluent.GenerateExtensions.GenerateImages(receiver, imagePathSourceAdapter, (settings == 0 ? null : Interop.Handles.Get<global::QuestPDF.Infrastructure.ImageGenerationSettings>(settings)));
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
        }
    }

    [UnmanagedCallersOnly(EntryPoint = "QP_IDocument_generatePdfAndShow_0")]
    public static void QP_IDocument_generatePdfAndShow_0(long self)
    {
        try
        {
            var receiver = Interop.Handles.Get<global::QuestPDF.Infrastructure.IDocument>(self);
            global::QuestPDF.Fluent.GenerateExtensions.GeneratePdfAndShow(receiver);
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
        }
    }

    [UnmanagedCallersOnly(EntryPoint = "QP_IDocument_generatePdf_0")]
    public static void QP_IDocument_generatePdf_0(long self, byte** outData, int* outLength)
    {
        try
        {
            var receiver = Interop.Handles.Get<global::QuestPDF.Infrastructure.IDocument>(self);
            var result = global::QuestPDF.Fluent.GenerateExtensions.GeneratePdf(receiver);
            Interop.WriteBuffer(result, outData, outLength);
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
            *outData = null;
            *outLength = 0;
        }
    }

    [UnmanagedCallersOnly(EntryPoint = "QP_IDocument_generatePdf_2")]
    public static void QP_IDocument_generatePdf_2(long self, byte* filePath)
    {
        try
        {
            var receiver = Interop.Handles.Get<global::QuestPDF.Infrastructure.IDocument>(self);
            global::QuestPDF.Fluent.GenerateExtensions.GeneratePdf(receiver, Interop.ToStringUtf8(filePath));
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
        }
    }

    [UnmanagedCallersOnly(EntryPoint = "QP_IDocument_generateXpsAndShow_0")]
    public static void QP_IDocument_generateXpsAndShow_0(long self)
    {
        try
        {
            var receiver = Interop.Handles.Get<global::QuestPDF.Infrastructure.IDocument>(self);
            global::QuestPDF.Fluent.GenerateExtensions.GenerateXpsAndShow(receiver);
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
        }
    }

    [UnmanagedCallersOnly(EntryPoint = "QP_IDocument_generateXps_0")]
    public static void QP_IDocument_generateXps_0(long self, byte** outData, int* outLength)
    {
        try
        {
            var receiver = Interop.Handles.Get<global::QuestPDF.Infrastructure.IDocument>(self);
            var result = global::QuestPDF.Fluent.GenerateExtensions.GenerateXps(receiver);
            Interop.WriteBuffer(result, outData, outLength);
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
            *outData = null;
            *outLength = 0;
        }
    }

    [UnmanagedCallersOnly(EntryPoint = "QP_IDocument_generateXps_2")]
    public static void QP_IDocument_generateXps_2(long self, byte* filePath)
    {
        try
        {
            var receiver = Interop.Handles.Get<global::QuestPDF.Infrastructure.IDocument>(self);
            global::QuestPDF.Fluent.GenerateExtensions.GenerateXps(receiver, Interop.ToStringUtf8(filePath));
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
        }
    }

    [UnmanagedCallersOnly(EntryPoint = "QP_IDocument_getMetadata_0")]
    public static long QP_IDocument_getMetadata_0(long self)
    {
        try
        {
            var receiver = Interop.Handles.Get<global::QuestPDF.Infrastructure.IDocument>(self);
            var result = receiver.GetMetadata();
            return Interop.Handles.Register(result);
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
            return default;
        }
    }

    [UnmanagedCallersOnly(EntryPoint = "QP_IDocument_getSettings_0")]
    public static long QP_IDocument_getSettings_0(long self)
    {
        try
        {
            var receiver = Interop.Handles.Get<global::QuestPDF.Infrastructure.IDocument>(self);
            var result = receiver.GetSettings();
            return Interop.Handles.Register(result);
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
            return default;
        }
    }

    [UnmanagedCallersOnly(EntryPoint = "QP_IDocument_showInCompanion_0")]
    public static void QP_IDocument_showInCompanion_0(long self, int port)
    {
        try
        {
            var receiver = Interop.Handles.Get<global::QuestPDF.Infrastructure.IDocument>(self);
            global::QuestPDF.Companion.CompanionExtensions.ShowInCompanion(receiver, port);
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
        }
    }

    [UnmanagedCallersOnly(EntryPoint = "QP_IDocument_showInPreviewer_0")]
    public static void QP_IDocument_showInPreviewer_0(long self, int port)
    {
        try
        {
            var receiver = Interop.Handles.Get<global::QuestPDF.Infrastructure.IDocument>(self);
            global::QuestPDF.Previewer.PreviewerExtensions.ShowInPreviewer(receiver, port);
        }
        catch (Exception exception)
        {
            Interop.ReportError(exception);
        }
    }
}
