using System.Text;
using QuestPDF.Interop.Generator.Core;
using QuestPDF.Interop.Generator.Core.Bridge;

namespace QuestPDF.Interop.Generator.Backends.TypeScript.Emission;

/// <summary>
/// Emits the generated half of the TypeScript interop layer: koffi function
/// declarations for every native export, and one koffi callback prototype per
/// deduplicated callback shape. The handwritten half (the Native runtime that
/// loads the library, owns the error channel and retains callbacks) lives in
/// the manual source set and consumes <c>declareNativeFunctions</c>.
/// </summary>
public static class InteropTypeScriptEmitter
{
    public static void Emit(TsModel model, IDictionary<string, string> files)
    {
        files["interop/native-functions.ts"] = EmitNativeFunctions(model);
        if (model.CallbackShapes.Count > 0)
            files["interop/callback-shapes.ts"] = EmitCallbackShapes(model);
    }

    private static string Header(TsModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"// Generated by {GeneratorInfo.ToolName} from QuestPDF {model.SourceAssemblyVersion}.");
        sb.AppendLine("// Do not edit — this file is wiped and recreated on every generator run.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        return sb.ToString();
    }

    private static string EmitNativeFunctions(TsModel model)
    {
        var sb = new StringBuilder(Header(model));
        sb.AppendLine("import koffi from 'koffi';");

        var referencedShapes = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var export in model.NativeExports)
        {
            foreach (var parameter in export.Parameters)
                foreach (var abi in BridgeAbi.ParameterLayout(parameter.Name, parameter.Marshal))
                    if (abi.Shape is not null)
                        referencedShapes.Add(abi.Shape.Name);
        }
        foreach (var proxy in model.Proxies)
            referencedShapes.Add(proxy.Method.Shape.Name);

        if (referencedShapes.Count > 0)
            sb.AppendLine($"import {{ {string.Join(", ", referencedShapes)} }} from './callback-shapes';");

        sb.AppendLine();
        sb.AppendLine("/**");
        sb.AppendLine(" * koffi declarations for every UnmanagedCallersOnly export of the");
        sb.AppendLine(" * QuestPDF.Native shared library. Property names equal entry-point names.");
        sb.AppendLine(" * The manual runtime calls this once with the loaded library.");
        sb.AppendLine(" */");
        sb.AppendLine("export function declareNativeFunctions(lib: koffi.IKoffiLib) {");
        sb.AppendLine("    return {");

        foreach (var export in model.NativeExports)
        {
            var parameters = new List<string>();
            if (export.Receiver is not null)
                parameters.Add("'int64_t'");

            foreach (var parameter in export.Parameters)
                foreach (var abi in BridgeAbi.ParameterLayout(parameter.Name, parameter.Marshal))
                    parameters.Add(KoffiType(abi));

            var returnSlot = BridgeAbi.ReturnLayout(export.Return);
            if (returnSlot == AbiSlot.BufferOut)
            {
                parameters.Add("koffi.out(koffi.pointer(koffi.pointer('uint8_t')))");
                parameters.Add("koffi.out(koffi.pointer('int32_t'))");
            }
            else if (BridgeAbi.IsFlaggedReturn(export.Return))
            {
                parameters.Add("koffi.out(koffi.pointer('int8_t'))");
            }

            var returnType = returnSlot switch
            {
                AbiSlot.Void or AbiSlot.BufferOut => "'void'",
                // Not char*: koffi would auto-convert the return to a JS string,
                // losing the pointer the free-export needs.
                AbiSlot.TextReturn => "koffi.pointer('uint8_t')",
                _ => "'" + KoffiScalarType(returnSlot) + "'",
            };

            sb.AppendLine($"        {export.EntryPoint}: lib.func('{export.EntryPoint}', {returnType}, [{string.Join(", ", parameters)}]),");
        }

        foreach (var proxy in model.Proxies)
            sb.AppendLine($"        {proxy.ProxyExportEntryPoint}: lib.func('{proxy.ProxyExportEntryPoint}', 'int64_t', [koffi.pointer({proxy.Method.Shape.Name})]),");

        sb.AppendLine("    } as const;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("export type NativeFunctions = ReturnType<typeof declareNativeFunctions>;");
        return sb.ToString();
    }

    private static string EmitCallbackShapes(TsModel model)
    {
        var sb = new StringBuilder(Header(model));
        sb.AppendLine("import koffi from 'koffi';");
        sb.AppendLine();
        sb.AppendLine("// One koffi prototype per callback ABI shape. The manual runtime");
        sb.AppendLine("// registers JS functions against these prototypes (Native.retain) and");
        sb.AppendLine("// keeps the registrations alive while native code may still call them.");

        foreach (var shape in model.CallbackShapes)
        {
            var parameters = shape.ParameterSlots
                .Select((slot, i) => $"{CallbackSlotCType(slot)} p{i}");
            var returnType = shape.ReturnSlot == AbiSlot.Void ? "void" : KoffiScalarType(shape.ReturnSlot);

            sb.AppendLine();
            sb.AppendLine($"export const {shape.Name} = koffi.proto('{returnType} {shape.Name}({string.Join(", ", parameters)})');");
        }

        return sb.ToString();
    }

    private static string KoffiType(AbiParameter parameter) => parameter.Slot switch
    {
        AbiSlot.Text => "'str'",
        AbiSlot.Bytes => "koffi.pointer('uint8_t')",
        AbiSlot.FloatArray => "koffi.pointer('float')",
        AbiSlot.LongArray => "koffi.pointer('int64_t')",
        AbiSlot.TextArray => "koffi.pointer('str')",
        AbiSlot.Callback => $"koffi.pointer({parameter.Shape!.Name})",
        _ => "'" + KoffiScalarType(parameter.Slot) + "'",
    };

    private static string CallbackSlotCType(AbiSlot slot) => slot switch
    {
        AbiSlot.Text => "str",
        _ => KoffiScalarType(slot),
    };

    private static string KoffiScalarType(AbiSlot slot) => slot switch
    {
        AbiSlot.Byte => "int8_t",
        AbiSlot.Short => "int16_t",
        AbiSlot.Int => "int32_t",
        AbiSlot.Long => "int64_t",
        AbiSlot.Float => "float",
        AbiSlot.Double => "double",
        _ => throw new InvalidOperationException($"Slot {slot} is not a scalar"),
    };
}
