using System.Text;
using QuestPDF.Interop.Generator.Core;
using QuestPDF.Interop.Generator.Core.Bridge;

namespace QuestPDF.Interop.Generator.Backends.TypeScript.Emission;

/// <summary>
/// Stage 3: renders the classified TypeScript model as source files. Pure
/// rendering — every mapping decision was already made in Stage 2; TypeScript
/// projections of the neutral bridge marshals come from
/// <see cref="TsBridgeViews"/>. Output is deterministic: one file per top-level
/// declaration, stable ordering, stable imports. Function bodies marshal
/// arguments, call the native export through <c>Native.lib</c>, re-throw
/// recorded errors and wrap results; same-name overloads render as TypeScript
/// overload signatures dispatched on argument count and runtime type tests.
/// </summary>
public sealed class TypeScriptEmitter(TsBridgeViews views)
{
    public IReadOnlyDictionary<string, string> Emit(TsModel model)
    {
        var files = new SortedDictionary<string, string>(StringComparer.Ordinal);

        foreach (var declaration in model.Declarations)
        {
            var path = declaration.ModulePath + "/" + declaration.Name + ".ts";
            files[path] = EmitFile(declaration, model);
        }

        files["internal.ts"] = EmitInternalBarrel(model);
        files["index.ts"] = EmitBarrel(model);
        return files;
    }

    /// <summary>
    /// The internal barrel every generated file imports siblings through. It
    /// evaluates modules in inheritance order (base files before files whose
    /// classes extend them), so CommonJS import cycles never observe an
    /// uninitialized base class.
    /// </summary>
    private string EmitInternalBarrel(TsModel model)
    {
        var declarations = model.Declarations.OfType<TsTypeDeclaration>().ToList();
        var fileOf = declarations.ToDictionary(d => d.Name, d => d.ModulePath + "/" + d.Name, StringComparer.Ordinal);

        var depths = new Dictionary<string, int>(StringComparer.Ordinal);

        IEnumerable<string> EvalTimeBases(TsTypeDeclaration declaration)
        {
            if (declaration.SuperClass is { ModulePath.Length: > 0 } superClass)
                yield return superClass.DeclaredInFile ?? superClass.Name.Split('.')[0];
            if (declaration.ImplBaseClass is { ModulePath.Length: > 0 } implBase)
                yield return implBase.DeclaredInFile ?? implBase.Name.Split('.')[0];
            foreach (var nested in declaration.NestedTypes)
                foreach (var name in EvalTimeBases(nested))
                    yield return name;
        }

        int DepthOf(TsTypeDeclaration declaration)
        {
            if (depths.TryGetValue(declaration.Name, out var known))
                return known;

            depths[declaration.Name] = 0; // cycle guard; C# inheritance is a DAG
            var depth = 0;
            foreach (var baseName in EvalTimeBases(declaration))
            {
                if (baseName == declaration.Name)
                    continue; // nested types extending siblings resolve within the file
                var baseDeclaration = declarations.FirstOrDefault(d => d.Name == baseName);
                if (baseDeclaration is not null)
                    depth = Math.Max(depth, DepthOf(baseDeclaration) + 1);
            }

            depths[declaration.Name] = depth;
            return depth;
        }

        var ordered = model.Declarations
            .OrderBy(d => d is TsTypeDeclaration typed ? DepthOf(typed) : 0)
            .ThenBy(d => d.ModulePath, StringComparer.Ordinal)
            .ThenBy(d => d.Name, StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder(Header(model.SourceAssemblyVersion));
        sb.AppendLine("// Module evaluation order is significant: base classes before subclasses.");
        foreach (var declaration in ordered)
            sb.AppendLine($"export * from './{fileOf.GetValueOrDefault(declaration.Name, declaration.ModulePath + "/" + declaration.Name)}';");
        return sb.ToString();
    }

    private static string Header(string version)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"// Generated by {GeneratorInfo.ToolName} from QuestPDF {version}.");
        sb.AppendLine("// Do not edit — this file is wiped and recreated on every generator run.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        return sb.ToString();
    }

    private string EmitBarrel(TsModel model)
    {
        var sb = new StringBuilder(Header(model.SourceAssemblyVersion));
        sb.AppendLine("export * from './internal';");
        return sb.ToString();
    }

    private string EmitFile(TsDeclaration declaration, TsModel model)
    {
        var localNames = new HashSet<string>(StringComparer.Ordinal) { declaration.Name };
        if (declaration is TsTypeDeclaration { ImplClassName: not null } withImpl)
            localNames.Add(withImpl.ImplClassName!);

        var resolver = new TsImportResolver(declaration.ModulePath, localNames);
        var body = new CodeWriter();

        switch (declaration)
        {
            case TsTypeAlias alias:
                EmitTypeAlias(body, alias, resolver);
                break;

            case TsTypeDeclaration type:
                EmitTopLevelType(body, type, resolver);
                break;
        }

        var sb = new StringBuilder(Header(model.SourceAssemblyVersion));

        var imports = resolver.ImportStatements();
        if (imports.Count > 0)
        {
            foreach (var import in imports)
                sb.AppendLine(import);
            sb.AppendLine();
        }

        sb.Append(body);
        return sb.ToString();
    }

    // ---- Declarations ----

    private static void EmitTypeAlias(CodeWriter writer, TsTypeAlias alias, TsImportResolver resolver)
    {
        EmitDoc(writer, alias.Doc, alias.DeprecationMessage);
        writer.Line($"export type {alias.Name} = {RenderType(alias.AliasedType, resolver)};");
    }

    private void EmitTopLevelType(CodeWriter writer, TsTypeDeclaration type, TsImportResolver resolver)
    {
        switch (type.Kind)
        {
            case TsTypeKind.Enum:
                EmitEnum(writer, type, exported: true);
                return;

            case TsTypeKind.Interface:
                EmitInterface(writer, type, resolver);
                if (type.ImplClassName is not null)
                    EmitImplClass(writer, type, resolver);
                break;

            case TsTypeKind.Class:
            case TsTypeKind.StaticHolder:
                EmitClass(writer, type, resolver, exported: true);
                break;
        }

        // Nested static holders render as lazy static object literals inside the
        // class; everything else needs the merged namespace (usable as types).
        var namespaceNested = type.NestedTypes.Where(n => n.Kind != TsTypeKind.StaticHolder).ToList();
        if (namespaceNested.Count > 0)
        {
            writer.Line();
            writer.Line($"// eslint-disable-next-line @typescript-eslint/no-namespace");
            writer.Line($"export namespace {type.Name} {{");
            writer.Indent();

            var ordered = OrderByBaseDependency(namespaceNested);
            for (var i = 0; i < ordered.Count; i++)
            {
                if (i > 0)
                    writer.Line();
                EmitNamespaceMember(writer, ordered[i], resolver);
            }

            writer.Outdent();
            writer.Line("}");
        }
    }

    /// <summary>Sibling classes extending sibling classes must be declared after their base.</summary>
    private static List<TsTypeDeclaration> OrderByBaseDependency(IReadOnlyList<TsTypeDeclaration> nested)
    {
        var byName = nested.ToDictionary(n => n.Name, StringComparer.Ordinal);
        var ordered = new List<TsTypeDeclaration>();
        var visited = new HashSet<string>(StringComparer.Ordinal);

        void Visit(TsTypeDeclaration declaration)
        {
            if (!visited.Add(declaration.Name))
                return;

            var baseSimple = declaration.SuperClass?.Name.Split('.')[^1];
            if (baseSimple is not null && byName.TryGetValue(baseSimple, out var sibling))
                Visit(sibling);

            ordered.Add(declaration);
        }

        foreach (var declaration in nested)
            Visit(declaration);

        return ordered;
    }

    private void EmitNamespaceMember(CodeWriter writer, TsTypeDeclaration type, TsImportResolver resolver)
    {
        switch (type.Kind)
        {
            case TsTypeKind.Enum:
                EmitEnum(writer, type, exported: true);
                return;

            case TsTypeKind.Class:
                EmitClass(writer, type, resolver, exported: true);
                return;

            case TsTypeKind.StaticHolder:
                EmitDoc(writer, type.Doc, type.DeprecationMessage);
                writer.Line($"export const {type.Name} = {{");
                writer.Indent();
                EmitObjectLiteralMembers(writer, type, resolver);
                writer.Outdent();
                writer.Line("};");
                return;

            case TsTypeKind.Interface:
                EmitInterface(writer, type, resolver);
                return;
        }
    }

    private static void EmitEnum(CodeWriter writer, TsTypeDeclaration type, bool exported)
    {
        var prefix = exported ? "export " : "";
        EmitDoc(writer, type.Doc, type.DeprecationMessage);
        writer.Line($"{prefix}const {type.Name} = {{");
        writer.Indent();

        foreach (var entry in type.EnumEntries)
        {
            EmitDoc(writer, entry.Doc, entry.DeprecationMessage);
            writer.Line($"{entry.Name}: {entry.Value},");
        }

        writer.Outdent();
        writer.Line("} as const;");
        writer.Line();
        writer.Line($"{prefix}type {type.Name} = (typeof {type.Name})[keyof typeof {type.Name}];");
    }

    private void EmitInterface(CodeWriter writer, TsTypeDeclaration type, TsImportResolver resolver)
    {
        EmitDoc(writer, type.Doc, type.DeprecationMessage);

        var extends = type.SuperInterfaces.Count > 0
            ? " extends " + string.Join(", ", type.SuperInterfaces.Select(resolver.Generated))
            : "";

        writer.Line($"export interface {type.Name}{extends} {{");
        writer.Indent();
        var needsSeparator = false;

        if (type.DeclaresNativeHandle)
        {
            writer.Line("/** Handle of the native object backing this instance. */");
            writer.Line("readonly nativeHandle: number;");
            needsSeparator = true;
        }

        foreach (var property in type.Properties)
        {
            if (needsSeparator)
                writer.Line();
            EmitDoc(writer, property.Doc, property.DeprecationMessage);
            writer.Line($"{(property.IsMutable ? "" : "readonly ")}{property.Name}: {RenderType(property.Type, resolver)};");
            needsSeparator = true;
        }

        foreach (var group in type.FunctionGroups)
        {
            foreach (var overload in group.Overloads)
            {
                if (needsSeparator)
                    writer.Line();
                EmitDoc(writer, overload.Doc, overload.DeprecationMessage);
                writer.Line(SignatureLine(overload, resolver, defaultsAsOptional: true) + ";");
                needsSeparator = true;
            }
        }

        writer.Outdent();
        writer.Line("}");
    }

    private void EmitImplClass(CodeWriter writer, TsTypeDeclaration type, TsImportResolver resolver)
    {
        var baseClass = type.ImplBaseClass is not null
            ? resolver.Generated(type.ImplBaseClass)
            : resolver.Manual("native-object", "NativeObject");

        writer.Line();
        writer.Line($"/** Wraps a native {type.Name} handle. @internal */");
        writer.Line($"export class {type.ImplClassName} extends {baseClass} implements {type.Name} {{");
        writer.Indent();

        var needsSeparator = false;
        foreach (var property in type.Properties)
        {
            if (needsSeparator)
                writer.Line();
            EmitAccessorProperty(writer, property, resolver, isStatic: false);
            needsSeparator = true;
        }

        foreach (var group in type.FunctionGroups)
        {
            if (needsSeparator)
                writer.Line();
            EmitFunctionGroup(writer, group, resolver, isStatic: false, docs: false);
            needsSeparator = true;
        }

        writer.Outdent();
        writer.Line("}");
    }

    private void EmitClass(CodeWriter writer, TsTypeDeclaration type, TsImportResolver resolver, bool exported)
    {
        EmitDoc(writer, type.Doc, type.DeprecationMessage);

        var header = new StringBuilder(exported ? "export " : "");
        if (type.IsAbstract)
            header.Append("abstract ");
        header.Append("class ").Append(type.Name);

        if (type.IsException)
        {
            header.Append(" extends Error");
        }
        else if (type.SuperClass is not null)
        {
            header.Append(" extends ").Append(resolver.Generated(type.SuperClass));
        }
        else if (type.IsHandleBacked)
        {
            header.Append(" extends ").Append(resolver.Manual("native-object", "NativeObject"));
        }

        if (type.SuperInterfaces.Count > 0)
            header.Append(" implements ").Append(string.Join(", ", type.SuperInterfaces.Select(resolver.Generated)));

        writer.Line(header + " {");
        writer.Indent();
        var needsSeparator = false;

        if (type.Kind == TsTypeKind.StaticHolder)
        {
            writer.Line("private constructor() {}");
            needsSeparator = true;
        }

        if (type.IsException)
        {
            writer.Line("constructor(message?: string) {");
            writer.Indent();
            writer.Line("super(message);");
            writer.Line($"this.name = \"{type.Name}\";");
            writer.Outdent();
            writer.Line("}");
            needsSeparator = true;
        }

        if (type.BridgedConstructor is { } ctor)
        {
            if (needsSeparator)
                writer.Line();
            EmitBridgedConstructor(writer, ctor, resolver);
            needsSeparator = true;
        }

        var isHolder = type.Kind == TsTypeKind.StaticHolder;

        foreach (var property in type.Properties)
        {
            if (needsSeparator)
                writer.Line();
            EmitAccessorProperty(writer, property, resolver, isStatic: isHolder);
            needsSeparator = true;
        }

        foreach (var group in type.FunctionGroups)
        {
            if (needsSeparator)
                writer.Line();
            EmitFunctionGroup(writer, group, resolver, isStatic: isHolder, docs: true);
            needsSeparator = true;
        }

        foreach (var property in type.StaticProperties)
        {
            if (needsSeparator)
                writer.Line();
            EmitAccessorProperty(writer, property, resolver, isStatic: true);
            needsSeparator = true;
        }

        foreach (var group in type.StaticFunctionGroups)
        {
            if (needsSeparator)
                writer.Line();
            EmitFunctionGroup(writer, group, resolver, isStatic: true, docs: true);
            needsSeparator = true;
        }

        // Nested static holders stay reachable as lazy object literals.
        foreach (var nested in type.NestedTypes.Where(n => n.Kind == TsTypeKind.StaticHolder))
        {
            if (needsSeparator)
                writer.Line();
            EmitDoc(writer, nested.Doc, nested.DeprecationMessage);
            writer.Line($"static readonly {nested.Name} = {{");
            writer.Indent();
            EmitObjectLiteralMembers(writer, nested, resolver);
            writer.Outdent();
            writer.Line("};");
            needsSeparator = true;
        }

        writer.Outdent();
        writer.Line("}");
    }

    /// <summary>Members of a nested static holder rendered as object-literal entries (lazy getters).</summary>
    private void EmitObjectLiteralMembers(CodeWriter writer, TsTypeDeclaration type, TsImportResolver resolver)
    {
        var needsSeparator = false;

        foreach (var property in type.Properties.Concat(type.StaticProperties))
        {
            if (needsSeparator)
                writer.Line();
            EmitDoc(writer, property.Doc, property.DeprecationMessage);

            if (property.Initializer is not null)
            {
                writer.Line($"{property.Name}: {RenderExpr(property.Initializer, resolver)},");
            }
            else if (property.Getter is not null)
            {
                EmitAccessorBody(writer, $"get {property.Name}(): {RenderType(property.Type, resolver)}", property.Getter, resolver, trailingComma: true);
                if (property.Setter is not null)
                    EmitSetterBody(writer, $"set {property.Name}(value: {RenderType(property.Type, resolver)})", property.Setter, property.Type, resolver, trailingComma: true);
            }

            needsSeparator = true;
        }

        foreach (var group in type.FunctionGroups.Concat(type.StaticFunctionGroups))
        {
            if (group.Overloads.Count > 1)
                throw new InvalidOperationException(
                    $"Nested static holder {type.Name} has overloaded member '{group.Name}'; object literals cannot carry overload signatures.");

            var function = group.Overloads[0];
            if (needsSeparator)
                writer.Line();
            EmitDoc(writer, function.Doc, function.DeprecationMessage);
            EmitFunctionWithBody(writer, function, resolver, prefix: "", suffixComma: true);
            needsSeparator = true;
        }

        foreach (var nested in type.NestedTypes)
        {
            if (nested.Kind != TsTypeKind.StaticHolder)
                throw new InvalidOperationException(
                    $"Nested static holder {type.Name} contains a non-holder nested type {nested.Name}; only holder nesting is supported inside object literals.");

            if (needsSeparator)
                writer.Line();
            EmitDoc(writer, nested.Doc, nested.DeprecationMessage);
            writer.Line($"{nested.Name}: {{");
            writer.Indent();
            EmitObjectLiteralMembers(writer, nested, resolver);
            writer.Outdent();
            writer.Line("},");
            needsSeparator = true;
        }
    }

    // ---- Constructors ----

    private void EmitBridgedConstructor(CodeWriter writer, TsConstructor ctor, TsImportResolver resolver)
    {
        var marker = resolver.Manual("native-object", "NATIVE_HANDLE");

        EmitDoc(writer, ctor.Doc, ctor.DeprecationMessage);
        writer.Line($"constructor({string.Join(", ", ctor.Parameters.Select(p => RenderParameter(p, resolver, defaultsAsOptional: true)))});");
        writer.Line("/** Wraps an existing native handle. @internal */");
        writer.Line($"constructor(handle: number, marker: typeof {marker});");
        writer.Line("constructor(...args: any[]) {");
        writer.Indent();

        // Base classes may declare the same two-overload constructor, so super
        // calls always take the handle-marker path.
        writer.Line($"if (args[1] === {marker}) {{");
        writer.Indent();
        writer.Line($"super(args[0] as number, {marker});");
        writer.Line("return;");
        writer.Outdent();
        writer.Line("}");

        BindDispatchArguments(writer, ctor.Parameters, resolver);
        var (preludes, arguments) = MarshalArguments(ctor.Export, resolver);
        foreach (var prelude in preludes)
            writer.Line(prelude);

        var native = resolver.Manual("native-bridge", "Native");
        writer.Line($"super({native}.checked({native}.lib.{ctor.Export.EntryPoint}({string.Join(", ", arguments)})), {marker});");
        writer.Outdent();
        writer.Line("}");
    }

    // ---- Properties ----

    private void EmitAccessorProperty(CodeWriter writer, TsProperty property, TsImportResolver resolver, bool isStatic)
    {
        EmitDoc(writer, property.Doc, property.DeprecationMessage);
        var prefix = isStatic ? "static " : "";

        if (property.Initializer is not null)
        {
            writer.Line($"{prefix}readonly {property.Name} = {RenderExpr(property.Initializer, resolver)};");
            return;
        }

        if (property.Getter is null)
        {
            // Signature-only property (user-implemented interface member on a class).
            writer.Line($"{prefix}{(property.IsMutable ? "" : "readonly ")}{property.Name}!: {RenderType(property.Type, resolver)};");
            return;
        }

        EmitAccessorBody(writer, $"{prefix}get {property.Name}(): {RenderType(property.Type, resolver)}", property.Getter, resolver, trailingComma: false);

        if (property.Setter is { } setter)
            EmitSetterBody(writer, $"{prefix}set {property.Name}(value: {RenderType(property.Type, resolver)})", setter, property.Type, resolver, trailingComma: false);
    }

    private void EmitAccessorBody(CodeWriter writer, string signature, NativeExport getter, TsImportResolver resolver, bool trailingComma)
    {
        writer.Line(signature + " {");
        writer.Indent();
        EmitBridgeCall(writer, getter, resolver);
        writer.Outdent();
        writer.Line(trailingComma ? "}," : "}");
    }

    private void EmitSetterBody(CodeWriter writer, string signature, NativeExport setter, TsType propertyType, TsImportResolver resolver, bool trailingComma)
    {
        writer.Line(signature + " {");
        writer.Indent();
        var native = resolver.Manual("native-bridge", "Native");
        var (preludes, arguments) = MarshalArguments(setter, resolver);
        foreach (var prelude in preludes)
            writer.Line(prelude);
        writer.Line($"{native}.lib.{setter.EntryPoint}({string.Join(", ", ReceiverPrefixed(setter, arguments))});");
        writer.Line($"{native}.check();");
        writer.Outdent();
        writer.Line(trailingComma ? "}," : "}");
    }

    // ---- Functions ----

    private void EmitFunctionGroup(CodeWriter writer, TsFunctionGroup group, TsImportResolver resolver, bool isStatic, bool docs)
    {
        if (group.Overloads.Count == 1)
        {
            var function = group.Overloads[0];
            if (docs || function.Body is TsBody.None)
                EmitDoc(writer, function.Doc, function.DeprecationMessage);
            EmitFunctionWithBody(writer, function, resolver, prefix: isStatic ? "static " : "", suffixComma: false);
            return;
        }

        var prefix = isStatic ? "static " : "";

        // Overload signatures carry the docs; defaults surface as optionals.
        foreach (var overload in group.Overloads)
        {
            if (docs)
                EmitDoc(writer, overload.Doc, overload.DeprecationMessage);
            writer.Line(prefix + SignatureLine(overload, resolver, defaultsAsOptional: true) + ";");
        }

        writer.Line($"{prefix}{EscapeMember(group.Name)}(...args: any[]): any {{");
        writer.Indent();

        foreach (var overload in group.Overloads)
        {
            writer.Line($"if ({DispatchPredicate(overload, resolver)}) {{");
            writer.Indent();
            BindDispatchArguments(writer, overload.Parameters, resolver);
            EmitFunctionBody(writer, overload, resolver);
            if (((TsBody.Bridge)overload.Body).Export.Return is BridgeMarshal.Nothing)
                writer.Line("return;");
            writer.Outdent();
            writer.Line("}");
        }

        writer.Line($"throw new TypeError(\"No overload of '{group.Name}' matches the provided arguments.\");");
        writer.Outdent();
        writer.Line("}");
    }

    private void EmitFunctionWithBody(CodeWriter writer, TsFunction function, TsImportResolver resolver, string prefix, bool suffixComma)
    {
        if (function.Body is TsBody.None)
        {
            // Only rendered on interfaces; classes never carry bodiless members.
            writer.Line(prefix + SignatureLine(function, resolver, defaultsAsOptional: true) + ";");
            return;
        }

        writer.Line(prefix + SignatureLine(function, resolver, defaultsAsOptional: false) + " {");
        writer.Indent();
        EmitFunctionBody(writer, function, resolver);
        writer.Outdent();
        writer.Line(suffixComma ? "}," : "}");
    }

    private void EmitFunctionBody(CodeWriter writer, TsFunction function, TsImportResolver resolver)
    {
        var export = ((TsBody.Bridge)function.Body).Export;
        EmitBridgeCall(writer, export, resolver);
    }

    /// <summary>Marshals arguments, calls the export, checks errors and returns the wrapped result.</summary>
    private void EmitBridgeCall(CodeWriter writer, NativeExport export, TsImportResolver resolver)
    {
        var native = resolver.Manual("native-bridge", "Native");
        var (preludes, arguments) = MarshalArguments(export, resolver);
        foreach (var prelude in preludes)
            writer.Line(prelude);

        var callArguments = ReceiverPrefixed(export, arguments).ToList();

        switch (export.Return)
        {
            case BridgeMarshal.Nothing:
                writer.Line($"{native}.lib.{export.EntryPoint}({string.Join(", ", callArguments)});");
                writer.Line($"{native}.check();");
                return;

            case BridgeMarshal.Blob:
                writer.Line("const outData: unknown[] = [null];");
                writer.Line("const outLength: number[] = [0];");
                writer.Line($"{native}.lib.{export.EntryPoint}({string.Join(", ", callArguments.Concat(["outData", "outLength"]))});");
                writer.Line($"{native}.check();");
                writer.Line($"return {native}.takeBuffer(outData[0], outLength[0]);");
                return;

            case var flagged when BridgeAbi.IsFlaggedReturn(flagged):
            {
                var convert = export.Return switch
                {
                    BridgeMarshal.NullableScalar scalar => ScalarIn("rawResult", scalar.Kind),
                    BridgeMarshal.EnumValue enumValue => $"(rawResult as {resolver.Generated(views.EnumType(enumValue))})",
                    _ => throw new InvalidOperationException($"Marshal {export.Return.GetType().Name} is not a flagged return"),
                };

                writer.Line("const outHasValue: number[] = [0];");
                writer.Line($"const rawResult = {native}.lib.{export.EntryPoint}({string.Join(", ", callArguments.Concat(["outHasValue"]))});");
                writer.Line($"{native}.check();");
                writer.Line($"return outHasValue[0] !== 0 ? {convert} : null;");
                return;
            }

            case BridgeMarshal.Handle { Nullable: true } handle:
            {
                var wrapName = resolver.Generated(views.WrapType(handle));
                var marker = resolver.Manual("native-object", "NATIVE_HANDLE");
                writer.Line($"const resultHandle = {native}.checked({native}.lib.{export.EntryPoint}({string.Join(", ", callArguments)}));");
                writer.Line($"return resultHandle === 0 ? null : new {wrapName}(resultHandle, {marker});");
                return;
            }

            case BridgeMarshal.DateTimeText { Nullable: true }:
                writer.Line($"const resultText = {native}.takeString({native}.checked({native}.lib.{export.EntryPoint}({string.Join(", ", callArguments)})));");
                writer.Line("return resultText == null ? null : new Date(resultText);");
                return;

            default:
            {
                var raw = $"{native}.checked({native}.lib.{export.EntryPoint}({string.Join(", ", callArguments)}))";
                writer.Line($"return {WrapReturn(export.Return, raw, resolver)};");
                return;
            }
        }
    }

    private static IEnumerable<string> ReceiverPrefixed(NativeExport export, IReadOnlyList<string> arguments) =>
        export.Receiver is null ? arguments : new[] { "this.nativeHandle" }.Concat(arguments);

    // ---- Overload dispatch ----

    private string DispatchPredicate(TsFunction function, TsImportResolver resolver)
    {
        var terms = new List<string>();

        var minArity = 0;
        foreach (var parameter in function.Parameters)
        {
            if (parameter.IsRest || parameter.DefaultValue is not null)
                break;
            minArity++;
        }

        var hasRest = function.Parameters.Any(p => p.IsRest);
        if (!hasRest && minArity == function.Parameters.Count)
        {
            terms.Add($"args.length === {minArity}");
        }
        else
        {
            if (minArity > 0)
                terms.Add($"args.length >= {minArity}");
            if (!hasRest)
                terms.Add($"args.length <= {function.Parameters.Count}");
        }

        for (var i = 0; i < function.Parameters.Count; i++)
        {
            var parameter = function.Parameters[i];
            var kind = i < function.RuntimeKinds.Count ? function.RuntimeKinds[i] : RuntimeKind.Unknown;
            var test = RuntimeTest($"args[{i}]", kind, parameter, function, i, resolver);
            if (test is null)
                continue;

            if (parameter.Type.IsNullable || parameter.DefaultValue is not null)
                test = $"(args[{i}] === null || args[{i}] === undefined || {test})";

            var optional = parameter.IsRest || i >= minArity;
            terms.Add(optional ? $"(args.length <= {i} || {test})" : test);
        }

        return terms.Count == 0 ? "true" : string.Join(" && ", terms);
    }

    private string? RuntimeTest(string value, RuntimeKind kind, TsParameter parameter, TsFunction function, int position, TsImportResolver resolver)
    {
        switch (kind)
        {
            case RuntimeKind.Number: return $"typeof {value} === \"number\"";
            case RuntimeKind.String: return $"typeof {value} === \"string\"";
            case RuntimeKind.Boolean: return $"typeof {value} === \"boolean\"";
            case RuntimeKind.Function: return $"typeof {value} === \"function\"";
            case RuntimeKind.Bytes: return $"{value} instanceof Uint8Array";
            case RuntimeKind.Date: return $"{value} instanceof Date";
            case RuntimeKind.ArrayLike: return $"Array.isArray({value})";
            case RuntimeKind.Iterable: return $"typeof ({value} as any)?.[Symbol.iterator] === \"function\"";
            case RuntimeKind.Handle: return $"{value} instanceof {resolver.Manual("native-object", "NativeObject")}";
            case RuntimeKind.UserImpl:
            {
                var method = UserImplMethodAt(function, position);
                return method is null
                    ? $"typeof {value} === \"object\" && {value} !== null"
                    : $"typeof ({value} as any)?.{method} === \"function\"";
            }
            default: return null;
        }
    }

    private string? UserImplMethodAt(TsFunction function, int position)
    {
        if (function.Body is not TsBody.Bridge bridge || position >= bridge.Export.Parameters.Count)
            return null;

        return bridge.Export.Parameters[position].Marshal is BridgeMarshal.UserImplValue user
            ? views.ProxyMethodName(user.Proxy)
            : null;
    }

    /// <summary>Rebinds dispatcher arguments to the overload's parameter names, applying defaults.</summary>
    private void BindDispatchArguments(CodeWriter writer, IReadOnlyList<TsParameter> parameters, TsImportResolver resolver)
    {
        for (var i = 0; i < parameters.Count; i++)
        {
            var parameter = parameters[i];

            if (parameter.IsRest)
            {
                writer.Line($"const {parameter.Name} = args.slice({i}) as {RenderAtomic(parameter.Type, resolver)}[];");
                continue;
            }

            var type = RenderType(parameter.Type, resolver);
            if (parameter.DefaultValue is not null)
            {
                writer.Line($"const {parameter.Name} = (args.length > {i} && args[{i}] !== undefined ? args[{i}] : {RenderExpr(parameter.DefaultValue, resolver)}) as {type};");
            }
            else
            {
                writer.Line($"const {parameter.Name} = args[{i}] as {type};");
            }
        }
    }

    // ---- Bridge argument marshaling ----

    private (IReadOnlyList<string> Preludes, IReadOnlyList<string> Arguments) MarshalArguments(NativeExport export, TsImportResolver resolver)
    {
        var preludes = new List<string>();
        var arguments = new List<string>();

        foreach (var parameter in export.Parameters)
            arguments.AddRange(ArgumentExpressions(parameter.Name, parameter.Marshal, resolver, preludes));

        return (preludes, arguments);
    }

    private IEnumerable<string> ArgumentExpressions(string name, BridgeMarshal marshal, TsImportResolver resolver, List<string> preludes)
    {
        switch (marshal)
        {
            case BridgeMarshal.Scalar s:
                yield return ScalarOut(name, s.Kind);
                break;

            case BridgeMarshal.NullableScalar n:
                yield return $"({name} != null ? 1 : 0)";
                yield return n.Kind == ScalarKind.Boolean ? $"({name} ? 1 : 0)" : $"({name} ?? 0)";
                break;

            case BridgeMarshal.EnumValue enumValue:
                if (enumValue.Nullable)
                {
                    yield return $"({name} != null ? 1 : 0)";
                    yield return $"({name} ?? 0)";
                }
                else
                {
                    yield return name;
                }
                break;

            case BridgeMarshal.Text:
                yield return name;
                break;

            case BridgeMarshal.DateTimeText d:
                yield return d.Nullable ? $"({name}?.toISOString() ?? null)" : $"{name}.toISOString()";
                break;

            case BridgeMarshal.Blob b:
                yield return name;
                yield return b.Nullable ? $"({name}?.length ?? 0)" : $"{name}.length";
                break;

            case BridgeMarshal.Handle h:
                yield return h.Nullable ? $"({name}?.nativeHandle ?? 0)" : $"{name}.nativeHandle";
                break;

            case BridgeMarshal.HandleSequence hs:
                if (hs.Container is SequenceContainer.Vararg or SequenceContainer.Array)
                {
                    yield return $"{name}.map((x) => x.nativeHandle)";
                    yield return $"{name}.length";
                }
                else
                {
                    preludes.Add($"const {name}Items = Array.from({name});");
                    yield return $"{name}Items.map((x) => x.nativeHandle)";
                    yield return $"{name}Items.length";
                }
                break;

            case BridgeMarshal.TextSequence ts:
                if (ts.Container is SequenceContainer.Vararg or SequenceContainer.Array)
                {
                    yield return name;
                    yield return $"{name}.length";
                }
                else
                {
                    preludes.Add($"const {name}Items = Array.from({name});");
                    yield return $"{name}Items";
                    yield return $"{name}Items.length";
                }
                break;

            case BridgeMarshal.ScalarArray sa:
                if (sa.Container is SequenceContainer.Vararg or SequenceContainer.Array)
                {
                    yield return name;
                    yield return $"{name}.length";
                }
                else
                {
                    preludes.Add($"const {name}Items = Array.from({name});");
                    yield return $"{name}Items";
                    yield return $"{name}Items.length";
                }
                break;

            case BridgeMarshal.CallbackValue callback:
                yield return CallbackExpression(name, callback, resolver);
                break;

            case BridgeMarshal.UserImplValue user:
                yield return ProxyExpression(name, user, resolver);
                break;

            default:
                throw new InvalidOperationException($"Marshal {marshal.GetType().Name} cannot appear as an argument");
        }
    }

    private string CallbackExpression(string name, BridgeMarshal.CallbackValue callback, TsImportResolver resolver)
    {
        if (!callback.Nullable)
            return CallbackAdapterExpression(name, callback.Adapter, resolver);

        return $"({name} == null ? null : {CallbackAdapterExpression(name, callback.Adapter, resolver)})";
    }

    private string ProxyExpression(string name, BridgeMarshal.UserImplValue user, TsImportResolver resolver)
    {
        var native = resolver.Manual("native-bridge", "Native");
        var adapter = UserMethodAdapterExpression(name, user.Proxy, resolver);
        var create = $"{native}.lib.{user.Proxy.ProxyExportEntryPoint}({adapter})";

        return user.Nullable ? $"({name} == null ? 0 : {create})" : create;
    }

    /// <summary>Adapter turning a TypeScript function value into a registered koffi callback of the planned shape.</summary>
    private string CallbackAdapterExpression(string functionReference, CallbackAdapter adapter, TsImportResolver resolver)
    {
        var (parameterList, unwrapped) = UnwrapCallbackParameters(adapter, resolver);
        var invocation = $"{functionReference}({string.Join(", ", unwrapped)})";
        return RetainedCallback(adapter, parameterList, invocation, resolver);
    }

    /// <summary>Adapter forwarding a user object's method (IComponent.compose) as a registered koffi callback.</summary>
    private string UserMethodAdapterExpression(string objectReference, ProxyPlan proxy, TsImportResolver resolver)
    {
        var adapter = proxy.Method;
        var (parameterList, unwrapped) = UnwrapCallbackParameters(adapter, resolver);
        var invocation = $"{objectReference}.{views.ProxyMethodName(proxy)}({string.Join(", ", unwrapped)})";
        return RetainedCallback(adapter, parameterList, invocation, resolver);
    }

    private string RetainedCallback(CallbackAdapter adapter, IReadOnlyList<string> parameterList, string invocation, TsImportResolver resolver)
    {
        var native = resolver.Manual("native-bridge", "Native");
        var shape = resolver.CallbackShape(adapter.Shape.Name);
        var body = GuardedResult(adapter.ReturnWrap, invocation, resolver);
        var lambdaParameters = string.Join(", ", parameterList);

        return $"{native}.retain({shape}, ({lambdaParameters}) => {body})";
    }

    private (IReadOnlyList<string> ParameterList, IReadOnlyList<string> Unwrapped) UnwrapCallbackParameters(
        CallbackAdapter adapter, TsImportResolver resolver)
    {
        var parameterList = new List<string>();
        var unwrapped = new List<string>();
        var slot = 0;

        void Declare(AbiSlot abiSlot)
        {
            parameterList.Add($"p{slot}: {CallbackSlotTsType(abiSlot)}");
            slot++;
        }

        foreach (var wrap in adapter.ParameterWraps)
        {
            switch (wrap)
            {
                case BridgeMarshal.Scalar s:
                    unwrapped.Add(ScalarIn($"p{slot}", s.Kind));
                    Declare(BridgeAbi.ScalarSlot(s.Kind));
                    break;

                case BridgeMarshal.NullableScalar n:
                {
                    var value = n.Kind == ScalarKind.Boolean ? $"p{slot + 1} !== 0" : $"p{slot + 1}";
                    unwrapped.Add($"(p{slot} !== 0 ? {value} : null)");
                    Declare(AbiSlot.Byte);
                    Declare(BridgeAbi.ScalarSlot(n.Kind));
                    break;
                }

                case BridgeMarshal.EnumValue { Nullable: true } e:
                    unwrapped.Add($"(p{slot} !== 0 ? (p{slot + 1} as {resolver.Generated(views.EnumType(e))}) : null)");
                    Declare(AbiSlot.Byte);
                    Declare(AbiSlot.Int);
                    break;

                case BridgeMarshal.EnumValue e:
                    unwrapped.Add($"(p{slot} as {resolver.Generated(views.EnumType(e))})");
                    Declare(AbiSlot.Int);
                    break;

                case BridgeMarshal.Text:
                    unwrapped.Add($"p{slot}");
                    Declare(AbiSlot.Text);
                    break;

                case BridgeMarshal.Handle h:
                {
                    var wrapName = resolver.Generated(views.WrapType(h));
                    var marker = resolver.Manual("native-object", "NATIVE_HANDLE");
                    unwrapped.Add(h.Nullable
                        ? $"(p{slot} === 0 ? null : new {wrapName}(p{slot}, {marker}))"
                        : $"new {wrapName}(p{slot}, {marker})");
                    Declare(AbiSlot.Long);
                    break;
                }

                default:
                    throw new InvalidOperationException($"Marshal {wrap.GetType().Name} cannot cross into a callback");
            }
        }

        return (parameterList, unwrapped);
    }

    private static string CallbackSlotTsType(AbiSlot slot) => slot switch
    {
        AbiSlot.Text => "string | null",
        _ => "number",
    };

    private string GuardedResult(BridgeMarshal returnWrap, string invocation, TsImportResolver resolver)
    {
        var native = resolver.Manual("native-bridge", "Native");
        return returnWrap switch
        {
            BridgeMarshal.Nothing =>
                $"{native}.guard(undefined, () => {{ {invocation}; }})",
            BridgeMarshal.Scalar s =>
                $"{native}.guard(0, () => {ScalarOut($"({invocation})", s.Kind)})",
            BridgeMarshal.EnumValue =>
                $"{native}.guard(0, () => ({invocation}))",
            BridgeMarshal.Handle h => h.Nullable
                ? $"{native}.guard(0, () => ({invocation})?.nativeHandle ?? 0)"
                : $"{native}.guard(0, () => ({invocation}).nativeHandle)",
            BridgeMarshal.Text t => t.Nullable
                ? $"{native}.guard(0, () => {{ const r = {invocation}; return r == null ? 0 : {native}.registerString(r); }})"
                : $"{native}.guard(0, () => {native}.registerString({invocation}))",
            BridgeMarshal.Blob b => b.Nullable
                ? $"{native}.guard(0, () => {{ const r = {invocation}; return r == null ? 0 : {native}.registerBuffer(r); }})"
                : $"{native}.guard(0, () => {native}.registerBuffer({invocation}))",
            _ => throw new InvalidOperationException($"Marshal {returnWrap.GetType().Name} cannot be returned from a callback"),
        };
    }

    /// <summary>Direct-return wrapping; nullable handles and dates take the statement path in <see cref="EmitBridgeCall"/>.</summary>
    private string WrapReturn(BridgeMarshal marshal, string raw, TsImportResolver resolver)
    {
        var native = resolver.Manual("native-bridge", "Native");
        switch (marshal)
        {
            case BridgeMarshal.Scalar s:
                return ScalarIn(raw, s.Kind);

            case BridgeMarshal.EnumValue e:
                return $"({raw} as {resolver.Generated(views.EnumType(e))})";

            case BridgeMarshal.Handle { Nullable: false } h:
            {
                var wrapName = resolver.Generated(views.WrapType(h));
                var marker = resolver.Manual("native-object", "NATIVE_HANDLE");
                return $"new {wrapName}({raw}, {marker})";
            }

            case BridgeMarshal.Text t:
                return $"{native}.takeString({raw})" + (t.Nullable ? "" : "!");

            case BridgeMarshal.DateTimeText { Nullable: false }:
                return $"new Date({native}.takeString({raw})!)";

            default:
                throw new InvalidOperationException($"Marshal {marshal.GetType().Name} cannot be a direct return");
        }
    }

    private static string ScalarOut(string expression, ScalarKind kind) => kind switch
    {
        ScalarKind.Boolean => $"({expression} ? 1 : 0)",
        _ => expression,
    };

    private static string ScalarIn(string expression, ScalarKind kind) => kind switch
    {
        ScalarKind.Boolean => $"({expression} !== 0)",
        _ => expression,
    };

    // ---- Signatures, types and expressions ----

    private static string SignatureLine(TsFunction function, TsImportResolver resolver, bool defaultsAsOptional)
    {
        var sb = new StringBuilder();
        sb.Append(EscapeMember(function.Name));

        if (function.TypeParameters.Count > 0)
        {
            sb.Append('<');
            sb.Append(string.Join(", ", function.TypeParameters.Select(p =>
                p.Constraints.Count == 0
                    ? p.Name
                    : $"{p.Name} extends {string.Join(" & ", p.Constraints.Select(c => RenderType(c, resolver)))}")));
            sb.Append('>');
        }

        sb.Append('(');
        sb.Append(string.Join(", ", function.Parameters.Select(p => RenderParameter(p, resolver, defaultsAsOptional))));
        sb.Append("): ").Append(RenderType(function.ReturnType, resolver));
        return sb.ToString();
    }

    private static string EscapeMember(string name) => name;

    private static string RenderParameter(TsParameter parameter, TsImportResolver resolver, bool defaultsAsOptional)
    {
        if (parameter.IsRest)
            return $"...{parameter.Name}: {RenderAtomic(parameter.Type, resolver)}[]";

        if (parameter.DefaultValue is null)
            return $"{parameter.Name}: {RenderType(parameter.Type, resolver)}";

        return defaultsAsOptional
            ? $"{parameter.Name}?: {RenderType(parameter.Type, resolver)}"
            : $"{parameter.Name}: {RenderType(parameter.Type, resolver)} = {RenderExpr(parameter.DefaultValue, resolver)}";
    }

    private static string RenderType(TsType type, TsImportResolver resolver)
    {
        var rendered = RenderTypeCore(type, resolver);
        return type.IsNullable ? rendered + " | null" : rendered;
    }

    /// <summary>Rendering safe to embed in composite positions (array elements, type arguments).</summary>
    private static string RenderAtomic(TsType type, TsImportResolver resolver)
    {
        var rendered = RenderType(type, resolver);
        return type.IsNullable || type.IsFunctionType ? "(" + rendered + ")" : rendered;
    }

    private static string RenderTypeCore(TsType type, TsImportResolver resolver)
    {
        if (type.IsFunctionType)
        {
            var parameters = string.Join(", ", type.FunctionParameters.Select(p =>
                $"{p.Name}: {RenderType(p.Type, resolver)}"));
            return $"({parameters}) => {RenderType(type.FunctionReturn ?? TsType.Void, resolver)}";
        }

        if (type.IsArray)
        {
            var element = RenderAtomic(type.ElementType!, resolver);
            return type.IsReadonlyArray ? $"readonly {element}[]" : $"{element}[]";
        }

        if (type.IsGenericParameter)
            return type.Name;

        var name = type.ModulePath.Length == 0 ? type.Name : resolver.Generated(type);
        if (type.TypeArguments.Count == 0)
            return name;

        return name + "<" + string.Join(", ", type.TypeArguments.Select(a => RenderType(a, resolver))) + ">";
    }

    private static string RenderExpr(TsExpr expr, TsImportResolver resolver) => expr switch
    {
        TsExpr.Null => "null",
        TsExpr.Literal literal => literal.Text,
        TsExpr.StringLiteral s => Quote(s.Value),
        TsExpr.EnumEntry entry => resolver.Generated(entry.EnumType) + "." + entry.EntryName,
        _ => throw new InvalidOperationException($"Unknown expression {expr.GetType().Name}"),
    };

    private static string Quote(string value)
    {
        var sb = new StringBuilder("\"");
        foreach (var c in value)
        {
            sb.Append(c switch
            {
                '\\' => "\\\\",
                '"' => "\\\"",
                '\n' => "\\n",
                '\r' => "\\r",
                '\t' => "\\t",
                _ => c.ToString(),
            });
        }

        return sb.Append('"').ToString();
    }

    private static void EmitDoc(CodeWriter writer, string? rawXml, string? deprecationMessage)
    {
        var lines = TsDocConverter.ToDocLines(rawXml).ToList();

        if (deprecationMessage is not null)
        {
            if (lines.Count > 0)
                lines.Add("");
            lines.Add("@deprecated " + deprecationMessage.Replace("\n", " ").Replace("\r", " "));
        }

        if (lines.Count == 0)
            return;

        writer.Line("/**");
        foreach (var line in lines)
            writer.Line((" * " + line).TrimEnd());
        writer.Line(" */");
    }
}
