// <auto-generated>
// Generated by QuestPDF.Interop.Generator from QuestPDF 2026.7.1.0.
// Do not edit — this file is wiped and recreated on every generator run.
// </auto-generated>

package com.questpdf.fluent

import com.questpdf.elements.table.ITableCellContainer
import com.questpdf.elements.table.TableCellContainerImpl
import com.questpdf.interop.NativeBridge
import com.questpdf.interop.NativeCallbackJToV
import com.questpdf.interop.NativeObject
import java.util.function.Consumer

class TableDescriptor internal constructor(handle: Long) : NativeObject(handle) {
    /**
     * Inserts a new item into the table element.
     *
     * @return The container for the newly inserted cell, enabling customization of its position, size, and content.
     */
    fun cell(): ITableCellContainer =
        TableCellContainerImpl(NativeBridge.checked(NativeBridge.lib.QP_TableDescriptor_cell_0(nativeHandle)))

    /**
     * Specifies the order and size of the table columns.
     * [Learn more](https://www.questpdf.com/api-reference/table/basics.html#columns-definition)
     *
     * This configuration affects both the main content as well as the header and footer sections.
     *
     * @param handler Handler to define columns of the table.
     */
    fun columnsDefinition(handler: TableColumnsDefinitionDescriptor.() -> Unit) {
        NativeBridge.lib.QP_TableDescriptor_columnsDefinition_0(nativeHandle, NativeBridge.retain(NativeCallbackJToV { p0 -> NativeBridge.guard(Unit) { handler(TableColumnsDefinitionDescriptor(p0)) } }))
        NativeBridge.check()
    }

    /**
     * Specifies the order and size of the table columns.
     * [Learn more](https://www.questpdf.com/api-reference/table/basics.html#columns-definition)
     *
     * This configuration affects both the main content as well as the header and footer sections.
     *
     * @param handler Handler to define columns of the table.
     */
    fun columnsDefinition(handler: Consumer<TableColumnsDefinitionDescriptor>) {
        columnsDefinition({ handler.accept(this) })
    }

    /**
     * Adjusts rendering algorithm to better handle complex table structures, especially those spanning multiple pages.
     * This applies a unique rule to the final cells in each column, ensuring they stretch to fill the table's bottom edge.
     * Such an approach can enhance your table's visual appeal.
     */
    fun extendLastCellsToTableBottom() {
        NativeBridge.lib.QP_TableDescriptor_extendLastCellsToTableBottom_0(nativeHandle)
        NativeBridge.check()
    }

    /**
     * Specifies a table footer that appears on each page, positioned below the main content.
     * The placement and dimensions of cells within this footer are distinct from the main content.
     * [Learn more](https://www.questpdf.com/api-reference/table/header-and-footer.html)
     */
    fun footer(handler: TableCellDescriptor.() -> Unit) {
        NativeBridge.lib.QP_TableDescriptor_footer_0(nativeHandle, NativeBridge.retain(NativeCallbackJToV { p0 -> NativeBridge.guard(Unit) { handler(TableCellDescriptor(p0)) } }))
        NativeBridge.check()
    }

    /**
     * Specifies a table footer that appears on each page, positioned below the main content.
     * The placement and dimensions of cells within this footer are distinct from the main content.
     * [Learn more](https://www.questpdf.com/api-reference/table/header-and-footer.html)
     */
    fun footer(handler: Consumer<TableCellDescriptor>) {
        footer({ handler.accept(this) })
    }

    /**
     * Specifies a table header that appears on each page, positioned above the main content.
     * The cell placement and dimensions in this header are distinct from those in the main content.
     * [Learn more](https://www.questpdf.com/api-reference/table/header-and-footer.html)
     *
     * @param handler Handler for configuring the header cells.
     */
    fun header(handler: TableCellDescriptor.() -> Unit) {
        NativeBridge.lib.QP_TableDescriptor_header_0(nativeHandle, NativeBridge.retain(NativeCallbackJToV { p0 -> NativeBridge.guard(Unit) { handler(TableCellDescriptor(p0)) } }))
        NativeBridge.check()
    }

    /**
     * Specifies a table header that appears on each page, positioned above the main content.
     * The cell placement and dimensions in this header are distinct from those in the main content.
     * [Learn more](https://www.questpdf.com/api-reference/table/header-and-footer.html)
     *
     * @param handler Handler for configuring the header cells.
     */
    fun header(handler: Consumer<TableCellDescriptor>) {
        header({ handler.accept(this) })
    }
}
