// <auto-generated>
// Generated by QuestPDF.Interop.Generator from QuestPDF 2026.7.1.0.
// Do not edit — this file is wiped and recreated on every generator run.
// </auto-generated>

package com.questpdf.fluent

import com.questpdf.infrastructure.Color
import com.questpdf.infrastructure.TextStyle
import com.questpdf.interop.NativeBridge
import com.questpdf.interop.NativeCallbackJToJ
import com.questpdf.interop.NativeObject

open class TextSpanDescriptor internal constructor(handle: Long) : NativeObject(handle) {
    /**
     * Sets a solid background color for the text.
     * This color fills the area behind the text or other elements, enhancing contrast and providing visual emphasis.
     *
     * @param color Color in a [valid format](https://www.questpdf.com/concepts/colors.html) (like `#FF8800` for orange) or from the predefined [Colors] set (like `Colors.Red.Lighten1`).
     */
    open fun backgroundColor(color: Color): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_backgroundColor_0(nativeHandle, color.nativeHandle)))

    /**
     * Sets the font weight to "black" (equivalent to CSS 900).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    open fun black(): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_black_0(nativeHandle)))

    /**
     * Sets the font weight to "bold" (equivalent to CSS 700).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    open fun bold(): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_bold_0(nativeHandle)))

    /**
     * Sets the color of the text decoration.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    open fun decorationColor(color: Color): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_decorationColor_0(nativeHandle, color.nativeHandle)))

    /**
     * Sets the decoration line to dashes.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    open fun decorationDashed(): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_decorationDashed_0(nativeHandle)))

    /**
     * Sets the decoration line to dots.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    open fun decorationDotted(): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_decorationDotted_0(nativeHandle)))

    /**
     * Sets the decoration line to a solid double line.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    open fun decorationDouble(): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_decorationDouble_0(nativeHandle)))

    /**
     * Sets the decoration line to a solid straight line.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    open fun decorationSolid(): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_decorationSolid_0(nativeHandle)))

    /**
     * Changess thickness of decoration line proportionally to the provided argument.
     * Value equal to 1 is the default thickness.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    open fun decorationThickness(factor: Float): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_decorationThickness_0(nativeHandle, factor)))

    /**
     * Sets the decoration line to wave.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    open fun decorationWavy(): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_decorationWavy_0(nativeHandle)))

    /**
     * Resets the text direction, enabling content to follow the automatically detected direction.
     */
    open fun directionAuto(): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_directionAuto_0(nativeHandle)))

    /**
     * Enforces a left-to-right text direction.
     */
    open fun directionFromLeftToRight(): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_directionFromLeftToRight_0(nativeHandle)))

    /**
     * Enforces a right-to-left text direction.
     */
    open fun directionFromRightToLeft(): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_directionFromRightToLeft_0(nativeHandle)))

    /**
     * Enables or disables font features defined by the OpenType standard, e.g. kernig, ligatures.
     *
     * Font features are always encoded as 4-character long strings. For example, the ligatures feature is encode as `liga`, while the kernig feature as `kern`.
     * For a list of available features, refer to the [FontFeatures] class.
     *
     * To better understand what font features are, please consider example definitions. Please note that there are many more various font features. Most fonts support only a handful of them, having some of them enabled by default:
     *
     * Ligatures in typography are specific character combinations that are designed to improve the aesthetics and readability of certain letter pairs. For example, in some fonts, when you type certain combinations of letters like 'fi' or 'fl', they will be replaced with a single, joined glyph.
     *
     * Kerning in typography refers to the adjustment of space between characters in a proportional font. It's used to achieve a visually pleasing result by adjusting the spacing of specific character pairs. For example, in many fonts, the pair 'AV' is kerned so that the 'A' and 'V' are closer together than they would be by default.
     *
     * TextStyle.Default.EnableFontFeature(FontFeatures.StandardLigatures);
     *
     * TextStyle.Default.DisableFontFeature(FontFeatures.Kerning);
     *
     * @param value Provide font feature name or use the [FontFeatures] class.
     */
    open fun disableFontFeature(featureName: String): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_disableFontFeature_0(nativeHandle, featureName)))

    /**
     * Enables or disables font features defined by the OpenType standard, e.g. kernig, ligatures.
     *
     * Font features are always encoded as 4-character long strings. For example, the ligatures feature is encode as `liga`, while the kernig feature as `kern`.
     * For a list of available features, refer to the [FontFeatures] class.
     *
     * To better understand what font features are, please consider example definitions. Please note that there are many more various font features. Most fonts support only a handful of them, having some of them enabled by default:
     *
     * Ligatures in typography are specific character combinations that are designed to improve the aesthetics and readability of certain letter pairs. For example, in some fonts, when you type certain combinations of letters like 'fi' or 'fl', they will be replaced with a single, joined glyph.
     *
     * Kerning in typography refers to the adjustment of space between characters in a proportional font. It's used to achieve a visually pleasing result by adjusting the spacing of specific character pairs. For example, in many fonts, the pair 'AV' is kerned so that the 'A' and 'V' are closer together than they would be by default.
     *
     * TextStyle.Default.EnableFontFeature(FontFeatures.StandardLigatures);
     *
     * TextStyle.Default.DisableFontFeature(FontFeatures.Kerning);
     *
     * @param value Provide font feature name or use the [FontFeatures] class.
     */
    open fun enableFontFeature(featureName: String): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_enableFontFeature_0(nativeHandle, featureName)))

    /**
     * Sets the font weight to "extra black" (equivalent to CSS 1000).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    open fun extraBlack(): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_extraBlack_0(nativeHandle)))

    /**
     * Sets the font weight to "extra bold" (equivalent to CSS 800).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    open fun extraBold(): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_extraBold_0(nativeHandle)))

    /**
     * Sets the font weight to "extra light" (equivalent to CSS 200).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    open fun extraLight(): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_extraLight_0(nativeHandle)))

    @Deprecated("This setting is not supported since the 2024.3 version. Please use the FontFamilyFallback method or rely on the new automated fallback mechanism.")
    open fun fallback(handler: TextStyle.() -> TextStyle): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_fallback_1(nativeHandle, NativeBridge.retain(NativeCallbackJToJ { p0 -> NativeBridge.guard(0L) { (handler(TextStyle(p0))).nativeHandle } }))))

    @Deprecated("This setting is not supported since the 2024.3 version. Please use the FontFamilyFallback method or rely on the new automated fallback mechanism.")
    open fun fallback(value: TextStyle? = null): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_fallback_0(nativeHandle, (value?.nativeHandle ?: 0L))))

    /**
     * Sets the font color.
     * The font color determines the color applied to text characters, affecting their visual appearance.
     *
     * It also influences the default color of text decorations, such as underlines.
     *
     * @param color Color in a [valid format](https://www.questpdf.com/concepts/colors.html) (like `#FF8800` for orange) or from the predefined [Colors] set (like `Colors.Red.Lighten1`).
     */
    open fun fontColor(color: Color): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_fontColor_0(nativeHandle, color.nativeHandle)))

    /**
     * Sets the font family of the text.
     * A font family is a collection of related fonts that share a consistent design style but may vary in weight, style, or width.
     * Examples of font families include Arial, Times New Roman, and Calibri.
     *
     * By default, the library searches all fonts available in the runtime environment.
     *
     * This may work well on the development environment but may fail in the cloud where fonts are usually not installed.
     *
     * It is safest deploy font files along with the application and then register them using the [FontManager] class.
     *
     * @param value Actual font family (e.g. "Times New Roman", "Calibri", "Lato") or custom identifier used when invoking the [FontManager.RegisterFontWithCustomName] method.
     */
    open fun fontFamily(vararg values: String): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_fontFamily_0(nativeHandle, values, values.size)))

    /**
     * Sets font size for the text.
     * Font size measures the height of text characters, determining how large or small the text appears.
     *
     * It's worth noting that different fonts may render text with distinct visual sizes, even when assigned the same numerical font size.
     */
    open fun fontSize(value: Float): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_fontSize_0(nativeHandle, value)))

    /**
     * Renders text with an italic effect, where letters are slightly slanted to the right.
     * Commonly used for emphasis or to distinguish specific words.
     */
    open fun italic(value: Boolean = true): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_italic_0(nativeHandle, (if (value) 1 else 0))))

    /**
     * Adjusts the horizontal spacing between characters in the text, affecting readability and overall visual style.
     * The adjustment is proportional to the text size.
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#letter-spacing)
     *
     * @param factor Sets the proportion by which the horizontal space between characters is changed.  A value of 0 maintains the original spacing. When the value is positive, the text is more spread out. When it is negative, the text is more condensed.
     */
    open fun letterSpacing(factor: Float = 0f): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_letterSpacing_0(nativeHandle, factor)))

    /**
     * Sets the font weight to "light" (equivalent to CSS 300).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    open fun light(): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_light_0(nativeHandle)))

    /**
     * Adjusts the vertical spacing between lines of text, affecting readability and overall text layout.
     * The added space is proportional to the text size.
     * A [factor] value of 1 retains the original spacing.
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#line-height)
     *
     * @param factor Sets the proportion of vertical spacing relative to the font size.  A value greater than 1 increases the spacing, while a value less than 1 decreases it. The value must be greater than 0.  A value of `1` sets the line height equal to the font size. This setting may result in insufficient vertical spacing around the text.  A value of `default` indicates that the font metrics should be used to calculate the line spacing, which is the default behavior.
     */
    open fun lineHeight(factor: Float?): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_lineHeight_0(nativeHandle, (if (factor != null) 1 else 0).toByte(), (factor ?: 0f))))

    /**
     * Sets the font weight to "medium" (equivalent to CSS 500).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    open fun medium(): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_medium_0(nativeHandle)))

    /**
     * Resets the text position and size to default, utilizing the full available line height.
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#subscript)
     */
    open fun normalPosition(): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_normalPosition_0(nativeHandle)))

    /**
     * Sets the font weight to "normal" or "regular (equivalent to CSS 400).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    open fun normalWeight(): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_normalWeight_0(nativeHandle)))

    /**
     * Draws a line above the text.
     *
     * You can control the decoration visuals by setting color and style (solid, double, wavy, dotted, dashed) of the line.
     */
    open fun overline(value: Boolean = true): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_overline_0(nativeHandle, (if (value) 1 else 0))))

    /**
     * Sets the font weight to "semi bold" (equivalent to CSS 600).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    open fun semiBold(): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_semiBold_0(nativeHandle)))

    /**
     * Draws a line through the middle of the text.
     *
     * You can control the decoration visuals by setting color and style (solid, double, wavy, dotted, dashed) of the line.
     */
    open fun strikethrough(value: Boolean = true): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_strikethrough_0(nativeHandle, (if (value) 1 else 0))))

    /**
     * Sets a font style using the typography pattern.
     * [Learn more](https://www.questpdf.com/api-reference/text/basics.html#typography-pattern)
     *
     * This API reduces the garbage collector pressure and offers the best performance.
     */
    open fun style(style: TextStyle): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_style_0(nativeHandle, style.nativeHandle)))

    /**
     * Sets the text style to subscript, making it smaller and positioning it below the baseline, e.g.: H₂0.
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#subscript)
     */
    open fun subscript(): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_subscript_0(nativeHandle)))

    /**
     * Sets the text style to subscript, making it smaller and positioning it above the baseline, e.g.: y² + x² = 1.
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#superscript)
     */
    open fun superscript(): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_superscript_0(nativeHandle)))

    /**
     * Sets the font weight to "thin" (equivalent to CSS 100).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    open fun thin(): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_thin_0(nativeHandle)))

    /**
     * Draws a line under the text.
     *
     * You can control the decoration visuals by setting color and style (solid, double, wavy, dotted, dashed) of the line.
     */
    open fun underline(value: Boolean = true): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_underline_0(nativeHandle, (if (value) 1 else 0))))

    /**
     * Adjusts the horizontal spacing between words in the text, affecting readability and overall visual style.
     * The adjustment is proportional to the text size.
     *
     * @param factor Sets the proportion by which the horizontal space between words is changed.  A value of 0 maintains the original spacing. When the value is positive, the text is more spread out. When it is negative, the text is more condensed.
     */
    open fun wordSpacing(factor: Float = 0f): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_wordSpacing_0(nativeHandle, factor)))

    /**
     * Allows text to wrap at any character, not just spaces.
     */
    @Deprecated("This setting is not supported since the 2024.3 version. This flag should be handled automatically by the layout engine.")
    open fun wrapAnywhere(value: Boolean = true): TextSpanDescriptor =
        TextSpanDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextSpanDescriptor_wrapAnywhere_0(nativeHandle, (if (value) 1 else 0))))
}
