// <auto-generated>
// Generated by QuestPDF.Interop.Generator from QuestPDF 2026.7.1.0.
// Do not edit — this file is wiped and recreated on every generator run.
// </auto-generated>

package com.questpdf.fluent

import com.questpdf.infrastructure.Color
import com.questpdf.infrastructure.TextStyle
import com.questpdf.interop.NativeBridge
import com.questpdf.interop.NativeCallbackJToJ

class TextBlockDescriptor internal constructor(handle: Long) : TextSpanDescriptor(handle) {
    /**
     * Aligns text horizontally to the center, ensuring equal space on both left and right sides.
     */
    fun alignCenter(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_alignCenter_0(nativeHandle)))

    /**
     * Aligns the text horizontally to the end of the container.
     * This method sets the horizontal alignment of the text to the end (right for left-to-right languages, left for right-to-left languages).
     */
    fun alignEnd(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_alignEnd_0(nativeHandle)))

    /**
     * Aligns text horizontally to the left side.
     */
    fun alignLeft(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_alignLeft_0(nativeHandle)))

    /**
     * Aligns content horizontally to the right side.
     */
    fun alignRight(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_alignRight_0(nativeHandle)))

    /**
     * Aligns the text horizontally to the start of the container.
     * This method sets the horizontal alignment of the text to the start (left for left-to-right languages, right for right-to-left languages).
     */
    fun alignStart(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_alignStart_0(nativeHandle)))

    /**
     * Sets a solid background color for the text.
     * This color fills the area behind the text or other elements, enhancing contrast and providing visual emphasis.
     *
     * @param color Color in a [valid format](https://www.questpdf.com/concepts/colors.html) (like `#FF8800` for orange) or from the predefined [Colors] set (like `Colors.Red.Lighten1`).
     */
    override fun backgroundColor(color: Color): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_backgroundColor_0(nativeHandle, color.nativeHandle)))

    /**
     * Sets the font weight to "black" (equivalent to CSS 900).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    override fun black(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_black_0(nativeHandle)))

    /**
     * Sets the font weight to "bold" (equivalent to CSS 700).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    override fun bold(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_bold_0(nativeHandle)))

    /**
     * Limits the number of visible lines in a paragraph, truncating overflow text with an ellipsis or by hiding it to maintain layout consistency.
     */
    fun clampLines(maxLines: Int, ellipsis: String = "…"): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_clampLines_0(nativeHandle, maxLines, ellipsis)))

    /**
     * Sets the color of the text decoration.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    override fun decorationColor(color: Color): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_decorationColor_0(nativeHandle, color.nativeHandle)))

    /**
     * Sets the decoration line to dashes.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    override fun decorationDashed(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_decorationDashed_0(nativeHandle)))

    /**
     * Sets the decoration line to dots.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    override fun decorationDotted(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_decorationDotted_0(nativeHandle)))

    /**
     * Sets the decoration line to a solid double line.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    override fun decorationDouble(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_decorationDouble_0(nativeHandle)))

    /**
     * Sets the decoration line to a solid straight line.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    override fun decorationSolid(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_decorationSolid_0(nativeHandle)))

    /**
     * Changess thickness of decoration line proportionally to the provided argument.
     * Value equal to 1 is the default thickness.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    override fun decorationThickness(factor: Float): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_decorationThickness_0(nativeHandle, factor)))

    /**
     * Sets the decoration line to wave.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    override fun decorationWavy(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_decorationWavy_0(nativeHandle)))

    /**
     * Resets the text direction, enabling content to follow the automatically detected direction.
     */
    override fun directionAuto(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_directionAuto_0(nativeHandle)))

    /**
     * Enforces a left-to-right text direction.
     */
    override fun directionFromLeftToRight(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_directionFromLeftToRight_0(nativeHandle)))

    /**
     * Enforces a right-to-left text direction.
     */
    override fun directionFromRightToLeft(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_directionFromRightToLeft_0(nativeHandle)))

    /**
     * Enables or disables font features defined by the OpenType standard, e.g. kernig, ligatures.
     *
     * Font features are always encoded as 4-character long strings. For example, the ligatures feature is encode as `liga`, while the kernig feature as `kern`.
     * For a list of available features, refer to the [FontFeatures] class.
     *
     * To better understand what font features are, please consider example definitions. Please note that there are many more various font features. Most fonts support only a handful of them, having some of them enabled by default:
     *
     * Ligatures in typography are specific character combinations that are designed to improve the aesthetics and readability of certain letter pairs. For example, in some fonts, when you type certain combinations of letters like 'fi' or 'fl', they will be replaced with a single, joined glyph.
     *
     * Kerning in typography refers to the adjustment of space between characters in a proportional font. It's used to achieve a visually pleasing result by adjusting the spacing of specific character pairs. For example, in many fonts, the pair 'AV' is kerned so that the 'A' and 'V' are closer together than they would be by default.
     *
     * TextStyle.Default.EnableFontFeature(FontFeatures.StandardLigatures);
     *
     * TextStyle.Default.DisableFontFeature(FontFeatures.Kerning);
     *
     * @param value Provide font feature name or use the [FontFeatures] class.
     */
    override fun disableFontFeature(featureName: String): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_disableFontFeature_0(nativeHandle, featureName)))

    /**
     * Enables or disables font features defined by the OpenType standard, e.g. kernig, ligatures.
     *
     * Font features are always encoded as 4-character long strings. For example, the ligatures feature is encode as `liga`, while the kernig feature as `kern`.
     * For a list of available features, refer to the [FontFeatures] class.
     *
     * To better understand what font features are, please consider example definitions. Please note that there are many more various font features. Most fonts support only a handful of them, having some of them enabled by default:
     *
     * Ligatures in typography are specific character combinations that are designed to improve the aesthetics and readability of certain letter pairs. For example, in some fonts, when you type certain combinations of letters like 'fi' or 'fl', they will be replaced with a single, joined glyph.
     *
     * Kerning in typography refers to the adjustment of space between characters in a proportional font. It's used to achieve a visually pleasing result by adjusting the spacing of specific character pairs. For example, in many fonts, the pair 'AV' is kerned so that the 'A' and 'V' are closer together than they would be by default.
     *
     * TextStyle.Default.EnableFontFeature(FontFeatures.StandardLigatures);
     *
     * TextStyle.Default.DisableFontFeature(FontFeatures.Kerning);
     *
     * @param value Provide font feature name or use the [FontFeatures] class.
     */
    override fun enableFontFeature(featureName: String): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_enableFontFeature_0(nativeHandle, featureName)))

    /**
     * Sets the font weight to "extra black" (equivalent to CSS 1000).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    override fun extraBlack(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_extraBlack_0(nativeHandle)))

    /**
     * Sets the font weight to "extra bold" (equivalent to CSS 800).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    override fun extraBold(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_extraBold_0(nativeHandle)))

    /**
     * Sets the font weight to "extra light" (equivalent to CSS 200).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    override fun extraLight(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_extraLight_0(nativeHandle)))

    @Deprecated("This setting is not supported since the 2024.3 version. Please use the FontFamilyFallback method or rely on the new automated fallback mechanism.")
    override fun fallback(handler: TextStyle.() -> TextStyle): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_fallback_1(nativeHandle, NativeBridge.retain(NativeCallbackJToJ { p0 -> NativeBridge.guard(0L) { (handler(TextStyle(p0))).nativeHandle } }))))

    @Deprecated("This setting is not supported since the 2024.3 version. Please use the FontFamilyFallback method or rely on the new automated fallback mechanism.")
    override fun fallback(value: TextStyle?): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_fallback_0(nativeHandle, (value?.nativeHandle ?: 0L))))

    /**
     * Sets the font color.
     * The font color determines the color applied to text characters, affecting their visual appearance.
     *
     * It also influences the default color of text decorations, such as underlines.
     *
     * @param color Color in a [valid format](https://www.questpdf.com/concepts/colors.html) (like `#FF8800` for orange) or from the predefined [Colors] set (like `Colors.Red.Lighten1`).
     */
    override fun fontColor(color: Color): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_fontColor_0(nativeHandle, color.nativeHandle)))

    /**
     * Sets the font family of the text.
     * A font family is a collection of related fonts that share a consistent design style but may vary in weight, style, or width.
     * Examples of font families include Arial, Times New Roman, and Calibri.
     *
     * By default, the library searches all fonts available in the runtime environment.
     *
     * This may work well on the development environment but may fail in the cloud where fonts are usually not installed.
     *
     * It is safest deploy font files along with the application and then register them using the [FontManager] class.
     *
     * @param value Actual font family (e.g. "Times New Roman", "Calibri", "Lato") or custom identifier used when invoking the [FontManager.RegisterFontWithCustomName] method.
     */
    override fun fontFamily(vararg values: String): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_fontFamily_0(nativeHandle, values, values.size)))

    /**
     * Sets font size for the text.
     * Font size measures the height of text characters, determining how large or small the text appears.
     *
     * It's worth noting that different fonts may render text with distinct visual sizes, even when assigned the same numerical font size.
     */
    override fun fontSize(value: Float): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_fontSize_0(nativeHandle, value)))

    /**
     * Renders text with an italic effect, where letters are slightly slanted to the right.
     * Commonly used for emphasis or to distinguish specific words.
     */
    override fun italic(value: Boolean): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_italic_0(nativeHandle, (if (value) 1 else 0))))

    /**
     * Justifies the text within its container.
     *
     * This method sets the horizontal alignment of the text to be justified, meaning it aligns along both the left and right margins.
     * This is achieved by adjusting the spacing between words and characters as necessary so that each line of text stretches from one end of the text column to the other.
     * This creates a clean, block-like appearance for the text.
     */
    fun justify(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_justify_0(nativeHandle)))

    /**
     * Adjusts the horizontal spacing between characters in the text, affecting readability and overall visual style.
     * The adjustment is proportional to the text size.
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#letter-spacing)
     *
     * @param factor Sets the proportion by which the horizontal space between characters is changed.  A value of 0 maintains the original spacing. When the value is positive, the text is more spread out. When it is negative, the text is more condensed.
     */
    override fun letterSpacing(factor: Float): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_letterSpacing_0(nativeHandle, factor)))

    /**
     * Sets the font weight to "light" (equivalent to CSS 300).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    override fun light(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_light_0(nativeHandle)))

    /**
     * Adjusts the vertical spacing between lines of text, affecting readability and overall text layout.
     * The added space is proportional to the text size.
     * A [factor] value of 1 retains the original spacing.
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#line-height)
     *
     * @param factor Sets the proportion of vertical spacing relative to the font size.  A value greater than 1 increases the spacing, while a value less than 1 decreases it. The value must be greater than 0.  A value of `1` sets the line height equal to the font size. This setting may result in insufficient vertical spacing around the text.  A value of `default` indicates that the font metrics should be used to calculate the line spacing, which is the default behavior.
     */
    override fun lineHeight(factor: Float?): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_lineHeight_0(nativeHandle, (if (factor != null) 1 else 0).toByte(), (factor ?: 0f))))

    /**
     * Sets the font weight to "medium" (equivalent to CSS 500).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    override fun medium(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_medium_0(nativeHandle)))

    /**
     * Resets the text position and size to default, utilizing the full available line height.
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#subscript)
     */
    override fun normalPosition(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_normalPosition_0(nativeHandle)))

    /**
     * Sets the font weight to "normal" or "regular (equivalent to CSS 400).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    override fun normalWeight(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_normalWeight_0(nativeHandle)))

    /**
     * Draws a line above the text.
     *
     * You can control the decoration visuals by setting color and style (solid, double, wavy, dotted, dashed) of the line.
     */
    override fun overline(value: Boolean): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_overline_0(nativeHandle, (if (value) 1 else 0))))

    /**
     * Specifies the horizontal offset of the first line in a paragraph.
     * Commonly used to visually separate paragraphs in a block of text.
     */
    fun paragraphFirstLineIndentation(value: Float, unit: com.questpdf.infrastructure.Unit = com.questpdf.infrastructure.Unit.Point): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_paragraphFirstLineIndentation_0(nativeHandle, value, unit.value)))

    /**
     * Adjusts the vertical gap between successive paragraphs (separated by line breaks),
     * helping to visually separate blocks of text for improved readability.
     */
    fun paragraphSpacing(value: Float, unit: com.questpdf.infrastructure.Unit = com.questpdf.infrastructure.Unit.Point): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_paragraphSpacing_0(nativeHandle, value, unit.value)))

    /**
     * Sets the font weight to "semi bold" (equivalent to CSS 600).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    override fun semiBold(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_semiBold_0(nativeHandle)))

    /**
     * Draws a line through the middle of the text.
     *
     * You can control the decoration visuals by setting color and style (solid, double, wavy, dotted, dashed) of the line.
     */
    override fun strikethrough(value: Boolean): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_strikethrough_0(nativeHandle, (if (value) 1 else 0))))

    /**
     * Sets a font style using the typography pattern.
     * [Learn more](https://www.questpdf.com/api-reference/text/basics.html#typography-pattern)
     *
     * This API reduces the garbage collector pressure and offers the best performance.
     */
    override fun style(style: TextStyle): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_style_0(nativeHandle, style.nativeHandle)))

    /**
     * Sets the text style to subscript, making it smaller and positioning it below the baseline, e.g.: H₂0.
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#subscript)
     */
    override fun subscript(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_subscript_0(nativeHandle)))

    /**
     * Sets the text style to subscript, making it smaller and positioning it above the baseline, e.g.: y² + x² = 1.
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#superscript)
     */
    override fun superscript(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_superscript_0(nativeHandle)))

    /**
     * Sets the font weight to "thin" (equivalent to CSS 100).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    override fun thin(): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_thin_0(nativeHandle)))

    /**
     * Draws a line under the text.
     *
     * You can control the decoration visuals by setting color and style (solid, double, wavy, dotted, dashed) of the line.
     */
    override fun underline(value: Boolean): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_underline_0(nativeHandle, (if (value) 1 else 0))))

    /**
     * Adjusts the horizontal spacing between words in the text, affecting readability and overall visual style.
     * The adjustment is proportional to the text size.
     *
     * @param factor Sets the proportion by which the horizontal space between words is changed.  A value of 0 maintains the original spacing. When the value is positive, the text is more spread out. When it is negative, the text is more condensed.
     */
    override fun wordSpacing(factor: Float): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_wordSpacing_0(nativeHandle, factor)))

    /**
     * Allows text to wrap at any character, not just spaces.
     */
    @Deprecated("This setting is not supported since the 2024.3 version. This flag should be handled automatically by the layout engine.")
    override fun wrapAnywhere(value: Boolean): TextBlockDescriptor =
        TextBlockDescriptor(NativeBridge.checked(NativeBridge.lib.QP_TextBlockDescriptor_wrapAnywhere_0(nativeHandle, (if (value) 1 else 0))))
}
