// <auto-generated>
// Generated by QuestPDF.Interop.Generator from QuestPDF 2026.7.1.0.
// Do not edit — this file is wiped and recreated on every generator run.
// </auto-generated>

package com.questpdf.infrastructure

import com.questpdf.interop.NativeBridge
import com.questpdf.interop.NativeObject

class Color internal constructor(handle: Long) : NativeObject(handle) {
    /**
     * Creates a new color from a hex value following the ARGB format.
     * For example 0xFF0000FF represents a fully opaque blue color.
     */
    constructor(hex: UInt) :
        this(NativeBridge.checked(NativeBridge.lib.QP_Color_ctor_0(hex.toInt())))

    val alpha: UByte
        get() = NativeBridge.checked(NativeBridge.lib.QP_Color_getAlpha_0(nativeHandle)).toUByte()

    val blue: UByte
        get() = NativeBridge.checked(NativeBridge.lib.QP_Color_getBlue_0(nativeHandle)).toUByte()

    val green: UByte
        get() = NativeBridge.checked(NativeBridge.lib.QP_Color_getGreen_0(nativeHandle)).toUByte()

    val hex: UInt
        get() = NativeBridge.checked(NativeBridge.lib.QP_Color_getHex_0(nativeHandle)).toUInt()

    val red: UByte
        get() = NativeBridge.checked(NativeBridge.lib.QP_Color_getRed_0(nativeHandle)).toUByte()

    fun toUInt(): UInt =
        NativeBridge.checked(NativeBridge.lib.QP_Color_toUInt32_0(nativeHandle)).toUInt()

    /**
     * Creates a new color instance with the specified alpha transparency value.
     * The alpha value should be within the range 0 to 1, where 0 represents fully transparent
     * and 1 represents fully opaque.
     *
     * @return A new color instance with the adjusted alpha transparency.
     */
    fun withAlpha(alpha: Float): Color =
        Color(NativeBridge.checked(NativeBridge.lib.QP_Color_withAlpha_1(nativeHandle, alpha)))

    /**
     * Creates a new color instance with the specified alpha transparency value.
     * The alpha value should be within the range 0 to 255, where 0 represents fully transparent
     * and 255 represents fully opaque.
     *
     * @return A new color instance with the adjusted alpha transparency.
     */
    fun withAlpha(alpha: UByte): Color =
        Color(NativeBridge.checked(NativeBridge.lib.QP_Color_withAlpha_0(nativeHandle, alpha.toByte())))

    companion object {
        fun from(hex: String): Color =
            Color(NativeBridge.checked(NativeBridge.lib.QP_Color_from_0(hex)))

        fun from(hex: UInt): Color =
            Color(NativeBridge.checked(NativeBridge.lib.QP_Color_from_1(hex.toInt())))

        /**
         * Creates a new color instance from the specified alpha, red, green, and blue component values.
         * Each component should be within the range 0 to 255.
         */
        fun fromARGB(alpha: UByte, red: UByte, green: UByte, blue: UByte): Color =
            Color(NativeBridge.checked(NativeBridge.lib.QP_Color_fromARGB_0(alpha.toByte(), red.toByte(), green.toByte(), blue.toByte())))

        /**
         * Creates a new color instance from a hex string representation.
         * The string should follow the formats: #RGB, #ARGB, #RRGGBB, or #AARRGGBB.
         * The hash sign is optional; for example: RGB, ARGB, RRGGBB, or AARRGGBB are also valid.
         *
         * @param hex The hex string representing the color.
         * @return A new color instance created from the hex string.
         */
        fun fromHex(hex: String): Color =
            Color(NativeBridge.checked(NativeBridge.lib.QP_Color_fromHex_0(hex)))

        /**
         * Creates a new color instance given the red, green, and blue component values.
         * Each component should be within the range 0 to 255.
         */
        fun fromRGB(red: UByte, green: UByte, blue: UByte): Color =
            Color(NativeBridge.checked(NativeBridge.lib.QP_Color_fromRGB_0(red.toByte(), green.toByte(), blue.toByte())))
    }
}
