// <auto-generated>
// Generated by QuestPDF.Interop.Generator from QuestPDF 2026.7.1.0.
// Do not edit — this file is wiped and recreated on every generator run.
// </auto-generated>

package com.questpdf.infrastructure

enum class Unit(val value: Int) {
    /**
     * Point is a standard unit for all PDF documents.
     * 72 points equal 1 inch
     */
    Point(0),
    Meter(1),
    Centimetre(2),
    Millimetre(3),
    Feet(4),
    Inch(5),
    /**
     * 1/1000th of inch
     */
    Mil(6),
    ;

    companion object {
        @JvmStatic
        fun fromValue(value: Int): Unit = entries.first { it.value == value }
    }
}
