// <auto-generated>
// Generated by QuestPDF.Interop.Generator from QuestPDF 2026.7.1.0.
// Do not edit — this file is wiped and recreated on every generator run.
// </auto-generated>

package com.questpdf

import com.questpdf.infrastructure.LicenseType
import com.questpdf.interop.NativeBridge
import com.sun.jna.ptr.ByteByReference

object Settings {
    /**
     * This flag enables checking the font glyph availability.
     * If your text contains glyphs that are not present in the specified font,
     * 1) when this flag is enabled: the DocumentDrawingException is thrown. OR
     * 2) when this flag is disabled: placeholder characters are visible in the produced PDF file.
     * Enabling this flag may slightly decrease document generation performance.
     * However, it provides hints that used fonts are not sufficient to produce correct results.
     *
     * By default, this flag is enabled only when the debugger IS attached.
     */
    @JvmStatic
    var checkIfAllTextGlyphsAreAvailable: Boolean
        get() = (NativeBridge.checked(NativeBridge.lib.QP_Settings_getCheckIfAllTextGlyphsAreAvailable_0()) != 0)
        set(value) {
            NativeBridge.lib.QP_Settings_setCheckIfAllTextGlyphsAreAvailable_0((if (value) 1 else 0))
            NativeBridge.check()
        }

    @Deprecated("This setting is ignored since the 2023.10 version. The new infinite layout detection algorithm works automatically. You can safely remove this setting from your codebase.")
    @JvmStatic
    var documentLayoutExceptionThreshold: Int
        get() = NativeBridge.checked(NativeBridge.lib.QP_Settings_getDocumentLayoutExceptionThreshold_0())
        set(value) {
            NativeBridge.lib.QP_Settings_setDocumentLayoutExceptionThreshold_0(value)
            NativeBridge.check()
        }

    /**
     * This flag generates additional document elements to cache layout calculation results.
     * In the vast majority of cases, this significantly improves performance, while slightly increasing memory consumption.
     *
     * Enabled by default.
     */
    @JvmStatic
    var enableCaching: Boolean
        get() = (NativeBridge.checked(NativeBridge.lib.QP_Settings_getEnableCaching_0()) != 0)
        set(value) {
            NativeBridge.lib.QP_Settings_setEnableCaching_0((if (value) 1 else 0))
            NativeBridge.check()
        }

    /**
     * This flag generates additional document elements to improve layout debugging experience.
     * When the provided content contains size constraints impossible to meet, the library generates an enhanced exception message with additional location and layout measurement details.
     *
     * By default, this flag is enabled only when the debugger IS attached.
     */
    @JvmStatic
    var enableDebugging: Boolean
        get() = (NativeBridge.checked(NativeBridge.lib.QP_Settings_getEnableDebugging_0()) != 0)
        set(value) {
            NativeBridge.lib.QP_Settings_setEnableDebugging_0((if (value) 1 else 0))
            NativeBridge.check()
        }

    /**
     * Selects the QuestPDF license tier that applies to your usage. Set this once at application startup, before generating the first document.
     *
     * For more details, please check the [QuestPDF Pricing webpage](https://www.questpdf.com/pricing) and [QuestPDF License webpage](https://www.questpdf.com/license).
     */
    @JvmStatic
    var license: LicenseType?
        get() {
            val outHasValue = ByteByReference()
            val raw = NativeBridge.lib.QP_Settings_getLicense_0(outHasValue)
            NativeBridge.check()
            return if (outHasValue.value.toInt() != 0) LicenseType.fromValue(raw) else null
        }
        set(value) {
            NativeBridge.lib.QP_Settings_setLicense_0((if (value != null) 1 else 0).toByte(), (value?.value ?: 0))
            NativeBridge.check()
        }

    /**
     * Gets or sets the file path used for temporary storage during the document generation process.
     * This path is used by various operations that require temporary files.
     */
    @JvmStatic
    var temporaryStoragePath: String?
        get() = NativeBridge.takeString(NativeBridge.checked(NativeBridge.lib.QP_Settings_getTemporaryStoragePath_0()))
        set(value) {
            NativeBridge.lib.QP_Settings_setTemporaryStoragePath_0(value)
            NativeBridge.check()
        }

    /**
     * Decides whether the application should use the fonts available in the environment.
     *
     * When set to `true`, the application will use the fonts installed on the system where it is running. This is the default behavior.
     *
     * When set to `false`, the application will only use the fonts that have been registered using the `FontManager` class in the QuestPDF library.
     *
     * This property is useful when you want to control the fonts used by your application, especially in cases where the environment might not have the necessary fonts installed.
     */
    @JvmStatic
    var useEnvironmentFonts: Boolean
        get() = (NativeBridge.checked(NativeBridge.lib.QP_Settings_getUseEnvironmentFonts_0()) != 0)
        set(value) {
            NativeBridge.lib.QP_Settings_setUseEnvironmentFonts_0((if (value) 1 else 0))
            NativeBridge.check()
        }
}
