// <auto-generated>
// Generated by QuestPDF.Interop.Generator from QuestPDF 2026.7.1.0.
// Do not edit — this file is wiped and recreated on every generator run.
// </auto-generated>

package com.questpdf.interop

import com.sun.jna.Callback

// One fun-interface per callback ABI shape. JNA builds a native
// trampoline per instance; NativeBridge.retain keeps instances alive
// while native code may still call them.

internal fun interface NativeCallbackBIToJ : Callback {
    fun invoke(p0: Byte, p1: Int): Long
}

internal fun interface NativeCallbackIToJ : Callback {
    fun invoke(p0: Int): Long
}

internal fun interface NativeCallbackJToI : Callback {
    fun invoke(p0: Long): Int
}

internal fun interface NativeCallbackJToJ : Callback {
    fun invoke(p0: Long): Long
}

internal fun interface NativeCallbackJToV : Callback {
    fun invoke(p0: Long)
}
