// <auto-generated>
// Generated by QuestPDF.Interop.Generator from QuestPDF 2026.7.1.0.
// Do not edit — this file is wiped and recreated on every generator run.
// </auto-generated>

package com.questpdf.interop

import com.sun.jna.Pointer
import com.sun.jna.ptr.ByteByReference
import com.sun.jna.ptr.IntByReference
import com.sun.jna.ptr.PointerByReference

/**
 * JNA declarations for every UnmanagedCallersOnly export of the
 * QuestPDF.Native shared library. Method names equal entry-point names.
 */
@Suppress("FunctionName", "LongLine")
internal interface QuestPdfNative : QuestPdfNativeRuntime {
    fun QP_Settings_getCheckIfAllTextGlyphsAreAvailable_0(): Int
    fun QP_Settings_setCheckIfAllTextGlyphsAreAvailable_0(value: Int)
    fun QP_Settings_getDocumentLayoutExceptionThreshold_0(): Int
    fun QP_Settings_setDocumentLayoutExceptionThreshold_0(value: Int)
    fun QP_Settings_getEnableCaching_0(): Int
    fun QP_Settings_setEnableCaching_0(value: Int)
    fun QP_Settings_getEnableDebugging_0(): Int
    fun QP_Settings_setEnableDebugging_0(value: Int)
    fun QP_Settings_getLicense_0(outHasValue: ByteByReference): Int
    fun QP_Settings_setLicense_0(valueHasValue: Byte, value: Int)
    fun QP_Settings_getTemporaryStoragePath_0(): Pointer?
    fun QP_Settings_setTemporaryStoragePath_0(value: String?)
    fun QP_Settings_getUseEnvironmentFonts_0(): Int
    fun QP_Settings_setUseEnvironmentFonts_0(value: Int)
    fun QP_FontManager_registerFontFromEmbeddedResource_0(pathName: String?)
    fun QP_DynamicContext_ctor_0(): Long
    fun QP_DynamicContext_getAvailableSize_0(self: Long): Long
    fun QP_DynamicContext_getPageNumber_0(self: Long): Int
    fun QP_DynamicContext_getTotalPages_0(self: Long): Int
    fun QP_DynamicContext_createElement_0(self: Long, content: NativeCallbackJToV?): Long
    fun QP_GenerateDynamicImageDelegatePayload_ctor_0(): Long
    fun QP_GenerateDynamicImageDelegatePayload_getAvailableSpace_0(self: Long): Long
    fun QP_GenerateDynamicImageDelegatePayload_setAvailableSpace_0(self: Long, value: Long)
    fun QP_GenerateDynamicImageDelegatePayload_getDpi_0(self: Long): Int
    fun QP_GenerateDynamicImageDelegatePayload_setDpi_0(self: Long, value: Int)
    fun QP_GenerateDynamicImageDelegatePayload_getImageSize_0(self: Long): Long
    fun QP_GenerateDynamicImageDelegatePayload_setImageSize_0(self: Long, value: Long)
    fun QP_IDynamicElement_getSize_0(self: Long): Long
    fun QP_ShowIfContext_ctor_0(): Long
    fun QP_ShowIfContext_getPageNumber_0(self: Long): Int
    fun QP_ShowIfContext_getTotalPages_0(self: Long, outHasValue: ByteByReference): Int
    fun QP_ITableCellContainer_asSemanticHorizontalHeader_0(self: Long): Long
    fun QP_ITableCellContainer_column_0(self: Long, value: Int): Long
    fun QP_ITableCellContainer_columnSpan_0(self: Long, value: Int): Long
    fun QP_ITableCellContainer_row_0(self: Long, value: Int): Long
    fun QP_ITableCellContainer_rowSpan_0(self: Long, value: Int): Long
    fun QP_ColumnDescriptor_item_0(self: Long): Long
    fun QP_ColumnDescriptor_spacing_0(self: Long, value: Float, unit: Int)
    fun QP_DecorationDescriptor_after_0(self: Long): Long
    fun QP_DecorationDescriptor_after_1(self: Long, handler: NativeCallbackJToV?)
    fun QP_DecorationDescriptor_before_0(self: Long): Long
    fun QP_DecorationDescriptor_before_1(self: Long, handler: NativeCallbackJToV?)
    fun QP_DecorationDescriptor_content_0(self: Long): Long
    fun QP_DecorationDescriptor_content_1(self: Long, handler: NativeCallbackJToV?)
    fun QP_DecorationDescriptor_footer_0(self: Long): Long
    fun QP_DecorationDescriptor_footer_1(self: Long, handler: NativeCallbackJToV?)
    fun QP_DecorationDescriptor_header_0(self: Long): Long
    fun QP_DecorationDescriptor_header_1(self: Long, handler: NativeCallbackJToV?)
    fun QP_Document_compose_0(self: Long, container: Long)
    fun QP_Document_getMetadata_0(self: Long): Long
    fun QP_Document_getSettings_0(self: Long): Long
    fun QP_Document_withMetadata_0(self: Long, metadata: Long): Long
    fun QP_Document_withSettings_0(self: Long, settings: Long): Long
    fun QP_Document_create_0(handler: NativeCallbackJToV?): Long
    fun QP_Document_merge_0(documents: LongArray?, documentsCount: Int): Long
    fun QP_Document_merge_1(documents: LongArray?, documentsCount: Int): Long
    fun QP_DocumentOperation_addAttachment_0(self: Long, attachment: Long): Long
    fun QP_DocumentOperation_decrypt_0(self: Long): Long
    fun QP_DocumentOperation_encrypt_0(self: Long, encryption: Long): Long
    fun QP_DocumentOperation_encrypt_1(self: Long, encryption: Long): Long
    fun QP_DocumentOperation_encrypt_2(self: Long, encryption: Long): Long
    fun QP_DocumentOperation_extendMetadata_0(self: Long, metadata: String?): Long
    fun QP_DocumentOperation_linearize_0(self: Long): Long
    fun QP_DocumentOperation_mergeFile_0(self: Long, filePath: String?, pageSelector: String?): Long
    fun QP_DocumentOperation_overlayFile_0(self: Long, configuration: Long): Long
    fun QP_DocumentOperation_removeRestrictions_0(self: Long): Long
    fun QP_DocumentOperation_save_0(self: Long, filePath: String?)
    fun QP_DocumentOperation_takePages_0(self: Long, pageSelector: String?): Long
    fun QP_DocumentOperation_underlayFile_0(self: Long, configuration: Long): Long
    fun QP_DocumentOperation_loadFile_0(filePath: String?, password: String?): Long
    fun QP_DocumentOperation_DocumentAttachment_ctor_0(): Long
    fun QP_DocumentOperation_DocumentAttachment_getAttachmentName_0(self: Long): Pointer?
    fun QP_DocumentOperation_DocumentAttachment_setAttachmentName_0(self: Long, value: String?)
    fun QP_DocumentOperation_DocumentAttachment_getCreationDate_0(self: Long): Pointer?
    fun QP_DocumentOperation_DocumentAttachment_setCreationDate_0(self: Long, value: String?)
    fun QP_DocumentOperation_DocumentAttachment_getDescription_0(self: Long): Pointer?
    fun QP_DocumentOperation_DocumentAttachment_setDescription_0(self: Long, value: String?)
    fun QP_DocumentOperation_DocumentAttachment_getFilePath_0(self: Long): Pointer?
    fun QP_DocumentOperation_DocumentAttachment_setFilePath_0(self: Long, value: String?)
    fun QP_DocumentOperation_DocumentAttachment_getKey_0(self: Long): Pointer?
    fun QP_DocumentOperation_DocumentAttachment_setKey_0(self: Long, value: String?)
    fun QP_DocumentOperation_DocumentAttachment_getMimeType_0(self: Long): Pointer?
    fun QP_DocumentOperation_DocumentAttachment_setMimeType_0(self: Long, value: String?)
    fun QP_DocumentOperation_DocumentAttachment_getModificationDate_0(self: Long): Pointer?
    fun QP_DocumentOperation_DocumentAttachment_setModificationDate_0(self: Long, value: String?)
    fun QP_DocumentOperation_DocumentAttachment_getRelationship_0(self: Long, outHasValue: ByteByReference): Int
    fun QP_DocumentOperation_DocumentAttachment_setRelationship_0(self: Long, valueHasValue: Byte, value: Int)
    fun QP_DocumentOperation_DocumentAttachment_getReplace_0(self: Long): Int
    fun QP_DocumentOperation_DocumentAttachment_setReplace_0(self: Long, value: Int)
    fun QP_DocumentOperation_Encryption128Bit_ctor_0(): Long
    fun QP_DocumentOperation_Encryption128Bit_getAllowAnnotation_0(self: Long): Int
    fun QP_DocumentOperation_Encryption128Bit_setAllowAnnotation_0(self: Long, value: Int)
    fun QP_DocumentOperation_Encryption128Bit_getAllowAssembly_0(self: Long): Int
    fun QP_DocumentOperation_Encryption128Bit_setAllowAssembly_0(self: Long, value: Int)
    fun QP_DocumentOperation_Encryption128Bit_getAllowContentExtraction_0(self: Long): Int
    fun QP_DocumentOperation_Encryption128Bit_setAllowContentExtraction_0(self: Long, value: Int)
    fun QP_DocumentOperation_Encryption128Bit_getAllowFillingForms_0(self: Long): Int
    fun QP_DocumentOperation_Encryption128Bit_setAllowFillingForms_0(self: Long, value: Int)
    fun QP_DocumentOperation_Encryption128Bit_getAllowPrinting_0(self: Long): Int
    fun QP_DocumentOperation_Encryption128Bit_setAllowPrinting_0(self: Long, value: Int)
    fun QP_DocumentOperation_Encryption128Bit_getEncryptMetadata_0(self: Long): Int
    fun QP_DocumentOperation_Encryption128Bit_setEncryptMetadata_0(self: Long, value: Int)
    fun QP_DocumentOperation_Encryption256Bit_ctor_0(): Long
    fun QP_DocumentOperation_Encryption256Bit_getAllowAnnotation_0(self: Long): Int
    fun QP_DocumentOperation_Encryption256Bit_setAllowAnnotation_0(self: Long, value: Int)
    fun QP_DocumentOperation_Encryption256Bit_getAllowAssembly_0(self: Long): Int
    fun QP_DocumentOperation_Encryption256Bit_setAllowAssembly_0(self: Long, value: Int)
    fun QP_DocumentOperation_Encryption256Bit_getAllowContentExtraction_0(self: Long): Int
    fun QP_DocumentOperation_Encryption256Bit_setAllowContentExtraction_0(self: Long, value: Int)
    fun QP_DocumentOperation_Encryption256Bit_getAllowFillingForms_0(self: Long): Int
    fun QP_DocumentOperation_Encryption256Bit_setAllowFillingForms_0(self: Long, value: Int)
    fun QP_DocumentOperation_Encryption256Bit_getAllowPrinting_0(self: Long): Int
    fun QP_DocumentOperation_Encryption256Bit_setAllowPrinting_0(self: Long, value: Int)
    fun QP_DocumentOperation_Encryption256Bit_getEncryptMetadata_0(self: Long): Int
    fun QP_DocumentOperation_Encryption256Bit_setEncryptMetadata_0(self: Long, value: Int)
    fun QP_DocumentOperation_Encryption40Bit_ctor_0(): Long
    fun QP_DocumentOperation_Encryption40Bit_getAllowAnnotation_0(self: Long): Int
    fun QP_DocumentOperation_Encryption40Bit_setAllowAnnotation_0(self: Long, value: Int)
    fun QP_DocumentOperation_Encryption40Bit_getAllowContentExtraction_0(self: Long): Int
    fun QP_DocumentOperation_Encryption40Bit_setAllowContentExtraction_0(self: Long, value: Int)
    fun QP_DocumentOperation_Encryption40Bit_getAllowModification_0(self: Long): Int
    fun QP_DocumentOperation_Encryption40Bit_setAllowModification_0(self: Long, value: Int)
    fun QP_DocumentOperation_Encryption40Bit_getAllowPrinting_0(self: Long): Int
    fun QP_DocumentOperation_Encryption40Bit_setAllowPrinting_0(self: Long, value: Int)
    fun QP_DocumentOperation_EncryptionBase_ctor_0(): Long
    fun QP_DocumentOperation_EncryptionBase_getOwnerPassword_0(self: Long): Pointer?
    fun QP_DocumentOperation_EncryptionBase_setOwnerPassword_0(self: Long, value: String?)
    fun QP_DocumentOperation_EncryptionBase_getUserPassword_0(self: Long): Pointer?
    fun QP_DocumentOperation_EncryptionBase_setUserPassword_0(self: Long, value: String?)
    fun QP_DocumentOperation_LayerConfiguration_ctor_0(): Long
    fun QP_DocumentOperation_LayerConfiguration_getFilePath_0(self: Long): Pointer?
    fun QP_DocumentOperation_LayerConfiguration_setFilePath_0(self: Long, value: String?)
    fun QP_DocumentOperation_LayerConfiguration_getRepeatSourcePages_0(self: Long): Pointer?
    fun QP_DocumentOperation_LayerConfiguration_setRepeatSourcePages_0(self: Long, value: String?)
    fun QP_DocumentOperation_LayerConfiguration_getSourcePages_0(self: Long): Pointer?
    fun QP_DocumentOperation_LayerConfiguration_setSourcePages_0(self: Long, value: String?)
    fun QP_DocumentOperation_LayerConfiguration_getTargetPages_0(self: Long): Pointer?
    fun QP_DocumentOperation_LayerConfiguration_setTargetPages_0(self: Long, value: String?)
    fun QP_DynamicImageDescriptor_useOriginalImage_0(self: Long, value: Int): Long
    fun QP_DynamicImageDescriptor_withCompressionQuality_0(self: Long, quality: Int): Long
    fun QP_DynamicImageDescriptor_withRasterDpi_0(self: Long, dpi: Int): Long
    fun QP_GridDescriptor_alignCenter_0(self: Long)
    fun QP_GridDescriptor_alignLeft_0(self: Long)
    fun QP_GridDescriptor_alignRight_0(self: Long)
    fun QP_GridDescriptor_alignment_0(self: Long, alignment: Int)
    fun QP_GridDescriptor_columns_0(self: Long, value: Int)
    fun QP_GridDescriptor_horizontalSpacing_0(self: Long, value: Float, unit: Int)
    fun QP_GridDescriptor_item_0(self: Long, columns: Int): Long
    fun QP_GridDescriptor_spacing_0(self: Long, value: Float, unit: Int)
    fun QP_GridDescriptor_verticalSpacing_0(self: Long, value: Float, unit: Int)
    fun QP_ImageDescriptor_fitArea_0(self: Long): Long
    fun QP_ImageDescriptor_fitHeight_0(self: Long): Long
    fun QP_ImageDescriptor_fitUnproportionally_0(self: Long): Long
    fun QP_ImageDescriptor_fitWidth_0(self: Long): Long
    fun QP_ImageDescriptor_useOriginalImage_0(self: Long, value: Int): Long
    fun QP_ImageDescriptor_withCompressionQuality_0(self: Long, quality: Int): Long
    fun QP_ImageDescriptor_withRasterDpi_0(self: Long, dpi: Int): Long
    fun QP_InlinedDescriptor_alignCenter_0(self: Long)
    fun QP_InlinedDescriptor_alignJustify_0(self: Long)
    fun QP_InlinedDescriptor_alignLeft_0(self: Long)
    fun QP_InlinedDescriptor_alignRight_0(self: Long)
    fun QP_InlinedDescriptor_alignSpaceAround_0(self: Long)
    fun QP_InlinedDescriptor_baselineBottom_0(self: Long)
    fun QP_InlinedDescriptor_baselineMiddle_0(self: Long)
    fun QP_InlinedDescriptor_baselineTop_0(self: Long)
    fun QP_InlinedDescriptor_horizontalSpacing_0(self: Long, value: Float, unit: Int)
    fun QP_InlinedDescriptor_item_0(self: Long): Long
    fun QP_InlinedDescriptor_spacing_0(self: Long, value: Float, unit: Int)
    fun QP_InlinedDescriptor_verticalSpacing_0(self: Long, value: Float, unit: Int)
    fun QP_LayersDescriptor_layer_0(self: Long): Long
    fun QP_LayersDescriptor_primaryLayer_0(self: Long): Long
    fun QP_LineDescriptor_lineColor_0(self: Long, color: Long): Long
    fun QP_LineDescriptor_lineDashPattern_0(self: Long, dashPattern: FloatArray?, dashPatternCount: Int, unit: Int): Long
    fun QP_LineDescriptor_lineGradient_0(self: Long, colors: LongArray?, colorsCount: Int): Long
    fun QP_MultiColumnDescriptor_balanceHeight_0(self: Long, enable: Int)
    fun QP_MultiColumnDescriptor_columns_0(self: Long, value: Int)
    fun QP_MultiColumnDescriptor_content_0(self: Long): Long
    fun QP_MultiColumnDescriptor_spacer_0(self: Long): Long
    fun QP_MultiColumnDescriptor_spacing_0(self: Long, value: Float, unit: Int)
    fun QP_PageDescriptor_background_0(self: Long): Long
    fun QP_PageDescriptor_background_1(self: Long, color: Long)
    fun QP_PageDescriptor_content_0(self: Long): Long
    fun QP_PageDescriptor_contentFromLeftToRight_0(self: Long)
    fun QP_PageDescriptor_contentFromRightToLeft_0(self: Long)
    fun QP_PageDescriptor_continuousSize_0(self: Long, width: Float, unit: Int)
    fun QP_PageDescriptor_defaultTextStyle_0(self: Long, textStyle: Long)
    fun QP_PageDescriptor_defaultTextStyle_1(self: Long, handler: NativeCallbackJToJ?)
    fun QP_PageDescriptor_footer_0(self: Long): Long
    fun QP_PageDescriptor_foreground_0(self: Long): Long
    fun QP_PageDescriptor_header_0(self: Long): Long
    fun QP_PageDescriptor_margin_0(self: Long, value: Float, unit: Int)
    fun QP_PageDescriptor_marginBottom_0(self: Long, value: Float, unit: Int)
    fun QP_PageDescriptor_marginHorizontal_0(self: Long, value: Float, unit: Int)
    fun QP_PageDescriptor_marginLeft_0(self: Long, value: Float, unit: Int)
    fun QP_PageDescriptor_marginRight_0(self: Long, value: Float, unit: Int)
    fun QP_PageDescriptor_marginTop_0(self: Long, value: Float, unit: Int)
    fun QP_PageDescriptor_marginVertical_0(self: Long, value: Float, unit: Int)
    fun QP_PageDescriptor_maxSize_0(self: Long, pageSize: Long)
    fun QP_PageDescriptor_minSize_0(self: Long, pageSize: Long)
    fun QP_PageDescriptor_pageColor_0(self: Long, color: Long)
    fun QP_PageDescriptor_size_0(self: Long, pageSize: Long)
    fun QP_PageDescriptor_size_1(self: Long, width: Float, height: Float, unit: Int)
    fun QP_RowDescriptor_autoItem_0(self: Long): Long
    fun QP_RowDescriptor_constantColumn_0(self: Long, size: Float): Long
    fun QP_RowDescriptor_constantItem_0(self: Long, size: Float, unit: Int): Long
    fun QP_RowDescriptor_relativeColumn_0(self: Long, size: Float): Long
    fun QP_RowDescriptor_relativeItem_0(self: Long, size: Float): Long
    fun QP_RowDescriptor_spacing_0(self: Long, spacing: Float, unit: Int)
    fun QP_SvgImageDescriptor_fitArea_0(self: Long): Long
    fun QP_SvgImageDescriptor_fitHeight_0(self: Long): Long
    fun QP_SvgImageDescriptor_fitWidth_0(self: Long): Long
    fun QP_TableCellDescriptor_cell_0(self: Long): Long
    fun QP_TableColumnsDefinitionDescriptor_constantColumn_0(self: Long, width: Float, unit: Int)
    fun QP_TableColumnsDefinitionDescriptor_relativeColumn_0(self: Long, width: Float)
    fun QP_TableDescriptor_cell_0(self: Long): Long
    fun QP_TableDescriptor_columnsDefinition_0(self: Long, handler: NativeCallbackJToV?)
    fun QP_TableDescriptor_extendLastCellsToTableBottom_0(self: Long)
    fun QP_TableDescriptor_footer_0(self: Long, handler: NativeCallbackJToV?)
    fun QP_TableDescriptor_header_0(self: Long, handler: NativeCallbackJToV?)
    fun QP_TextBlockDescriptor_alignCenter_0(self: Long): Long
    fun QP_TextBlockDescriptor_alignEnd_0(self: Long): Long
    fun QP_TextBlockDescriptor_alignLeft_0(self: Long): Long
    fun QP_TextBlockDescriptor_alignRight_0(self: Long): Long
    fun QP_TextBlockDescriptor_alignStart_0(self: Long): Long
    fun QP_TextBlockDescriptor_backgroundColor_0(self: Long, color: Long): Long
    fun QP_TextBlockDescriptor_black_0(self: Long): Long
    fun QP_TextBlockDescriptor_bold_0(self: Long): Long
    fun QP_TextBlockDescriptor_clampLines_0(self: Long, maxLines: Int, ellipsis: String?): Long
    fun QP_TextBlockDescriptor_decorationColor_0(self: Long, color: Long): Long
    fun QP_TextBlockDescriptor_decorationDashed_0(self: Long): Long
    fun QP_TextBlockDescriptor_decorationDotted_0(self: Long): Long
    fun QP_TextBlockDescriptor_decorationDouble_0(self: Long): Long
    fun QP_TextBlockDescriptor_decorationSolid_0(self: Long): Long
    fun QP_TextBlockDescriptor_decorationThickness_0(self: Long, factor: Float): Long
    fun QP_TextBlockDescriptor_decorationWavy_0(self: Long): Long
    fun QP_TextBlockDescriptor_directionAuto_0(self: Long): Long
    fun QP_TextBlockDescriptor_directionFromLeftToRight_0(self: Long): Long
    fun QP_TextBlockDescriptor_directionFromRightToLeft_0(self: Long): Long
    fun QP_TextBlockDescriptor_disableFontFeature_0(self: Long, featureName: String?): Long
    fun QP_TextBlockDescriptor_enableFontFeature_0(self: Long, featureName: String?): Long
    fun QP_TextBlockDescriptor_extraBlack_0(self: Long): Long
    fun QP_TextBlockDescriptor_extraBold_0(self: Long): Long
    fun QP_TextBlockDescriptor_extraLight_0(self: Long): Long
    fun QP_TextBlockDescriptor_fallback_1(self: Long, handler: NativeCallbackJToJ?): Long
    fun QP_TextBlockDescriptor_fallback_0(self: Long, value: Long): Long
    fun QP_TextBlockDescriptor_fontColor_0(self: Long, color: Long): Long
    fun QP_TextBlockDescriptor_fontFamily_0(self: Long, values: Array<out String>?, valuesCount: Int): Long
    fun QP_TextBlockDescriptor_fontSize_0(self: Long, value: Float): Long
    fun QP_TextBlockDescriptor_italic_0(self: Long, value: Int): Long
    fun QP_TextBlockDescriptor_justify_0(self: Long): Long
    fun QP_TextBlockDescriptor_letterSpacing_0(self: Long, factor: Float): Long
    fun QP_TextBlockDescriptor_light_0(self: Long): Long
    fun QP_TextBlockDescriptor_lineHeight_0(self: Long, factorHasValue: Byte, factor: Float): Long
    fun QP_TextBlockDescriptor_medium_0(self: Long): Long
    fun QP_TextBlockDescriptor_normalPosition_0(self: Long): Long
    fun QP_TextBlockDescriptor_normalWeight_0(self: Long): Long
    fun QP_TextBlockDescriptor_overline_0(self: Long, value: Int): Long
    fun QP_TextBlockDescriptor_paragraphFirstLineIndentation_0(self: Long, value: Float, unit: Int): Long
    fun QP_TextBlockDescriptor_paragraphSpacing_0(self: Long, value: Float, unit: Int): Long
    fun QP_TextBlockDescriptor_semiBold_0(self: Long): Long
    fun QP_TextBlockDescriptor_strikethrough_0(self: Long, value: Int): Long
    fun QP_TextBlockDescriptor_style_0(self: Long, style: Long): Long
    fun QP_TextBlockDescriptor_subscript_0(self: Long): Long
    fun QP_TextBlockDescriptor_superscript_0(self: Long): Long
    fun QP_TextBlockDescriptor_thin_0(self: Long): Long
    fun QP_TextBlockDescriptor_underline_0(self: Long, value: Int): Long
    fun QP_TextBlockDescriptor_wordSpacing_0(self: Long, factor: Float): Long
    fun QP_TextBlockDescriptor_wrapAnywhere_0(self: Long, value: Int): Long
    fun QP_TextDescriptor_alignCenter_0(self: Long)
    fun QP_TextDescriptor_alignEnd_0(self: Long)
    fun QP_TextDescriptor_alignLeft_0(self: Long)
    fun QP_TextDescriptor_alignRight_0(self: Long)
    fun QP_TextDescriptor_alignStart_0(self: Long)
    fun QP_TextDescriptor_beginPageNumberOfSection_0(self: Long, sectionName: String?): Long
    fun QP_TextDescriptor_clampLines_0(self: Long, maxLines: Int, ellipsis: String?)
    fun QP_TextDescriptor_currentPageNumber_0(self: Long): Long
    fun QP_TextDescriptor_defaultTextStyle_0(self: Long, style: Long)
    fun QP_TextDescriptor_defaultTextStyle_1(self: Long, style: NativeCallbackJToJ?)
    fun QP_TextDescriptor_element_0(self: Long, alignment: Int): Long
    fun QP_TextDescriptor_element_1(self: Long, handler: NativeCallbackJToV?, alignment: Int)
    fun QP_TextDescriptor_emptyLine_0(self: Long): Long
    fun QP_TextDescriptor_endPageNumberOfSection_0(self: Long, sectionName: String?): Long
    fun QP_TextDescriptor_externalLocation_0(self: Long, text: String?, url: String?, style: Long)
    fun QP_TextDescriptor_hyperlink_0(self: Long, text: String?, url: String?): Long
    fun QP_TextDescriptor_internalLocation_0(self: Long, text: String?, locationName: String?, style: Long)
    fun QP_TextDescriptor_justify_0(self: Long)
    fun QP_TextDescriptor_line_0(self: Long, text: String?): Long
    fun QP_TextDescriptor_pageNumberOfLocation_0(self: Long, sectionName: String?, style: Long)
    fun QP_TextDescriptor_pageNumberWithinSection_0(self: Long, sectionName: String?): Long
    fun QP_TextDescriptor_paragraphFirstLineIndentation_0(self: Long, value: Float, unit: Int)
    fun QP_TextDescriptor_paragraphSpacing_0(self: Long, value: Float, unit: Int)
    fun QP_TextDescriptor_sectionLink_0(self: Long, text: String?, sectionName: String?): Long
    fun QP_TextDescriptor_span_0(self: Long, text: String?): Long
    fun QP_TextDescriptor_span_1(self: Long, text: String?, style: Long)
    fun QP_TextDescriptor_totalPages_0(self: Long): Long
    fun QP_TextDescriptor_totalPagesWithinSection_0(self: Long, sectionName: String?): Long
    fun QP_TextPageNumberDescriptor_backgroundColor_0(self: Long, color: Long): Long
    fun QP_TextPageNumberDescriptor_black_0(self: Long): Long
    fun QP_TextPageNumberDescriptor_bold_0(self: Long): Long
    fun QP_TextPageNumberDescriptor_decorationColor_0(self: Long, color: Long): Long
    fun QP_TextPageNumberDescriptor_decorationDashed_0(self: Long): Long
    fun QP_TextPageNumberDescriptor_decorationDotted_0(self: Long): Long
    fun QP_TextPageNumberDescriptor_decorationDouble_0(self: Long): Long
    fun QP_TextPageNumberDescriptor_decorationSolid_0(self: Long): Long
    fun QP_TextPageNumberDescriptor_decorationThickness_0(self: Long, factor: Float): Long
    fun QP_TextPageNumberDescriptor_decorationWavy_0(self: Long): Long
    fun QP_TextPageNumberDescriptor_directionAuto_0(self: Long): Long
    fun QP_TextPageNumberDescriptor_directionFromLeftToRight_0(self: Long): Long
    fun QP_TextPageNumberDescriptor_directionFromRightToLeft_0(self: Long): Long
    fun QP_TextPageNumberDescriptor_disableFontFeature_0(self: Long, featureName: String?): Long
    fun QP_TextPageNumberDescriptor_enableFontFeature_0(self: Long, featureName: String?): Long
    fun QP_TextPageNumberDescriptor_extraBlack_0(self: Long): Long
    fun QP_TextPageNumberDescriptor_extraBold_0(self: Long): Long
    fun QP_TextPageNumberDescriptor_extraLight_0(self: Long): Long
    fun QP_TextPageNumberDescriptor_fallback_1(self: Long, handler: NativeCallbackJToJ?): Long
    fun QP_TextPageNumberDescriptor_fallback_0(self: Long, value: Long): Long
    fun QP_TextPageNumberDescriptor_fontColor_0(self: Long, color: Long): Long
    fun QP_TextPageNumberDescriptor_fontFamily_0(self: Long, values: Array<out String>?, valuesCount: Int): Long
    fun QP_TextPageNumberDescriptor_fontSize_0(self: Long, value: Float): Long
    fun QP_TextPageNumberDescriptor_format_0(self: Long, formatter: NativeCallbackBIToJ?): Long
    fun QP_TextPageNumberDescriptor_italic_0(self: Long, value: Int): Long
    fun QP_TextPageNumberDescriptor_letterSpacing_0(self: Long, factor: Float): Long
    fun QP_TextPageNumberDescriptor_light_0(self: Long): Long
    fun QP_TextPageNumberDescriptor_lineHeight_0(self: Long, factorHasValue: Byte, factor: Float): Long
    fun QP_TextPageNumberDescriptor_medium_0(self: Long): Long
    fun QP_TextPageNumberDescriptor_normalPosition_0(self: Long): Long
    fun QP_TextPageNumberDescriptor_normalWeight_0(self: Long): Long
    fun QP_TextPageNumberDescriptor_overline_0(self: Long, value: Int): Long
    fun QP_TextPageNumberDescriptor_semiBold_0(self: Long): Long
    fun QP_TextPageNumberDescriptor_strikethrough_0(self: Long, value: Int): Long
    fun QP_TextPageNumberDescriptor_style_0(self: Long, style: Long): Long
    fun QP_TextPageNumberDescriptor_subscript_0(self: Long): Long
    fun QP_TextPageNumberDescriptor_superscript_0(self: Long): Long
    fun QP_TextPageNumberDescriptor_thin_0(self: Long): Long
    fun QP_TextPageNumberDescriptor_underline_0(self: Long, value: Int): Long
    fun QP_TextPageNumberDescriptor_wordSpacing_0(self: Long, factor: Float): Long
    fun QP_TextPageNumberDescriptor_wrapAnywhere_0(self: Long, value: Int): Long
    fun QP_TextSpanDescriptor_backgroundColor_0(self: Long, color: Long): Long
    fun QP_TextSpanDescriptor_black_0(self: Long): Long
    fun QP_TextSpanDescriptor_bold_0(self: Long): Long
    fun QP_TextSpanDescriptor_decorationColor_0(self: Long, color: Long): Long
    fun QP_TextSpanDescriptor_decorationDashed_0(self: Long): Long
    fun QP_TextSpanDescriptor_decorationDotted_0(self: Long): Long
    fun QP_TextSpanDescriptor_decorationDouble_0(self: Long): Long
    fun QP_TextSpanDescriptor_decorationSolid_0(self: Long): Long
    fun QP_TextSpanDescriptor_decorationThickness_0(self: Long, factor: Float): Long
    fun QP_TextSpanDescriptor_decorationWavy_0(self: Long): Long
    fun QP_TextSpanDescriptor_directionAuto_0(self: Long): Long
    fun QP_TextSpanDescriptor_directionFromLeftToRight_0(self: Long): Long
    fun QP_TextSpanDescriptor_directionFromRightToLeft_0(self: Long): Long
    fun QP_TextSpanDescriptor_disableFontFeature_0(self: Long, featureName: String?): Long
    fun QP_TextSpanDescriptor_enableFontFeature_0(self: Long, featureName: String?): Long
    fun QP_TextSpanDescriptor_extraBlack_0(self: Long): Long
    fun QP_TextSpanDescriptor_extraBold_0(self: Long): Long
    fun QP_TextSpanDescriptor_extraLight_0(self: Long): Long
    fun QP_TextSpanDescriptor_fallback_1(self: Long, handler: NativeCallbackJToJ?): Long
    fun QP_TextSpanDescriptor_fallback_0(self: Long, value: Long): Long
    fun QP_TextSpanDescriptor_fontColor_0(self: Long, color: Long): Long
    fun QP_TextSpanDescriptor_fontFamily_0(self: Long, values: Array<out String>?, valuesCount: Int): Long
    fun QP_TextSpanDescriptor_fontSize_0(self: Long, value: Float): Long
    fun QP_TextSpanDescriptor_italic_0(self: Long, value: Int): Long
    fun QP_TextSpanDescriptor_letterSpacing_0(self: Long, factor: Float): Long
    fun QP_TextSpanDescriptor_light_0(self: Long): Long
    fun QP_TextSpanDescriptor_lineHeight_0(self: Long, factorHasValue: Byte, factor: Float): Long
    fun QP_TextSpanDescriptor_medium_0(self: Long): Long
    fun QP_TextSpanDescriptor_normalPosition_0(self: Long): Long
    fun QP_TextSpanDescriptor_normalWeight_0(self: Long): Long
    fun QP_TextSpanDescriptor_overline_0(self: Long, value: Int): Long
    fun QP_TextSpanDescriptor_semiBold_0(self: Long): Long
    fun QP_TextSpanDescriptor_strikethrough_0(self: Long, value: Int): Long
    fun QP_TextSpanDescriptor_style_0(self: Long, style: Long): Long
    fun QP_TextSpanDescriptor_subscript_0(self: Long): Long
    fun QP_TextSpanDescriptor_superscript_0(self: Long): Long
    fun QP_TextSpanDescriptor_thin_0(self: Long): Long
    fun QP_TextSpanDescriptor_underline_0(self: Long, value: Int): Long
    fun QP_TextSpanDescriptor_wordSpacing_0(self: Long, factor: Float): Long
    fun QP_TextSpanDescriptor_wrapAnywhere_0(self: Long, value: Int): Long
    fun QP_Colors_getBlack_0(): Long
    fun QP_Colors_getTransparent_0(): Long
    fun QP_Colors_getWhite_0(): Long
    fun QP_Colors_Amber_getAccent1_0(): Long
    fun QP_Colors_Amber_getAccent2_0(): Long
    fun QP_Colors_Amber_getAccent3_0(): Long
    fun QP_Colors_Amber_getAccent4_0(): Long
    fun QP_Colors_Amber_getDarken1_0(): Long
    fun QP_Colors_Amber_getDarken2_0(): Long
    fun QP_Colors_Amber_getDarken3_0(): Long
    fun QP_Colors_Amber_getDarken4_0(): Long
    fun QP_Colors_Amber_getLighten1_0(): Long
    fun QP_Colors_Amber_getLighten2_0(): Long
    fun QP_Colors_Amber_getLighten3_0(): Long
    fun QP_Colors_Amber_getLighten4_0(): Long
    fun QP_Colors_Amber_getLighten5_0(): Long
    fun QP_Colors_Amber_getMedium_0(): Long
    fun QP_Colors_Blue_getAccent1_0(): Long
    fun QP_Colors_Blue_getAccent2_0(): Long
    fun QP_Colors_Blue_getAccent3_0(): Long
    fun QP_Colors_Blue_getAccent4_0(): Long
    fun QP_Colors_Blue_getDarken1_0(): Long
    fun QP_Colors_Blue_getDarken2_0(): Long
    fun QP_Colors_Blue_getDarken3_0(): Long
    fun QP_Colors_Blue_getDarken4_0(): Long
    fun QP_Colors_Blue_getLighten1_0(): Long
    fun QP_Colors_Blue_getLighten2_0(): Long
    fun QP_Colors_Blue_getLighten3_0(): Long
    fun QP_Colors_Blue_getLighten4_0(): Long
    fun QP_Colors_Blue_getLighten5_0(): Long
    fun QP_Colors_Blue_getMedium_0(): Long
    fun QP_Colors_BlueGrey_getDarken1_0(): Long
    fun QP_Colors_BlueGrey_getDarken2_0(): Long
    fun QP_Colors_BlueGrey_getDarken3_0(): Long
    fun QP_Colors_BlueGrey_getDarken4_0(): Long
    fun QP_Colors_BlueGrey_getLighten1_0(): Long
    fun QP_Colors_BlueGrey_getLighten2_0(): Long
    fun QP_Colors_BlueGrey_getLighten3_0(): Long
    fun QP_Colors_BlueGrey_getLighten4_0(): Long
    fun QP_Colors_BlueGrey_getLighten5_0(): Long
    fun QP_Colors_BlueGrey_getMedium_0(): Long
    fun QP_Colors_Brown_getDarken1_0(): Long
    fun QP_Colors_Brown_getDarken2_0(): Long
    fun QP_Colors_Brown_getDarken3_0(): Long
    fun QP_Colors_Brown_getDarken4_0(): Long
    fun QP_Colors_Brown_getLighten1_0(): Long
    fun QP_Colors_Brown_getLighten2_0(): Long
    fun QP_Colors_Brown_getLighten3_0(): Long
    fun QP_Colors_Brown_getLighten4_0(): Long
    fun QP_Colors_Brown_getLighten5_0(): Long
    fun QP_Colors_Brown_getMedium_0(): Long
    fun QP_Colors_Cyan_getAccent1_0(): Long
    fun QP_Colors_Cyan_getAccent2_0(): Long
    fun QP_Colors_Cyan_getAccent3_0(): Long
    fun QP_Colors_Cyan_getAccent4_0(): Long
    fun QP_Colors_Cyan_getDarken1_0(): Long
    fun QP_Colors_Cyan_getDarken2_0(): Long
    fun QP_Colors_Cyan_getDarken3_0(): Long
    fun QP_Colors_Cyan_getDarken4_0(): Long
    fun QP_Colors_Cyan_getLighten1_0(): Long
    fun QP_Colors_Cyan_getLighten2_0(): Long
    fun QP_Colors_Cyan_getLighten3_0(): Long
    fun QP_Colors_Cyan_getLighten4_0(): Long
    fun QP_Colors_Cyan_getLighten5_0(): Long
    fun QP_Colors_Cyan_getMedium_0(): Long
    fun QP_Colors_DeepOrange_getAccent1_0(): Long
    fun QP_Colors_DeepOrange_getAccent2_0(): Long
    fun QP_Colors_DeepOrange_getAccent3_0(): Long
    fun QP_Colors_DeepOrange_getAccent4_0(): Long
    fun QP_Colors_DeepOrange_getDarken1_0(): Long
    fun QP_Colors_DeepOrange_getDarken2_0(): Long
    fun QP_Colors_DeepOrange_getDarken3_0(): Long
    fun QP_Colors_DeepOrange_getDarken4_0(): Long
    fun QP_Colors_DeepOrange_getLighten1_0(): Long
    fun QP_Colors_DeepOrange_getLighten2_0(): Long
    fun QP_Colors_DeepOrange_getLighten3_0(): Long
    fun QP_Colors_DeepOrange_getLighten4_0(): Long
    fun QP_Colors_DeepOrange_getLighten5_0(): Long
    fun QP_Colors_DeepOrange_getMedium_0(): Long
    fun QP_Colors_DeepPurple_getAccent1_0(): Long
    fun QP_Colors_DeepPurple_getAccent2_0(): Long
    fun QP_Colors_DeepPurple_getAccent3_0(): Long
    fun QP_Colors_DeepPurple_getAccent4_0(): Long
    fun QP_Colors_DeepPurple_getDarken1_0(): Long
    fun QP_Colors_DeepPurple_getDarken2_0(): Long
    fun QP_Colors_DeepPurple_getDarken3_0(): Long
    fun QP_Colors_DeepPurple_getDarken4_0(): Long
    fun QP_Colors_DeepPurple_getLighten1_0(): Long
    fun QP_Colors_DeepPurple_getLighten2_0(): Long
    fun QP_Colors_DeepPurple_getLighten3_0(): Long
    fun QP_Colors_DeepPurple_getLighten4_0(): Long
    fun QP_Colors_DeepPurple_getLighten5_0(): Long
    fun QP_Colors_DeepPurple_getMedium_0(): Long
    fun QP_Colors_Green_getAccent1_0(): Long
    fun QP_Colors_Green_getAccent2_0(): Long
    fun QP_Colors_Green_getAccent3_0(): Long
    fun QP_Colors_Green_getAccent4_0(): Long
    fun QP_Colors_Green_getDarken1_0(): Long
    fun QP_Colors_Green_getDarken2_0(): Long
    fun QP_Colors_Green_getDarken3_0(): Long
    fun QP_Colors_Green_getDarken4_0(): Long
    fun QP_Colors_Green_getLighten1_0(): Long
    fun QP_Colors_Green_getLighten2_0(): Long
    fun QP_Colors_Green_getLighten3_0(): Long
    fun QP_Colors_Green_getLighten4_0(): Long
    fun QP_Colors_Green_getLighten5_0(): Long
    fun QP_Colors_Green_getMedium_0(): Long
    fun QP_Colors_Grey_getDarken1_0(): Long
    fun QP_Colors_Grey_getDarken2_0(): Long
    fun QP_Colors_Grey_getDarken3_0(): Long
    fun QP_Colors_Grey_getDarken4_0(): Long
    fun QP_Colors_Grey_getLighten1_0(): Long
    fun QP_Colors_Grey_getLighten2_0(): Long
    fun QP_Colors_Grey_getLighten3_0(): Long
    fun QP_Colors_Grey_getLighten4_0(): Long
    fun QP_Colors_Grey_getLighten5_0(): Long
    fun QP_Colors_Grey_getMedium_0(): Long
    fun QP_Colors_Indigo_getAccent1_0(): Long
    fun QP_Colors_Indigo_getAccent2_0(): Long
    fun QP_Colors_Indigo_getAccent3_0(): Long
    fun QP_Colors_Indigo_getAccent4_0(): Long
    fun QP_Colors_Indigo_getDarken1_0(): Long
    fun QP_Colors_Indigo_getDarken2_0(): Long
    fun QP_Colors_Indigo_getDarken3_0(): Long
    fun QP_Colors_Indigo_getDarken4_0(): Long
    fun QP_Colors_Indigo_getLighten1_0(): Long
    fun QP_Colors_Indigo_getLighten2_0(): Long
    fun QP_Colors_Indigo_getLighten3_0(): Long
    fun QP_Colors_Indigo_getLighten4_0(): Long
    fun QP_Colors_Indigo_getLighten5_0(): Long
    fun QP_Colors_Indigo_getMedium_0(): Long
    fun QP_Colors_LightBlue_getAccent1_0(): Long
    fun QP_Colors_LightBlue_getAccent2_0(): Long
    fun QP_Colors_LightBlue_getAccent3_0(): Long
    fun QP_Colors_LightBlue_getAccent4_0(): Long
    fun QP_Colors_LightBlue_getDarken1_0(): Long
    fun QP_Colors_LightBlue_getDarken2_0(): Long
    fun QP_Colors_LightBlue_getDarken3_0(): Long
    fun QP_Colors_LightBlue_getDarken4_0(): Long
    fun QP_Colors_LightBlue_getLighten1_0(): Long
    fun QP_Colors_LightBlue_getLighten2_0(): Long
    fun QP_Colors_LightBlue_getLighten3_0(): Long
    fun QP_Colors_LightBlue_getLighten4_0(): Long
    fun QP_Colors_LightBlue_getLighten5_0(): Long
    fun QP_Colors_LightBlue_getMedium_0(): Long
    fun QP_Colors_LightGreen_getAccent1_0(): Long
    fun QP_Colors_LightGreen_getAccent2_0(): Long
    fun QP_Colors_LightGreen_getAccent3_0(): Long
    fun QP_Colors_LightGreen_getAccent4_0(): Long
    fun QP_Colors_LightGreen_getDarken1_0(): Long
    fun QP_Colors_LightGreen_getDarken2_0(): Long
    fun QP_Colors_LightGreen_getDarken3_0(): Long
    fun QP_Colors_LightGreen_getDarken4_0(): Long
    fun QP_Colors_LightGreen_getLighten1_0(): Long
    fun QP_Colors_LightGreen_getLighten2_0(): Long
    fun QP_Colors_LightGreen_getLighten3_0(): Long
    fun QP_Colors_LightGreen_getLighten4_0(): Long
    fun QP_Colors_LightGreen_getLighten5_0(): Long
    fun QP_Colors_LightGreen_getMedium_0(): Long
    fun QP_Colors_Lime_getAccent1_0(): Long
    fun QP_Colors_Lime_getAccent2_0(): Long
    fun QP_Colors_Lime_getAccent3_0(): Long
    fun QP_Colors_Lime_getAccent4_0(): Long
    fun QP_Colors_Lime_getDarken1_0(): Long
    fun QP_Colors_Lime_getDarken2_0(): Long
    fun QP_Colors_Lime_getDarken3_0(): Long
    fun QP_Colors_Lime_getDarken4_0(): Long
    fun QP_Colors_Lime_getLighten1_0(): Long
    fun QP_Colors_Lime_getLighten2_0(): Long
    fun QP_Colors_Lime_getLighten3_0(): Long
    fun QP_Colors_Lime_getLighten4_0(): Long
    fun QP_Colors_Lime_getLighten5_0(): Long
    fun QP_Colors_Lime_getMedium_0(): Long
    fun QP_Colors_Orange_getAccent1_0(): Long
    fun QP_Colors_Orange_getAccent2_0(): Long
    fun QP_Colors_Orange_getAccent3_0(): Long
    fun QP_Colors_Orange_getAccent4_0(): Long
    fun QP_Colors_Orange_getDarken1_0(): Long
    fun QP_Colors_Orange_getDarken2_0(): Long
    fun QP_Colors_Orange_getDarken3_0(): Long
    fun QP_Colors_Orange_getDarken4_0(): Long
    fun QP_Colors_Orange_getLighten1_0(): Long
    fun QP_Colors_Orange_getLighten2_0(): Long
    fun QP_Colors_Orange_getLighten3_0(): Long
    fun QP_Colors_Orange_getLighten4_0(): Long
    fun QP_Colors_Orange_getLighten5_0(): Long
    fun QP_Colors_Orange_getMedium_0(): Long
    fun QP_Colors_Pink_getAccent1_0(): Long
    fun QP_Colors_Pink_getAccent2_0(): Long
    fun QP_Colors_Pink_getAccent3_0(): Long
    fun QP_Colors_Pink_getAccent4_0(): Long
    fun QP_Colors_Pink_getDarken1_0(): Long
    fun QP_Colors_Pink_getDarken2_0(): Long
    fun QP_Colors_Pink_getDarken3_0(): Long
    fun QP_Colors_Pink_getDarken4_0(): Long
    fun QP_Colors_Pink_getLighten1_0(): Long
    fun QP_Colors_Pink_getLighten2_0(): Long
    fun QP_Colors_Pink_getLighten3_0(): Long
    fun QP_Colors_Pink_getLighten4_0(): Long
    fun QP_Colors_Pink_getLighten5_0(): Long
    fun QP_Colors_Pink_getMedium_0(): Long
    fun QP_Colors_Purple_getAccent1_0(): Long
    fun QP_Colors_Purple_getAccent2_0(): Long
    fun QP_Colors_Purple_getAccent3_0(): Long
    fun QP_Colors_Purple_getAccent4_0(): Long
    fun QP_Colors_Purple_getDarken1_0(): Long
    fun QP_Colors_Purple_getDarken2_0(): Long
    fun QP_Colors_Purple_getDarken3_0(): Long
    fun QP_Colors_Purple_getDarken4_0(): Long
    fun QP_Colors_Purple_getLighten1_0(): Long
    fun QP_Colors_Purple_getLighten2_0(): Long
    fun QP_Colors_Purple_getLighten3_0(): Long
    fun QP_Colors_Purple_getLighten4_0(): Long
    fun QP_Colors_Purple_getLighten5_0(): Long
    fun QP_Colors_Purple_getMedium_0(): Long
    fun QP_Colors_Red_getAccent1_0(): Long
    fun QP_Colors_Red_getAccent2_0(): Long
    fun QP_Colors_Red_getAccent3_0(): Long
    fun QP_Colors_Red_getAccent4_0(): Long
    fun QP_Colors_Red_getDarken1_0(): Long
    fun QP_Colors_Red_getDarken2_0(): Long
    fun QP_Colors_Red_getDarken3_0(): Long
    fun QP_Colors_Red_getDarken4_0(): Long
    fun QP_Colors_Red_getLighten1_0(): Long
    fun QP_Colors_Red_getLighten2_0(): Long
    fun QP_Colors_Red_getLighten3_0(): Long
    fun QP_Colors_Red_getLighten4_0(): Long
    fun QP_Colors_Red_getLighten5_0(): Long
    fun QP_Colors_Red_getMedium_0(): Long
    fun QP_Colors_Teal_getAccent1_0(): Long
    fun QP_Colors_Teal_getAccent2_0(): Long
    fun QP_Colors_Teal_getAccent3_0(): Long
    fun QP_Colors_Teal_getAccent4_0(): Long
    fun QP_Colors_Teal_getDarken1_0(): Long
    fun QP_Colors_Teal_getDarken2_0(): Long
    fun QP_Colors_Teal_getDarken3_0(): Long
    fun QP_Colors_Teal_getDarken4_0(): Long
    fun QP_Colors_Teal_getLighten1_0(): Long
    fun QP_Colors_Teal_getLighten2_0(): Long
    fun QP_Colors_Teal_getLighten3_0(): Long
    fun QP_Colors_Teal_getLighten4_0(): Long
    fun QP_Colors_Teal_getLighten5_0(): Long
    fun QP_Colors_Teal_getMedium_0(): Long
    fun QP_Colors_Yellow_getAccent1_0(): Long
    fun QP_Colors_Yellow_getAccent2_0(): Long
    fun QP_Colors_Yellow_getAccent3_0(): Long
    fun QP_Colors_Yellow_getAccent4_0(): Long
    fun QP_Colors_Yellow_getDarken1_0(): Long
    fun QP_Colors_Yellow_getDarken2_0(): Long
    fun QP_Colors_Yellow_getDarken3_0(): Long
    fun QP_Colors_Yellow_getDarken4_0(): Long
    fun QP_Colors_Yellow_getLighten1_0(): Long
    fun QP_Colors_Yellow_getLighten2_0(): Long
    fun QP_Colors_Yellow_getLighten3_0(): Long
    fun QP_Colors_Yellow_getLighten4_0(): Long
    fun QP_Colors_Yellow_getLighten5_0(): Long
    fun QP_Colors_Yellow_getMedium_0(): Long
    fun QP_FontFeatures_characterVariant_0(value: Int): Pointer?
    fun QP_FontFeatures_stylisticSet_0(value: Int): Pointer?
    fun QP_PageSize_ctor_0(width: Float, height: Float, unit: Int): Long
    fun QP_PageSize_getHeight_0(self: Long): Float
    fun QP_PageSize_getWidth_0(self: Long): Float
    fun QP_PageSize_landscape_0(self: Long): Long
    fun QP_PageSize_portrait_0(self: Long): Long
    fun QP_PageSize_toSize_0(self: Long): Long
    fun QP_PageSizes_getA0_0(): Long
    fun QP_PageSizes_getA1_0(): Long
    fun QP_PageSizes_getA10_0(): Long
    fun QP_PageSizes_getA2_0(): Long
    fun QP_PageSizes_getA3_0(): Long
    fun QP_PageSizes_getA4_0(): Long
    fun QP_PageSizes_getA5_0(): Long
    fun QP_PageSizes_getA6_0(): Long
    fun QP_PageSizes_getA7_0(): Long
    fun QP_PageSizes_getA8_0(): Long
    fun QP_PageSizes_getA9_0(): Long
    fun QP_PageSizes_getARCH_A_0(): Long
    fun QP_PageSizes_getARCH_B_0(): Long
    fun QP_PageSizes_getARCH_C_0(): Long
    fun QP_PageSizes_getARCH_D_0(): Long
    fun QP_PageSizes_getARCH_E_0(): Long
    fun QP_PageSizes_getARCH_E1_0(): Long
    fun QP_PageSizes_getARCH_E2_0(): Long
    fun QP_PageSizes_getARCH_E3_0(): Long
    fun QP_PageSizes_getB0_0(): Long
    fun QP_PageSizes_getB1_0(): Long
    fun QP_PageSizes_getB10_0(): Long
    fun QP_PageSizes_getB2_0(): Long
    fun QP_PageSizes_getB3_0(): Long
    fun QP_PageSizes_getB4_0(): Long
    fun QP_PageSizes_getB5_0(): Long
    fun QP_PageSizes_getB6_0(): Long
    fun QP_PageSizes_getB7_0(): Long
    fun QP_PageSizes_getB8_0(): Long
    fun QP_PageSizes_getB9_0(): Long
    fun QP_PageSizes_getC0_0(): Long
    fun QP_PageSizes_getC1_0(): Long
    fun QP_PageSizes_getC10_0(): Long
    fun QP_PageSizes_getC2_0(): Long
    fun QP_PageSizes_getC3_0(): Long
    fun QP_PageSizes_getC4_0(): Long
    fun QP_PageSizes_getC5_0(): Long
    fun QP_PageSizes_getC6_0(): Long
    fun QP_PageSizes_getC7_0(): Long
    fun QP_PageSizes_getC8_0(): Long
    fun QP_PageSizes_getC9_0(): Long
    fun QP_PageSizes_getEnv10_0(): Long
    fun QP_PageSizes_getEnvC4_0(): Long
    fun QP_PageSizes_getEnvDL_0(): Long
    fun QP_PageSizes_getExecutive_0(): Long
    fun QP_PageSizes_getLedger_0(): Long
    fun QP_PageSizes_getLegal_0(): Long
    fun QP_PageSizes_getLetter_0(): Long
    fun QP_PageSizes_getPostcard_0(): Long
    fun QP_PageSizes_getTabloid_0(): Long
    fun QP_Placeholders_backgroundColor_0(): Long
    fun QP_Placeholders_color_0(): Long
    fun QP_Placeholders_dateTime_0(): Pointer?
    fun QP_Placeholders_decimal_0(): Pointer?
    fun QP_Placeholders_email_0(): Pointer?
    fun QP_Placeholders_image_0(size: Long, outData: PointerByReference, outLength: IntByReference)
    fun QP_Placeholders_image_1(width: Int, height: Int, outData: PointerByReference, outLength: IntByReference)
    fun QP_Placeholders_integer_0(): Pointer?
    fun QP_Placeholders_label_0(): Pointer?
    fun QP_Placeholders_longDate_0(): Pointer?
    fun QP_Placeholders_loremIpsum_0(): Pointer?
    fun QP_Placeholders_name_0(): Pointer?
    fun QP_Placeholders_paragraph_0(): Pointer?
    fun QP_Placeholders_paragraphs_0(): Pointer?
    fun QP_Placeholders_percent_0(): Pointer?
    fun QP_Placeholders_phoneNumber_0(): Pointer?
    fun QP_Placeholders_price_0(): Pointer?
    fun QP_Placeholders_question_0(): Pointer?
    fun QP_Placeholders_sentence_0(): Pointer?
    fun QP_Placeholders_shortDate_0(): Pointer?
    fun QP_Placeholders_time_0(): Pointer?
    fun QP_Placeholders_webpageUrl_0(): Pointer?
    fun QP_BoxShadowStyle_ctor_0(): Long
    fun QP_BoxShadowStyle_getBlur_0(self: Long): Float
    fun QP_BoxShadowStyle_setBlur_0(self: Long, value: Float)
    fun QP_BoxShadowStyle_getColor_0(self: Long): Long
    fun QP_BoxShadowStyle_setColor_0(self: Long, value: Long)
    fun QP_BoxShadowStyle_getOffsetX_0(self: Long): Float
    fun QP_BoxShadowStyle_setOffsetX_0(self: Long, value: Float)
    fun QP_BoxShadowStyle_getOffsetY_0(self: Long): Float
    fun QP_BoxShadowStyle_setOffsetY_0(self: Long, value: Float)
    fun QP_BoxShadowStyle_getSpread_0(self: Long): Float
    fun QP_BoxShadowStyle_setSpread_0(self: Long, value: Float)
    fun QP_Color_ctor_0(hex: Int): Long
    fun QP_Color_getAlpha_0(self: Long): Byte
    fun QP_Color_getBlue_0(self: Long): Byte
    fun QP_Color_getGreen_0(self: Long): Byte
    fun QP_Color_getHex_0(self: Long): Int
    fun QP_Color_getRed_0(self: Long): Byte
    fun QP_Color_toString_0(self: Long): Pointer?
    fun QP_Color_toUInt32_0(self: Long): Int
    fun QP_Color_withAlpha_1(self: Long, alpha: Float): Long
    fun QP_Color_withAlpha_0(self: Long, alpha: Byte): Long
    fun QP_Color_from_0(hex: String?): Long
    fun QP_Color_from_1(hex: Int): Long
    fun QP_Color_fromARGB_0(alpha: Byte, red: Byte, green: Byte, blue: Byte): Long
    fun QP_Color_fromHex_0(hex: String?): Long
    fun QP_Color_fromRGB_0(red: Byte, green: Byte, blue: Byte): Long
    fun QP_DocumentMetadata_ctor_0(): Long
    fun QP_DocumentMetadata_getApplyCaching_0(self: Long): Int
    fun QP_DocumentMetadata_setApplyCaching_0(self: Long, value: Int)
    fun QP_DocumentMetadata_getApplyDebugging_0(self: Long): Int
    fun QP_DocumentMetadata_setApplyDebugging_0(self: Long, value: Int)
    fun QP_DocumentMetadata_getAuthor_0(self: Long): Pointer?
    fun QP_DocumentMetadata_setAuthor_0(self: Long, value: String?)
    fun QP_DocumentMetadata_getCreationDate_0(self: Long): Pointer?
    fun QP_DocumentMetadata_setCreationDate_0(self: Long, value: String?)
    fun QP_DocumentMetadata_getCreator_0(self: Long): Pointer?
    fun QP_DocumentMetadata_setCreator_0(self: Long, value: String?)
    fun QP_DocumentMetadata_getDocumentLayoutExceptionThreshold_0(self: Long): Int
    fun QP_DocumentMetadata_setDocumentLayoutExceptionThreshold_0(self: Long, value: Int)
    fun QP_DocumentMetadata_getImageQuality_0(self: Long, outHasValue: ByteByReference): Int
    fun QP_DocumentMetadata_setImageQuality_0(self: Long, valueHasValue: Byte, value: Int)
    fun QP_DocumentMetadata_getKeywords_0(self: Long): Pointer?
    fun QP_DocumentMetadata_setKeywords_0(self: Long, value: String?)
    fun QP_DocumentMetadata_getLanguage_0(self: Long): Pointer?
    fun QP_DocumentMetadata_setLanguage_0(self: Long, value: String?)
    fun QP_DocumentMetadata_getModifiedDate_0(self: Long): Pointer?
    fun QP_DocumentMetadata_setModifiedDate_0(self: Long, value: String?)
    fun QP_DocumentMetadata_getPdfA_0(self: Long, outHasValue: ByteByReference): Int
    fun QP_DocumentMetadata_setPdfA_0(self: Long, valueHasValue: Byte, value: Int)
    fun QP_DocumentMetadata_getProducer_0(self: Long): Pointer?
    fun QP_DocumentMetadata_setProducer_0(self: Long, value: String?)
    fun QP_DocumentMetadata_getRasterDpi_0(self: Long, outHasValue: ByteByReference): Int
    fun QP_DocumentMetadata_setRasterDpi_0(self: Long, valueHasValue: Byte, value: Int)
    fun QP_DocumentMetadata_getSubject_0(self: Long): Pointer?
    fun QP_DocumentMetadata_setSubject_0(self: Long, value: String?)
    fun QP_DocumentMetadata_getTitle_0(self: Long): Pointer?
    fun QP_DocumentMetadata_setTitle_0(self: Long, value: String?)
    fun QP_DocumentMetadata_getDefault_0(): Long
    fun QP_DocumentSettings_ctor_0(): Long
    fun QP_DocumentSettings_getCompressDocument_0(self: Long): Int
    fun QP_DocumentSettings_setCompressDocument_0(self: Long, value: Int)
    fun QP_DocumentSettings_getContentDirection_0(self: Long): Int
    fun QP_DocumentSettings_setContentDirection_0(self: Long, value: Int)
    fun QP_DocumentSettings_getImageCompressionQuality_0(self: Long): Int
    fun QP_DocumentSettings_setImageCompressionQuality_0(self: Long, value: Int)
    fun QP_DocumentSettings_getImageRasterDpi_0(self: Long): Int
    fun QP_DocumentSettings_setImageRasterDpi_0(self: Long, value: Int)
    fun QP_DocumentSettings_getPdfA_0(self: Long): Int
    fun QP_DocumentSettings_setPdfA_0(self: Long, value: Int)
    fun QP_DocumentSettings_getPDFA_Conformance_0(self: Long): Int
    fun QP_DocumentSettings_setPDFA_Conformance_0(self: Long, value: Int)
    fun QP_DocumentSettings_getPDFUA_Conformance_0(self: Long): Int
    fun QP_DocumentSettings_setPDFUA_Conformance_0(self: Long, value: Int)
    fun QP_DocumentSettings_getDefault_0(): Long
    fun QP_DynamicComponentComposeResult_ctor_0(): Long
    fun QP_DynamicComponentComposeResult_getContent_0(self: Long): Long
    fun QP_DynamicComponentComposeResult_setContent_0(self: Long, value: Long)
    fun QP_DynamicComponentComposeResult_getHasMoreContent_0(self: Long): Int
    fun QP_DynamicComponentComposeResult_setHasMoreContent_0(self: Long, value: Int)
    fun QP_EmptyContainer_create_0(): Long
    fun QP_IContainer_getChild_0(self: Long): Long
    fun QP_IContainer_setChild_0(self: Long, value: Long)
    fun QP_IContainer_alignBottom_0(self: Long): Long
    fun QP_IContainer_alignCenter_0(self: Long): Long
    fun QP_IContainer_alignLeft_0(self: Long): Long
    fun QP_IContainer_alignMiddle_0(self: Long): Long
    fun QP_IContainer_alignRight_0(self: Long): Long
    fun QP_IContainer_alignTop_0(self: Long): Long
    fun QP_IContainer_aspectRatio_0(self: Long, ratio: Float, option: Int): Long
    fun QP_IContainer_background_0(self: Long, color: Long): Long
    fun QP_IContainer_backgroundLinearGradient_0(self: Long, angle: Float, colors: LongArray?, colorsCount: Int): Long
    fun QP_IContainer_border_0(self: Long, all: Float, color: Long): Long
    fun QP_IContainer_border_1(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_borderAlignmentInside_0(self: Long): Long
    fun QP_IContainer_borderAlignmentMiddle_0(self: Long): Long
    fun QP_IContainer_borderAlignmentOutside_0(self: Long): Long
    fun QP_IContainer_borderBottom_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_borderColor_0(self: Long, color: Long): Long
    fun QP_IContainer_borderHorizontal_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_borderLeft_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_borderLinearGradient_0(self: Long, angle: Float, colors: LongArray?, colorsCount: Int): Long
    fun QP_IContainer_borderRight_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_borderTop_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_borderVertical_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_box_0(self: Long): Long
    fun QP_IContainer_captureContentPosition_0(self: Long, id: String?): Long
    fun QP_IContainer_column_0(self: Long, handler: NativeCallbackJToV?)
    fun QP_IContainer_component_1(self: Long, component: Long)
    fun QP_IContainer_container_0(self: Long): Long
    fun QP_IContainer_contentFromLeftToRight_0(self: Long): Long
    fun QP_IContainer_contentFromRightToLeft_0(self: Long): Long
    fun QP_IContainer_cornerRadius_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_cornerRadiusBottomLeft_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_cornerRadiusBottomRight_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_cornerRadiusTopLeft_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_cornerRadiusTopRight_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_debugArea_0(self: Long, text: String?, color: Long): Long
    fun QP_IContainer_debugPointer_0(self: Long, label: String?): Long
    fun QP_IContainer_decoration_0(self: Long, handler: NativeCallbackJToV?)
    fun QP_IContainer_defaultTextStyle_0(self: Long, textStyle: Long): Long
    fun QP_IContainer_defaultTextStyle_1(self: Long, handler: NativeCallbackJToJ?): Long
    fun QP_IContainer_dynamic_0(self: Long, dynamicElement: Long)
    fun QP_IContainer_element_0(self: Long, child: Long)
    fun QP_IContainer_element_1(self: Long, child: Long)
    fun QP_IContainer_element_2(self: Long, handler: NativeCallbackJToV?)
    fun QP_IContainer_ensureSpace_0(self: Long, minHeight: Float): Long
    fun QP_IContainer_extend_0(self: Long): Long
    fun QP_IContainer_extendHorizontal_0(self: Long): Long
    fun QP_IContainer_extendVertical_0(self: Long): Long
    fun QP_IContainer_externalLink_0(self: Long, url: String?): Long
    fun QP_IContainer_flipHorizontal_0(self: Long): Long
    fun QP_IContainer_flipOver_0(self: Long): Long
    fun QP_IContainer_flipVertical_0(self: Long): Long
    fun QP_IContainer_grid_0(self: Long, handler: NativeCallbackJToV?)
    fun QP_IContainer_height_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_hyperlink_0(self: Long, url: String?): Long
    fun QP_IContainer_image_0(self: Long, dynamicImageSource: NativeCallbackJToJ?): Long
    fun QP_IContainer_image_1(self: Long, image: Long): Long
    fun QP_IContainer_image_2(self: Long, imageData: ByteArray?, imageDataLength: Int): Long
    fun QP_IContainer_image_8(self: Long, filePath: String?): Long
    fun QP_IContainer_image_3(self: Long, imageData: ByteArray?, imageDataLength: Int, scaling: Int)
    fun QP_IContainer_image_9(self: Long, filePath: String?, scaling: Int)
    fun QP_IContainer_inlined_0(self: Long, handler: NativeCallbackJToV?)
    fun QP_IContainer_internalLink_0(self: Long, locationName: String?): Long
    fun QP_IContainer_layers_0(self: Long, handler: NativeCallbackJToV?)
    fun QP_IContainer_lazy_0(self: Long, contentBuilder: NativeCallbackJToV?)
    fun QP_IContainer_lazyWithCache_0(self: Long, contentBuilder: NativeCallbackJToV?)
    fun QP_IContainer_lineHorizontal_0(self: Long, thickness: Float, unit: Int): Long
    fun QP_IContainer_lineVertical_0(self: Long, thickness: Float, unit: Int): Long
    fun QP_IContainer_location_0(self: Long, locationName: String?): Long
    fun QP_IContainer_maxHeight_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_maxWidth_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_minHeight_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_minWidth_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_minimalBox_0(self: Long): Long
    fun QP_IContainer_multiColumn_0(self: Long, handler: NativeCallbackJToV?)
    fun QP_IContainer_offsetX_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_offsetY_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_padding_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_paddingBottom_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_paddingHorizontal_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_paddingLeft_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_paddingRight_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_paddingTop_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_paddingVertical_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_pageBreak_0(self: Long)
    fun QP_IContainer_placeholder_0(self: Long, text: String?)
    fun QP_IContainer_preventPageBreak_0(self: Long): Long
    fun QP_IContainer_repeat_0(self: Long): Long
    fun QP_IContainer_rotate_0(self: Long, angle: Float): Long
    fun QP_IContainer_rotateLeft_0(self: Long): Long
    fun QP_IContainer_rotateRight_0(self: Long): Long
    fun QP_IContainer_row_0(self: Long, handler: NativeCallbackJToV?)
    fun QP_IContainer_scale_0(self: Long, factor: Float): Long
    fun QP_IContainer_scaleHorizontal_0(self: Long, factor: Float): Long
    fun QP_IContainer_scaleToFit_0(self: Long): Long
    fun QP_IContainer_scaleVertical_0(self: Long, factor: Float): Long
    fun QP_IContainer_section_0(self: Long, sectionName: String?): Long
    fun QP_IContainer_sectionLink_0(self: Long, sectionName: String?): Long
    fun QP_IContainer_semanticArticle_0(self: Long): Long
    fun QP_IContainer_semanticBlockQuotation_0(self: Long): Long
    fun QP_IContainer_semanticCaption_0(self: Long): Long
    fun QP_IContainer_semanticCode_0(self: Long): Long
    fun QP_IContainer_semanticDivision_0(self: Long): Long
    fun QP_IContainer_semanticFigure_0(self: Long, alternativeText: String?): Long
    fun QP_IContainer_semanticFormula_0(self: Long, alternativeText: String?): Long
    fun QP_IContainer_semanticHeader1_0(self: Long): Long
    fun QP_IContainer_semanticHeader2_0(self: Long): Long
    fun QP_IContainer_semanticHeader3_0(self: Long): Long
    fun QP_IContainer_semanticHeader4_0(self: Long): Long
    fun QP_IContainer_semanticHeader5_0(self: Long): Long
    fun QP_IContainer_semanticHeader6_0(self: Long): Long
    fun QP_IContainer_semanticIgnore_0(self: Long): Long
    fun QP_IContainer_semanticImage_0(self: Long, alternativeText: String?): Long
    fun QP_IContainer_semanticIndex_0(self: Long): Long
    fun QP_IContainer_semanticLanguage_0(self: Long, language: String?): Long
    fun QP_IContainer_semanticLink_0(self: Long, alternativeText: String?): Long
    fun QP_IContainer_semanticList_0(self: Long): Long
    fun QP_IContainer_semanticListItem_0(self: Long): Long
    fun QP_IContainer_semanticListItemBody_0(self: Long): Long
    fun QP_IContainer_semanticListLabel_0(self: Long): Long
    fun QP_IContainer_semanticParagraph_0(self: Long): Long
    fun QP_IContainer_semanticQuote_0(self: Long): Long
    fun QP_IContainer_semanticSection_0(self: Long): Long
    fun QP_IContainer_semanticSpan_0(self: Long, alternativeText: String?): Long
    fun QP_IContainer_semanticTable_0(self: Long): Long
    fun QP_IContainer_semanticTableOfContents_0(self: Long): Long
    fun QP_IContainer_semanticTableOfContentsItem_0(self: Long): Long
    fun QP_IContainer_shadow_0(self: Long, style: Long): Long
    fun QP_IContainer_showEntire_0(self: Long): Long
    fun QP_IContainer_showIf_1(self: Long, predicate: NativeCallbackJToI?): Long
    fun QP_IContainer_showIf_0(self: Long, condition: Int): Long
    fun QP_IContainer_showOnce_0(self: Long): Long
    fun QP_IContainer_shrink_0(self: Long): Long
    fun QP_IContainer_shrinkHorizontal_0(self: Long): Long
    fun QP_IContainer_shrinkVertical_0(self: Long): Long
    fun QP_IContainer_skipOnce_0(self: Long): Long
    fun QP_IContainer_stack_0(self: Long, handler: NativeCallbackJToV?)
    fun QP_IContainer_stopPaging_0(self: Long): Long
    fun QP_IContainer_svg_0(self: Long, dynamicSvgSource: NativeCallbackJToJ?)
    fun QP_IContainer_svg_1(self: Long, image: Long): Long
    fun QP_IContainer_svg_2(self: Long, svg: String?): Long
    fun QP_IContainer_table_0(self: Long, handler: NativeCallbackJToV?)
    fun QP_IContainer_text_0(self: Long, content: NativeCallbackJToV?)
    fun QP_IContainer_text_3(self: Long, text: String?): Long
    fun QP_IContainer_translateX_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_translateY_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_unconstrained_0(self: Long): Long
    fun QP_IContainer_width_0(self: Long, value: Float, unit: Int): Long
    fun QP_IContainer_zIndex_0(self: Long, indexValue: Int): Long
    fun QP_IDocument_compose_0(self: Long, container: Long)
    fun QP_IDocument_generateImages_0(self: Long, imagePathSource: NativeCallbackIToJ?, settings: Long)
    fun QP_IDocument_generatePdf_0(self: Long, outData: PointerByReference, outLength: IntByReference)
    fun QP_IDocument_generatePdf_2(self: Long, filePath: String?)
    fun QP_IDocument_generatePdfAndShow_0(self: Long)
    fun QP_IDocument_generateXps_0(self: Long, outData: PointerByReference, outLength: IntByReference)
    fun QP_IDocument_generateXps_2(self: Long, filePath: String?)
    fun QP_IDocument_generateXpsAndShow_0(self: Long)
    fun QP_IDocument_getMetadata_0(self: Long): Long
    fun QP_IDocument_getSettings_0(self: Long): Long
    fun QP_IDocument_showInCompanion_0(self: Long, port: Int)
    fun QP_IDocument_showInPreviewer_0(self: Long, port: Int)
    fun QP_IDocumentContainer_page_0(self: Long, handler: NativeCallbackJToV?): Long
    fun QP_Image_getSize_0(self: Long): Long
    fun QP_Image_dispose_0(self: Long)
    fun QP_Image_fromBinaryData_0(imageBytes: ByteArray?, imageBytesLength: Int): Long
    fun QP_Image_fromFile_0(filePath: String?): Long
    fun QP_ImageGenerationSettings_ctor_0(): Long
    fun QP_ImageGenerationSettings_getImageCompressionQuality_0(self: Long): Int
    fun QP_ImageGenerationSettings_setImageCompressionQuality_0(self: Long, value: Int)
    fun QP_ImageGenerationSettings_getImageFormat_0(self: Long): Int
    fun QP_ImageGenerationSettings_setImageFormat_0(self: Long, value: Int)
    fun QP_ImageGenerationSettings_getRasterDpi_0(self: Long): Int
    fun QP_ImageGenerationSettings_setRasterDpi_0(self: Long, value: Int)
    fun QP_ImageGenerationSettings_getDefault_0(): Long
    fun QP_ImageSize_ctor_0(width: Int, height: Int): Long
    fun QP_ImageSize_getHeight_0(self: Long): Int
    fun QP_ImageSize_getWidth_0(self: Long): Int
    fun QP_MergedDocument_compose_0(self: Long, container: Long)
    fun QP_MergedDocument_getMetadata_0(self: Long): Long
    fun QP_MergedDocument_getSettings_0(self: Long): Long
    fun QP_MergedDocument_useContinuousPageNumbers_0(self: Long): Long
    fun QP_MergedDocument_useOriginalPageNumbers_0(self: Long): Long
    fun QP_MergedDocument_withMetadata_0(self: Long, metadata: Long): Long
    fun QP_MergedDocument_withSettings_0(self: Long, settings: Long): Long
    fun QP_PageElementLocation_ctor_0(): Long
    fun QP_PageElementLocation_getHeight_0(self: Long): Float
    fun QP_PageElementLocation_setHeight_0(self: Long, value: Float)
    fun QP_PageElementLocation_getId_0(self: Long): Pointer?
    fun QP_PageElementLocation_setId_0(self: Long, value: String?)
    fun QP_PageElementLocation_getPageNumber_0(self: Long): Int
    fun QP_PageElementLocation_setPageNumber_0(self: Long, value: Int)
    fun QP_PageElementLocation_getWidth_0(self: Long): Float
    fun QP_PageElementLocation_setWidth_0(self: Long, value: Float)
    fun QP_PageElementLocation_getX_0(self: Long): Float
    fun QP_PageElementLocation_setX_0(self: Long, value: Float)
    fun QP_PageElementLocation_getY_0(self: Long): Float
    fun QP_PageElementLocation_setY_0(self: Long, value: Float)
    fun QP_Size_ctor_0(width: Float, height: Float): Long
    fun QP_Size_getHeight_0(self: Long): Float
    fun QP_Size_getWidth_0(self: Long): Float
    fun QP_Size_getMax_0(): Long
    fun QP_Size_getZero_0(): Long
    fun QP_Size_toString_0(self: Long): Pointer?
    fun QP_SvgImage_dispose_0(self: Long)
    fun QP_SvgImage_fromFile_0(filePath: String?): Long
    fun QP_SvgImage_fromText_0(svg: String?): Long
    fun QP_TextStyle_ctor_0(): Long
    fun QP_TextStyle_getDefault_0(): Long
    fun QP_TextStyle_backgroundColor_0(self: Long, color: Long): Long
    fun QP_TextStyle_black_0(self: Long): Long
    fun QP_TextStyle_bold_0(self: Long): Long
    fun QP_TextStyle_color_0(self: Long, value: String?): Long
    fun QP_TextStyle_decorationColor_0(self: Long, color: Long): Long
    fun QP_TextStyle_decorationDashed_0(self: Long): Long
    fun QP_TextStyle_decorationDotted_0(self: Long): Long
    fun QP_TextStyle_decorationDouble_0(self: Long): Long
    fun QP_TextStyle_decorationSolid_0(self: Long): Long
    fun QP_TextStyle_decorationThickness_0(self: Long, factor: Float): Long
    fun QP_TextStyle_decorationWavy_0(self: Long): Long
    fun QP_TextStyle_directionAuto_0(self: Long): Long
    fun QP_TextStyle_directionFromLeftToRight_0(self: Long): Long
    fun QP_TextStyle_directionFromRightToLeft_0(self: Long): Long
    fun QP_TextStyle_disableFontFeature_0(self: Long, featureName: String?): Long
    fun QP_TextStyle_enableFontFeature_0(self: Long, featureName: String?): Long
    fun QP_TextStyle_extraBlack_0(self: Long): Long
    fun QP_TextStyle_extraBold_0(self: Long): Long
    fun QP_TextStyle_extraLight_0(self: Long): Long
    fun QP_TextStyle_fallback_1(self: Long, handler: NativeCallbackJToJ?): Long
    fun QP_TextStyle_fallback_0(self: Long, value: Long): Long
    fun QP_TextStyle_fontColor_0(self: Long, color: Long): Long
    fun QP_TextStyle_fontFamily_0(self: Long, values: Array<out String>?, valuesCount: Int): Long
    fun QP_TextStyle_fontSize_0(self: Long, value: Float): Long
    fun QP_TextStyle_fontType_0(self: Long, value: String?): Long
    fun QP_TextStyle_italic_0(self: Long, value: Int): Long
    fun QP_TextStyle_letterSpacing_0(self: Long, factor: Float): Long
    fun QP_TextStyle_light_0(self: Long): Long
    fun QP_TextStyle_lineHeight_0(self: Long, factorHasValue: Byte, factor: Float): Long
    fun QP_TextStyle_medium_0(self: Long): Long
    fun QP_TextStyle_normalPosition_0(self: Long): Long
    fun QP_TextStyle_normalWeight_0(self: Long): Long
    fun QP_TextStyle_overline_0(self: Long, value: Int): Long
    fun QP_TextStyle_semiBold_0(self: Long): Long
    fun QP_TextStyle_size_0(self: Long, value: Float): Long
    fun QP_TextStyle_strikethrough_0(self: Long, value: Int): Long
    fun QP_TextStyle_subscript_0(self: Long): Long
    fun QP_TextStyle_superscript_0(self: Long): Long
    fun QP_TextStyle_thin_0(self: Long): Long
    fun QP_TextStyle_toString_0(self: Long): Pointer?
    fun QP_TextStyle_underline_0(self: Long, value: Int): Long
    fun QP_TextStyle_weight_0(self: Long, weight: Int): Long
    fun QP_TextStyle_wordSpacing_0(self: Long, factor: Float): Long
    fun QP_TextStyle_wrapAnywhere_0(self: Long, value: Int): Long
    fun QP_Proxy_Component_new(callback: NativeCallbackJToV): Long
    fun QP_Proxy_DynamicComponent_new(callback: NativeCallbackJToJ): Long
}
