// <auto-generated>
// Generated by QuestPDF.Interop.Generator from QuestPDF 2026.7.1.0.
// Do not edit — this file is wiped and recreated on every generator run.
// </auto-generated>

import { Native } from '../../../manual/native-bridge';
import { NATIVE_HANDLE, NativeObject } from '../../../manual/native-object';

/**
 * Provides functionality for performing various operations on PDF documents, including loading, merging, overlaying, underlaying, selecting specific pages, adding attachments, and applying encryption settings.
 */
export class DocumentOperation extends NativeObject {
    /**
     * Adds an attachment to the document, with specified metadata and configuration options.
     */
    addAttachment(attachment: DocumentOperation.DocumentAttachment): DocumentOperation {
        return new DocumentOperation(Native.checked(Native.lib.QP_DocumentOperation_addAttachment_0(this.nativeHandle, attachment.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Removes any existing encryption from the current PDF document, effectively making it accessible without a password or encryption restrictions.
     */
    decrypt(): DocumentOperation {
        return new DocumentOperation(Native.checked(Native.lib.QP_DocumentOperation_decrypt_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Encrypts the document using 128-bit encryption, applying specified owner and user passwords along with defined permissions.
     */
    encrypt(encryption: DocumentOperation.Encryption128Bit): DocumentOperation {
        return new DocumentOperation(Native.checked(Native.lib.QP_DocumentOperation_encrypt_0(this.nativeHandle, encryption.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Extends the current document's XMP metadata by adding content within the `rdf:Description` tag.
     * This allows for adding additional descriptive metadata to the PDF, which is useful for compliance standards
     * like PDF/A or for industry-specific metadata (e.g., ZUGFeRD).
     *
     * @param metadata A string containing the metadata to add. This metadata must be valid XML content and conform to the RDF structure required by the PDF XMP metadata specification.
     */
    extendMetadata(metadata: string): DocumentOperation {
        return new DocumentOperation(Native.checked(Native.lib.QP_DocumentOperation_extendMetadata_0(this.nativeHandle, metadata)), NATIVE_HANDLE);
    }

    /**
     * Creates linearized (web-optimized) output files.
     * Linearized files are structured to allow compliant PDF readers to begin displaying content before the entire file is downloaded.
     * Normally, a PDF reader requires the entire file to be present to render content, as essential cross-reference data typically appears at the file’s end.
     */
    linearize(): DocumentOperation {
        return new DocumentOperation(Native.checked(Native.lib.QP_DocumentOperation_linearize_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Merges pages from the specified PDF file into the current document, according to the provided page selection.
     *
     * - **1, 2, 3** Plain numbers indicate pages numbered from the start
     * - **r1, r2** Numbers with 'r' prefix count from the end (r1 = last page)
     * - **z** Represents the last page (equivalent to r1)
     * - **1-5** Dash-separated ranges are inclusive
     * - **5-1** Reversed ranges list pages in descending order
     * - **x1-3** Excludes specified pages from previous range
     * - **:odd** Selects odd-positioned pages from the resulting page-set
     * - **:even** Selects even-positioned pages from the resulting page-set
     *
     * - **1,6,4** pages 1, 6, and 4 in that order
     * - **3-7** pages 3 through 7 inclusive
     * - **7-3** pages 7, 6, 5, 4, and 3 in that order
     * - **1-z** all pages in order
     * - **z-1** all pages in reverse order
     * - **r3-r1** the last three pages of the document
     * - **r1-r3** the last three pages of the document in reverse order
     * - **1-20:even** even pages from 2 to 20
     * - **5,7-9,12** pages 5, 7, 8, 9, and 12
     * - **5,7-9,12:odd** pages 5, 8, and 12 (pages in odd positions from the original set of 5, 7, 8, 9, 12)
     * - **5,7-9,12:even** pages 7 and 9 (pages in even positions from the original set of 5, 7, 8, 9, 12)
     * - **1-10,x3-4** pages 1 through 10 except pages 3 and 4 (1, 2, and 5 through 10)
     * - **4-10,x7-9,12-8,xr5** In a 15-page file: pages 4, 5, 6, 10, 12, 10, 9, and 8 in that order (pages 4 through 10 except 7 through 9, followed by 12 through 8 descending, except 11 which is the fifth page from the end)
     *
     * @param filePath The path to the PDF file to be merged.
     * @param pageSelector An optional {@link DocumentPageSelector} to specify the range of pages to merge. If not provided, all pages will be merged.
     */
    mergeFile(filePath: string, pageSelector: string | null = null): DocumentOperation {
        return new DocumentOperation(Native.checked(Native.lib.QP_DocumentOperation_mergeFile_0(this.nativeHandle, filePath, pageSelector)), NATIVE_HANDLE);
    }

    /**
     * Applies an overlay to the document using the specified configuration.
     * The overlay pages are drawn on top of the target pages in the output file, potentially obscuring the original content.
     */
    overlayFile(configuration: DocumentOperation.LayerConfiguration): DocumentOperation {
        return new DocumentOperation(Native.checked(Native.lib.QP_DocumentOperation_overlayFile_0(this.nativeHandle, configuration.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Remove security restrictions associated with digitally signed PDF files.
     * This may be combined with Decrypt() operation to allow free editing of previously signed/encrypted files.
     * This option invalidates and disables any digital signatures but leaves their visual appearances intact.
     */
    removeRestrictions(): DocumentOperation {
        return new DocumentOperation(Native.checked(Native.lib.QP_DocumentOperation_removeRestrictions_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Executes the configured operations on the document and saves the resulting file to the specified path.
     *
     * @param filePath The path where the output file will be saved.
     */
    save(filePath: string): void {
        Native.lib.QP_DocumentOperation_save_0(this.nativeHandle, filePath);
        Native.check();
    }

    /**
     * Selects specific pages from the current document based on the provided page selector, marking them for further operations.
     *
     * - **1, 2, 3** Plain numbers indicate pages numbered from the start
     * - **r1, r2** Numbers with 'r' prefix count from the end (r1 = last page)
     * - **z** Represents the last page (equivalent to r1)
     * - **1-5** Dash-separated ranges are inclusive
     * - **5-1** Reversed ranges list pages in descending order
     * - **x1-3** Excludes specified pages from previous range
     * - **:odd** Selects odd-positioned pages from the resulting page-set
     * - **:even** Selects even-positioned pages from the resulting page-set
     *
     * - **1,6,4** pages 1, 6, and 4 in that order
     * - **3-7** pages 3 through 7 inclusive
     * - **7-3** pages 7, 6, 5, 4, and 3 in that order
     * - **1-z** all pages in order
     * - **z-1** all pages in reverse order
     * - **r3-r1** the last three pages of the document
     * - **r1-r3** the last three pages of the document in reverse order
     * - **1-20:even** even pages from 2 to 20
     * - **5,7-9,12** pages 5, 7, 8, 9, and 12
     * - **5,7-9,12:odd** pages 5, 8, and 12 (pages in odd positions from the original set of 5, 7, 8, 9, 12)
     * - **5,7-9,12:even** pages 7 and 9 (pages in even positions from the original set of 5, 7, 8, 9, 12)
     * - **1-10,x3-4** pages 1 through 10 except pages 3 and 4 (1, 2, and 5 through 10)
     * - **4-10,x7-9,12-8,xr5** In a 15-page file: pages 4, 5, 6, 10, 12, 10, 9, and 8 in that order (pages 4 through 10 except 7 through 9, followed by 12 through 8 descending, except 11 which is the fifth page from the end)
     */
    takePages(pageSelector: string): DocumentOperation {
        return new DocumentOperation(Native.checked(Native.lib.QP_DocumentOperation_takePages_0(this.nativeHandle, pageSelector)), NATIVE_HANDLE);
    }

    /**
     * Applies an underlay to the document using the specified configuration.
     * The underlay pages are drawn beneath the target pages in the output file, potentially obscured by the original content.
     */
    underlayFile(configuration: DocumentOperation.LayerConfiguration): DocumentOperation {
        return new DocumentOperation(Native.checked(Native.lib.QP_DocumentOperation_underlayFile_0(this.nativeHandle, configuration.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Loads the specified PDF file for processing, enabling operations such as merging, overlaying or underlaying content, selecting pages, adding attachments, and encrypting.
     *
     * @param filePath The full path to the PDF file to be loaded.
     * @param password The password for the PDF file, if it is password-protected. Optional.
     */
    static loadFile(filePath: string, password: string | null = null): DocumentOperation {
        return new DocumentOperation(Native.checked(Native.lib.QP_DocumentOperation_loadFile_0(filePath, password)), NATIVE_HANDLE);
    }
}

// eslint-disable-next-line @typescript-eslint/no-namespace
export namespace DocumentOperation {
    export class DocumentAttachment extends NativeObject {
        constructor();
        /** Wraps an existing native handle. @internal */
        constructor(handle: number, marker: typeof NATIVE_HANDLE);
        constructor(...args: any[]) {
            if (args[1] === NATIVE_HANDLE) {
                super(args[0] as number, NATIVE_HANDLE);
                return;
            }
            super(Native.checked(Native.lib.QP_DocumentOperation_DocumentAttachment_ctor_0()), NATIVE_HANDLE);
        }

        /**
         * Specifies the display name for the attachment.
         * This name is typically shown to the user and used by most graphical PDF viewers when saving the file.
         * Defaults to the file name without its path.
         */
        get attachmentName(): string | null {
            return Native.takeString(Native.checked(Native.lib.QP_DocumentOperation_DocumentAttachment_getAttachmentName_0(this.nativeHandle)));
        }
        set attachmentName(value: string | null) {
            Native.lib.QP_DocumentOperation_DocumentAttachment_setAttachmentName_0(this.nativeHandle, value);
            Native.check();
        }

        /**
         * Specifies the creation date of the attachment.
         * Defaults to the file's creation time.
         */
        get creationDate(): Date | null {
            const resultText = Native.takeString(Native.checked(Native.lib.QP_DocumentOperation_DocumentAttachment_getCreationDate_0(this.nativeHandle)));
            return resultText == null ? null : new Date(resultText);
        }
        set creationDate(value: Date | null) {
            Native.lib.QP_DocumentOperation_DocumentAttachment_setCreationDate_0(this.nativeHandle, (value?.toISOString() ?? null));
            Native.check();
        }

        /**
         * Sets a description for the attachment, which may be displayed by some PDF viewers.
         */
        get description(): string | null {
            return Native.takeString(Native.checked(Native.lib.QP_DocumentOperation_DocumentAttachment_getDescription_0(this.nativeHandle)));
        }
        set description(value: string | null) {
            Native.lib.QP_DocumentOperation_DocumentAttachment_setDescription_0(this.nativeHandle, value);
            Native.check();
        }

        /**
         * The file path of the attachment. Ensure that the specified file exists.
         */
        get filePath(): string {
            return Native.takeString(Native.checked(Native.lib.QP_DocumentOperation_DocumentAttachment_getFilePath_0(this.nativeHandle)))!;
        }
        set filePath(value: string) {
            Native.lib.QP_DocumentOperation_DocumentAttachment_setFilePath_0(this.nativeHandle, value);
            Native.check();
        }

        /**
         * Sets the key for the attachment, specific to the PDF format.
         * Defaults to the file name without its path.
         */
        get key(): string | null {
            return Native.takeString(Native.checked(Native.lib.QP_DocumentOperation_DocumentAttachment_getKey_0(this.nativeHandle)));
        }
        set key(value: string | null) {
            Native.lib.QP_DocumentOperation_DocumentAttachment_setKey_0(this.nativeHandle, value);
            Native.check();
        }

        /**
         * Specifies the MIME type of the attachment, such as "text/plain", "application/pdf", "image/png", etc.
         */
        get mimeType(): string | null {
            return Native.takeString(Native.checked(Native.lib.QP_DocumentOperation_DocumentAttachment_getMimeType_0(this.nativeHandle)));
        }
        set mimeType(value: string | null) {
            Native.lib.QP_DocumentOperation_DocumentAttachment_setMimeType_0(this.nativeHandle, value);
            Native.check();
        }

        /**
         * Specifies the modification date of the attachment.
         * Defaults to the file's last modified time.
         */
        get modificationDate(): Date | null {
            const resultText = Native.takeString(Native.checked(Native.lib.QP_DocumentOperation_DocumentAttachment_getModificationDate_0(this.nativeHandle)));
            return resultText == null ? null : new Date(resultText);
        }
        set modificationDate(value: Date | null) {
            Native.lib.QP_DocumentOperation_DocumentAttachment_setModificationDate_0(this.nativeHandle, (value?.toISOString() ?? null));
            Native.check();
        }

        /**
         * Specifies the relationship of the embedded file to the document for PDF/A-3b compliance.
         */
        get relationship(): DocumentOperation.DocumentAttachmentRelationship | null {
            const outHasValue: number[] = [0];
            const rawResult = Native.lib.QP_DocumentOperation_DocumentAttachment_getRelationship_0(this.nativeHandle, outHasValue);
            Native.check();
            return outHasValue[0] !== 0 ? (rawResult as DocumentOperation.DocumentAttachmentRelationship) : null;
        }
        set relationship(value: DocumentOperation.DocumentAttachmentRelationship | null) {
            Native.lib.QP_DocumentOperation_DocumentAttachment_setRelationship_0(this.nativeHandle, (value != null ? 1 : 0), (value ?? 0));
            Native.check();
        }

        /**
         * Indicates whether to replace an existing attachment with the same key.
         * If false, an exception is thrown if an attachment with the same key already exists.
         */
        get replace(): boolean {
            return (Native.checked(Native.lib.QP_DocumentOperation_DocumentAttachment_getReplace_0(this.nativeHandle)) !== 0);
        }
        set replace(value: boolean) {
            Native.lib.QP_DocumentOperation_DocumentAttachment_setReplace_0(this.nativeHandle, (value ? 1 : 0));
            Native.check();
        }
    }

    export const DocumentAttachmentRelationship = {
        /**
         * Indicates data files relevant to the document (e.g., supporting datasets or data tables).
         */
        Data: 0,
        /**
         * Represents a source file directly used to create the document.
         */
        Source: 1,
        /**
         * An alternative representation of the document content (e.g., XML, HTML).
         */
        Alternative: 2,
        /**
         * A file supplementing the content, like additional resources.
         */
        Supplement: 3,
        /**
         * No specific relationship is defined.
         */
        Unspecified: 4,
    } as const;

    export type DocumentAttachmentRelationship = (typeof DocumentAttachmentRelationship)[keyof typeof DocumentAttachmentRelationship];

    export class EncryptionBase extends NativeObject {
        constructor();
        /** Wraps an existing native handle. @internal */
        constructor(handle: number, marker: typeof NATIVE_HANDLE);
        constructor(...args: any[]) {
            if (args[1] === NATIVE_HANDLE) {
                super(args[0] as number, NATIVE_HANDLE);
                return;
            }
            super(Native.checked(Native.lib.QP_DocumentOperation_EncryptionBase_ctor_0()), NATIVE_HANDLE);
        }

        /**
         * The owner password for the PDF, granting full access to all document features.
         * An empty owner password is considered insecure, as is using the same value for both user and owner passwords.
         */
        get ownerPassword(): string {
            return Native.takeString(Native.checked(Native.lib.QP_DocumentOperation_EncryptionBase_getOwnerPassword_0(this.nativeHandle)))!;
        }
        set ownerPassword(value: string) {
            Native.lib.QP_DocumentOperation_EncryptionBase_setOwnerPassword_0(this.nativeHandle, value);
            Native.check();
        }

        /**
         * The user password for the PDF, allowing restricted access based on encryption settings.
         * May be left null to enable opening the PDF without a password, though this may restrict certain operations.
         */
        get userPassword(): string | null {
            return Native.takeString(Native.checked(Native.lib.QP_DocumentOperation_EncryptionBase_getUserPassword_0(this.nativeHandle)));
        }
        set userPassword(value: string | null) {
            Native.lib.QP_DocumentOperation_EncryptionBase_setUserPassword_0(this.nativeHandle, value);
            Native.check();
        }
    }

    export class Encryption128Bit extends DocumentOperation.EncryptionBase {
        constructor();
        /** Wraps an existing native handle. @internal */
        constructor(handle: number, marker: typeof NATIVE_HANDLE);
        constructor(...args: any[]) {
            if (args[1] === NATIVE_HANDLE) {
                super(args[0] as number, NATIVE_HANDLE);
                return;
            }
            super(Native.checked(Native.lib.QP_DocumentOperation_Encryption128Bit_ctor_0()), NATIVE_HANDLE);
        }

        /**
         * Specifies whether the user is permitted to add signatures and annotations to the document.
         */
        get allowAnnotation(): boolean {
            return (Native.checked(Native.lib.QP_DocumentOperation_Encryption128Bit_getAllowAnnotation_0(this.nativeHandle)) !== 0);
        }
        set allowAnnotation(value: boolean) {
            Native.lib.QP_DocumentOperation_Encryption128Bit_setAllowAnnotation_0(this.nativeHandle, (value ? 1 : 0));
            Native.check();
        }

        /**
         * Specifies whether the user is permitted to insert, rotate, or delete pages within the document.
         */
        get allowAssembly(): boolean {
            return (Native.checked(Native.lib.QP_DocumentOperation_Encryption128Bit_getAllowAssembly_0(this.nativeHandle)) !== 0);
        }
        set allowAssembly(value: boolean) {
            Native.lib.QP_DocumentOperation_Encryption128Bit_setAllowAssembly_0(this.nativeHandle, (value ? 1 : 0));
            Native.check();
        }

        /**
         * Specifies whether the user is allowed to copy text and graphics from the document.
         */
        get allowContentExtraction(): boolean {
            return (Native.checked(Native.lib.QP_DocumentOperation_Encryption128Bit_getAllowContentExtraction_0(this.nativeHandle)) !== 0);
        }
        set allowContentExtraction(value: boolean) {
            Native.lib.QP_DocumentOperation_Encryption128Bit_setAllowContentExtraction_0(this.nativeHandle, (value ? 1 : 0));
            Native.check();
        }

        /**
         * Specifies whether the user is allowed to fill out existing form fields in the document.
         */
        get allowFillingForms(): boolean {
            return (Native.checked(Native.lib.QP_DocumentOperation_Encryption128Bit_getAllowFillingForms_0(this.nativeHandle)) !== 0);
        }
        set allowFillingForms(value: boolean) {
            Native.lib.QP_DocumentOperation_Encryption128Bit_setAllowFillingForms_0(this.nativeHandle, (value ? 1 : 0));
            Native.check();
        }

        /**
         * Specifies whether the user can print the document.
         */
        get allowPrinting(): boolean {
            return (Native.checked(Native.lib.QP_DocumentOperation_Encryption128Bit_getAllowPrinting_0(this.nativeHandle)) !== 0);
        }
        set allowPrinting(value: boolean) {
            Native.lib.QP_DocumentOperation_Encryption128Bit_setAllowPrinting_0(this.nativeHandle, (value ? 1 : 0));
            Native.check();
        }

        /**
         * Determines whether the document's metadata is included in encryption.
         */
        get encryptMetadata(): boolean {
            return (Native.checked(Native.lib.QP_DocumentOperation_Encryption128Bit_getEncryptMetadata_0(this.nativeHandle)) !== 0);
        }
        set encryptMetadata(value: boolean) {
            Native.lib.QP_DocumentOperation_Encryption128Bit_setEncryptMetadata_0(this.nativeHandle, (value ? 1 : 0));
            Native.check();
        }
    }

    export class Encryption256Bit extends DocumentOperation.EncryptionBase {
        constructor();
        /** Wraps an existing native handle. @internal */
        constructor(handle: number, marker: typeof NATIVE_HANDLE);
        constructor(...args: any[]) {
            if (args[1] === NATIVE_HANDLE) {
                super(args[0] as number, NATIVE_HANDLE);
                return;
            }
            super(Native.checked(Native.lib.QP_DocumentOperation_Encryption256Bit_ctor_0()), NATIVE_HANDLE);
        }

        /**
         * Specifies whether the user is permitted to add signatures and annotations to the document.
         */
        get allowAnnotation(): boolean {
            return (Native.checked(Native.lib.QP_DocumentOperation_Encryption256Bit_getAllowAnnotation_0(this.nativeHandle)) !== 0);
        }
        set allowAnnotation(value: boolean) {
            Native.lib.QP_DocumentOperation_Encryption256Bit_setAllowAnnotation_0(this.nativeHandle, (value ? 1 : 0));
            Native.check();
        }

        /**
         * Specifies whether the user is permitted to insert, rotate, or delete pages within the document.
         */
        get allowAssembly(): boolean {
            return (Native.checked(Native.lib.QP_DocumentOperation_Encryption256Bit_getAllowAssembly_0(this.nativeHandle)) !== 0);
        }
        set allowAssembly(value: boolean) {
            Native.lib.QP_DocumentOperation_Encryption256Bit_setAllowAssembly_0(this.nativeHandle, (value ? 1 : 0));
            Native.check();
        }

        /**
         * Specifies whether the user is allowed to copy text and graphics from the document.
         */
        get allowContentExtraction(): boolean {
            return (Native.checked(Native.lib.QP_DocumentOperation_Encryption256Bit_getAllowContentExtraction_0(this.nativeHandle)) !== 0);
        }
        set allowContentExtraction(value: boolean) {
            Native.lib.QP_DocumentOperation_Encryption256Bit_setAllowContentExtraction_0(this.nativeHandle, (value ? 1 : 0));
            Native.check();
        }

        /**
         * Specifies whether the user is allowed to fill out existing form fields in the document.
         */
        get allowFillingForms(): boolean {
            return (Native.checked(Native.lib.QP_DocumentOperation_Encryption256Bit_getAllowFillingForms_0(this.nativeHandle)) !== 0);
        }
        set allowFillingForms(value: boolean) {
            Native.lib.QP_DocumentOperation_Encryption256Bit_setAllowFillingForms_0(this.nativeHandle, (value ? 1 : 0));
            Native.check();
        }

        /**
         * Specifies whether the user can print the document.
         */
        get allowPrinting(): boolean {
            return (Native.checked(Native.lib.QP_DocumentOperation_Encryption256Bit_getAllowPrinting_0(this.nativeHandle)) !== 0);
        }
        set allowPrinting(value: boolean) {
            Native.lib.QP_DocumentOperation_Encryption256Bit_setAllowPrinting_0(this.nativeHandle, (value ? 1 : 0));
            Native.check();
        }

        /**
         * Determines whether the document's metadata is included in encryption.
         */
        get encryptMetadata(): boolean {
            return (Native.checked(Native.lib.QP_DocumentOperation_Encryption256Bit_getEncryptMetadata_0(this.nativeHandle)) !== 0);
        }
        set encryptMetadata(value: boolean) {
            Native.lib.QP_DocumentOperation_Encryption256Bit_setEncryptMetadata_0(this.nativeHandle, (value ? 1 : 0));
            Native.check();
        }
    }

    export class Encryption40Bit extends DocumentOperation.EncryptionBase {
        constructor();
        /** Wraps an existing native handle. @internal */
        constructor(handle: number, marker: typeof NATIVE_HANDLE);
        constructor(...args: any[]) {
            if (args[1] === NATIVE_HANDLE) {
                super(args[0] as number, NATIVE_HANDLE);
                return;
            }
            super(Native.checked(Native.lib.QP_DocumentOperation_Encryption40Bit_ctor_0()), NATIVE_HANDLE);
        }

        /**
         * Specifies whether the user is permitted to add signatures and annotations to the document.
         */
        get allowAnnotation(): boolean {
            return (Native.checked(Native.lib.QP_DocumentOperation_Encryption40Bit_getAllowAnnotation_0(this.nativeHandle)) !== 0);
        }
        set allowAnnotation(value: boolean) {
            Native.lib.QP_DocumentOperation_Encryption40Bit_setAllowAnnotation_0(this.nativeHandle, (value ? 1 : 0));
            Native.check();
        }

        /**
         * Specifies whether the user is allowed to copy text and graphics from the document.
         */
        get allowContentExtraction(): boolean {
            return (Native.checked(Native.lib.QP_DocumentOperation_Encryption40Bit_getAllowContentExtraction_0(this.nativeHandle)) !== 0);
        }
        set allowContentExtraction(value: boolean) {
            Native.lib.QP_DocumentOperation_Encryption40Bit_setAllowContentExtraction_0(this.nativeHandle, (value ? 1 : 0));
            Native.check();
        }

        /**
         * Specifies whether the user is permitted to insert, rotate, or delete pages within the document.
         */
        get allowModification(): boolean {
            return (Native.checked(Native.lib.QP_DocumentOperation_Encryption40Bit_getAllowModification_0(this.nativeHandle)) !== 0);
        }
        set allowModification(value: boolean) {
            Native.lib.QP_DocumentOperation_Encryption40Bit_setAllowModification_0(this.nativeHandle, (value ? 1 : 0));
            Native.check();
        }

        /**
         * Specifies whether the user can print the document.
         */
        get allowPrinting(): boolean {
            return (Native.checked(Native.lib.QP_DocumentOperation_Encryption40Bit_getAllowPrinting_0(this.nativeHandle)) !== 0);
        }
        set allowPrinting(value: boolean) {
            Native.lib.QP_DocumentOperation_Encryption40Bit_setAllowPrinting_0(this.nativeHandle, (value ? 1 : 0));
            Native.check();
        }
    }

    /**
     * Represents configuration options for applying an overlay or underlay to a PDF document using qpdf.
     */
    export class LayerConfiguration extends NativeObject {
        constructor();
        /** Wraps an existing native handle. @internal */
        constructor(handle: number, marker: typeof NATIVE_HANDLE);
        constructor(...args: any[]) {
            if (args[1] === NATIVE_HANDLE) {
                super(args[0] as number, NATIVE_HANDLE);
                return;
            }
            super(Native.checked(Native.lib.QP_DocumentOperation_LayerConfiguration_ctor_0()), NATIVE_HANDLE);
        }

        /**
         * The file path of the overlay or underlay PDF file to be used.
         */
        get filePath(): string {
            return Native.takeString(Native.checked(Native.lib.QP_DocumentOperation_LayerConfiguration_getFilePath_0(this.nativeHandle)))!;
        }
        set filePath(value: string) {
            Native.lib.QP_DocumentOperation_LayerConfiguration_setFilePath_0(this.nativeHandle, value);
            Native.check();
        }

        /**
         * Specifies an optional range of pages in the overlay or underlay file that will repeat after the initial source pages are exhausted.
         * Useful for repeating certain pages of the overlay or underlay file across multiple pages of the output.
         *
         * - **1, 2, 3** Plain numbers indicate pages numbered from the start
         * - **r1, r2** Numbers with 'r' prefix count from the end (r1 = last page)
         * - **z** Represents the last page (equivalent to r1)
         * - **1-5** Dash-separated ranges are inclusive
         * - **5-1** Reversed ranges list pages in descending order
         * - **x1-3** Excludes specified pages from previous range
         * - **:odd** Selects odd-positioned pages from the resulting page-set
         * - **:even** Selects even-positioned pages from the resulting page-set
         *
         * - **1,6,4** pages 1, 6, and 4 in that order
         * - **3-7** pages 3 through 7 inclusive
         * - **7-3** pages 7, 6, 5, 4, and 3 in that order
         * - **1-z** all pages in order
         * - **z-1** all pages in reverse order
         * - **r3-r1** the last three pages of the document
         * - **r1-r3** the last three pages of the document in reverse order
         * - **1-20:even** even pages from 2 to 20
         * - **5,7-9,12** pages 5, 7, 8, 9, and 12
         * - **5,7-9,12:odd** pages 5, 8, and 12 (pages in odd positions from the original set of 5, 7, 8, 9, 12)
         * - **5,7-9,12:even** pages 7 and 9 (pages in even positions from the original set of 5, 7, 8, 9, 12)
         * - **1-10,x3-4** pages 1 through 10 except pages 3 and 4 (1, 2, and 5 through 10)
         * - **4-10,x7-9,12-8,xr5** In a 15-page file: pages 4, 5, 6, 10, 12, 10, 9, and 8 in that order (pages 4 through 10 except 7 through 9, followed by 12 through 8 descending, except 11 which is the fifth page from the end)
         */
        get repeatSourcePages(): string | null {
            return Native.takeString(Native.checked(Native.lib.QP_DocumentOperation_LayerConfiguration_getRepeatSourcePages_0(this.nativeHandle)));
        }
        set repeatSourcePages(value: string | null) {
            Native.lib.QP_DocumentOperation_LayerConfiguration_setRepeatSourcePages_0(this.nativeHandle, value);
            Native.check();
        }

        /**
         * Specifies the range of pages in the overlay or underlay file to be used initially.
         * If not specified, all pages in the overlay or underlay file will be used in sequence.
         *
         * - **1, 2, 3** Plain numbers indicate pages numbered from the start
         * - **r1, r2** Numbers with 'r' prefix count from the end (r1 = last page)
         * - **z** Represents the last page (equivalent to r1)
         * - **1-5** Dash-separated ranges are inclusive
         * - **5-1** Reversed ranges list pages in descending order
         * - **x1-3** Excludes specified pages from previous range
         * - **:odd** Selects odd-positioned pages from the resulting page-set
         * - **:even** Selects even-positioned pages from the resulting page-set
         *
         * - **1,6,4** pages 1, 6, and 4 in that order
         * - **3-7** pages 3 through 7 inclusive
         * - **7-3** pages 7, 6, 5, 4, and 3 in that order
         * - **1-z** all pages in order
         * - **z-1** all pages in reverse order
         * - **r3-r1** the last three pages of the document
         * - **r1-r3** the last three pages of the document in reverse order
         * - **1-20:even** even pages from 2 to 20
         * - **5,7-9,12** pages 5, 7, 8, 9, and 12
         * - **5,7-9,12:odd** pages 5, 8, and 12 (pages in odd positions from the original set of 5, 7, 8, 9, 12)
         * - **5,7-9,12:even** pages 7 and 9 (pages in even positions from the original set of 5, 7, 8, 9, 12)
         * - **1-10,x3-4** pages 1 through 10 except pages 3 and 4 (1, 2, and 5 through 10)
         * - **4-10,x7-9,12-8,xr5** In a 15-page file: pages 4, 5, 6, 10, 12, 10, 9, and 8 in that order (pages 4 through 10 except 7 through 9, followed by 12 through 8 descending, except 11 which is the fifth page from the end)
         */
        get sourcePages(): string | null {
            return Native.takeString(Native.checked(Native.lib.QP_DocumentOperation_LayerConfiguration_getSourcePages_0(this.nativeHandle)));
        }
        set sourcePages(value: string | null) {
            Native.lib.QP_DocumentOperation_LayerConfiguration_setSourcePages_0(this.nativeHandle, value);
            Native.check();
        }

        /**
         * Specifies the range of pages in the output document where the overlay or underlay will be applied.
         * If not specified, the overlay or underlay is applied to all output pages.
         *
         * - **1, 2, 3** Plain numbers indicate pages numbered from the start
         * - **r1, r2** Numbers with 'r' prefix count from the end (r1 = last page)
         * - **z** Represents the last page (equivalent to r1)
         * - **1-5** Dash-separated ranges are inclusive
         * - **5-1** Reversed ranges list pages in descending order
         * - **x1-3** Excludes specified pages from previous range
         * - **:odd** Selects odd-positioned pages from the resulting page-set
         * - **:even** Selects even-positioned pages from the resulting page-set
         *
         * - **1,6,4** pages 1, 6, and 4 in that order
         * - **3-7** pages 3 through 7 inclusive
         * - **7-3** pages 7, 6, 5, 4, and 3 in that order
         * - **1-z** all pages in order
         * - **z-1** all pages in reverse order
         * - **r3-r1** the last three pages of the document
         * - **r1-r3** the last three pages of the document in reverse order
         * - **1-20:even** even pages from 2 to 20
         * - **5,7-9,12** pages 5, 7, 8, 9, and 12
         * - **5,7-9,12:odd** pages 5, 8, and 12 (pages in odd positions from the original set of 5, 7, 8, 9, 12)
         * - **5,7-9,12:even** pages 7 and 9 (pages in even positions from the original set of 5, 7, 8, 9, 12)
         * - **1-10,x3-4** pages 1 through 10 except pages 3 and 4 (1, 2, and 5 through 10)
         * - **4-10,x7-9,12-8,xr5** In a 15-page file: pages 4, 5, 6, 10, 12, 10, 9, and 8 in that order (pages 4 through 10 except 7 through 9, followed by 12 through 8 descending, except 11 which is the fifth page from the end)
         */
        get targetPages(): string | null {
            return Native.takeString(Native.checked(Native.lib.QP_DocumentOperation_LayerConfiguration_getTargetPages_0(this.nativeHandle)));
        }
        set targetPages(value: string | null) {
            Native.lib.QP_DocumentOperation_LayerConfiguration_setTargetPages_0(this.nativeHandle, value);
            Native.check();
        }
    }
}
