// <auto-generated>
// Generated by QuestPDF.Interop.Generator from QuestPDF 2026.7.1.0.
// Do not edit — this file is wiped and recreated on every generator run.
// </auto-generated>

/**
 * Transforms a page number into a custom text format (e.g., roman numerals).
 *
 * When `pageNumber` is null, the delegate should return a default placeholder text of a typical length.
 */
export type PageNumberFormatter = (pageNumber: number | null) => string;
