// <auto-generated>
// Generated by QuestPDF.Interop.Generator from QuestPDF 2026.7.1.0.
// Do not edit — this file is wiped and recreated on every generator run.
// </auto-generated>

import { Native } from '../../../manual/native-bridge';
import { NATIVE_HANDLE, NativeObject } from '../../../manual/native-object';
import { NativeCallbackJToV } from '../../interop/callback-shapes';
import { ITableCellContainer, TableCellContainerImpl, TableCellDescriptor, TableColumnsDefinitionDescriptor } from '../../internal';

export class TableDescriptor extends NativeObject {
    /**
     * Inserts a new item into the table element.
     *
     * @returns The container for the newly inserted cell, enabling customization of its position, size, and content.
     */
    cell(): ITableCellContainer {
        return new TableCellContainerImpl(Native.checked(Native.lib.QP_TableDescriptor_cell_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Specifies the order and size of the table columns.
     * [Learn more](https://www.questpdf.com/api-reference/table/basics.html#columns-definition)
     *
     * This configuration affects both the main content as well as the header and footer sections.
     *
     * @param handler Handler to define columns of the table.
     */
    columnsDefinition(handler: (tableColumnsDefinition: TableColumnsDefinitionDescriptor) => void): void {
        Native.lib.QP_TableDescriptor_columnsDefinition_0(this.nativeHandle, Native.retain(NativeCallbackJToV, (p0: number) => Native.guard(undefined, () => { handler(new TableColumnsDefinitionDescriptor(p0, NATIVE_HANDLE)); })));
        Native.check();
    }

    /**
     * Adjusts rendering algorithm to better handle complex table structures, especially those spanning multiple pages.
     * This applies a unique rule to the final cells in each column, ensuring they stretch to fill the table's bottom edge.
     * Such an approach can enhance your table's visual appeal.
     */
    extendLastCellsToTableBottom(): void {
        Native.lib.QP_TableDescriptor_extendLastCellsToTableBottom_0(this.nativeHandle);
        Native.check();
    }

    /**
     * Specifies a table footer that appears on each page, positioned below the main content.
     * The placement and dimensions of cells within this footer are distinct from the main content.
     * [Learn more](https://www.questpdf.com/api-reference/table/header-and-footer.html)
     */
    footer(handler: (tableCell: TableCellDescriptor) => void): void {
        Native.lib.QP_TableDescriptor_footer_0(this.nativeHandle, Native.retain(NativeCallbackJToV, (p0: number) => Native.guard(undefined, () => { handler(new TableCellDescriptor(p0, NATIVE_HANDLE)); })));
        Native.check();
    }

    /**
     * Specifies a table header that appears on each page, positioned above the main content.
     * The cell placement and dimensions in this header are distinct from those in the main content.
     * [Learn more](https://www.questpdf.com/api-reference/table/header-and-footer.html)
     *
     * @param handler Handler for configuring the header cells.
     */
    header(handler: (tableCell: TableCellDescriptor) => void): void {
        Native.lib.QP_TableDescriptor_header_0(this.nativeHandle, Native.retain(NativeCallbackJToV, (p0: number) => Native.guard(undefined, () => { handler(new TableCellDescriptor(p0, NATIVE_HANDLE)); })));
        Native.check();
    }
}
