// <auto-generated>
// Generated by QuestPDF.Interop.Generator from QuestPDF 2026.7.1.0.
// Do not edit — this file is wiped and recreated on every generator run.
// </auto-generated>

import { Native } from '../../../manual/native-bridge';
import { NATIVE_HANDLE, NativeObject } from '../../../manual/native-object';
import { NativeCallbackJToJ } from '../../interop/callback-shapes';
import { Color, TextStyle } from '../../internal';

export class TextSpanDescriptor extends NativeObject {
    /**
     * Sets a solid background color for the text.
     * This color fills the area behind the text or other elements, enhancing contrast and providing visual emphasis.
     *
     * @param color Color in a [valid format](https://www.questpdf.com/concepts/colors.html) (like `#FF8800` for orange) or from the predefined {@link Colors} set (like `Colors.Red.Lighten1`).
     */
    backgroundColor(color: Color): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_backgroundColor_0(this.nativeHandle, color.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the font weight to "black" (equivalent to CSS 900).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    black(): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_black_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the font weight to "bold" (equivalent to CSS 700).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    bold(): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_bold_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the color of the text decoration.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    decorationColor(color: Color): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_decorationColor_0(this.nativeHandle, color.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the decoration line to dashes.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    decorationDashed(): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_decorationDashed_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the decoration line to dots.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    decorationDotted(): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_decorationDotted_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the decoration line to a solid double line.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    decorationDouble(): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_decorationDouble_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the decoration line to a solid straight line.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    decorationSolid(): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_decorationSolid_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Changess thickness of decoration line proportionally to the provided argument.
     * Value equal to 1 is the default thickness.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    decorationThickness(factor: number): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_decorationThickness_0(this.nativeHandle, factor)), NATIVE_HANDLE);
    }

    /**
     * Sets the decoration line to wave.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    decorationWavy(): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_decorationWavy_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Resets the text direction, enabling content to follow the automatically detected direction.
     */
    directionAuto(): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_directionAuto_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Enforces a left-to-right text direction.
     */
    directionFromLeftToRight(): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_directionFromLeftToRight_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Enforces a right-to-left text direction.
     */
    directionFromRightToLeft(): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_directionFromRightToLeft_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Enables or disables font features defined by the OpenType standard, e.g. kernig, ligatures.
     *
     * Font features are always encoded as 4-character long strings. For example, the ligatures feature is encode as `liga`, while the kernig feature as `kern`.
     * For a list of available features, refer to the {@link FontFeatures} class.
     *
     * To better understand what font features are, please consider example definitions. Please note that there are many more various font features. Most fonts support only a handful of them, having some of them enabled by default:
     *
     * Ligatures in typography are specific character combinations that are designed to improve the aesthetics and readability of certain letter pairs. For example, in some fonts, when you type certain combinations of letters like 'fi' or 'fl', they will be replaced with a single, joined glyph.
     *
     * Kerning in typography refers to the adjustment of space between characters in a proportional font. It's used to achieve a visually pleasing result by adjusting the spacing of specific character pairs. For example, in many fonts, the pair 'AV' is kerned so that the 'A' and 'V' are closer together than they would be by default.
     *
     * TextStyle.Default.EnableFontFeature(FontFeatures.StandardLigatures);
     *
     * TextStyle.Default.DisableFontFeature(FontFeatures.Kerning);
     *
     * @param value Provide font feature name or use the {@link FontFeatures} class.
     */
    disableFontFeature(featureName: string): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_disableFontFeature_0(this.nativeHandle, featureName)), NATIVE_HANDLE);
    }

    /**
     * Enables or disables font features defined by the OpenType standard, e.g. kernig, ligatures.
     *
     * Font features are always encoded as 4-character long strings. For example, the ligatures feature is encode as `liga`, while the kernig feature as `kern`.
     * For a list of available features, refer to the {@link FontFeatures} class.
     *
     * To better understand what font features are, please consider example definitions. Please note that there are many more various font features. Most fonts support only a handful of them, having some of them enabled by default:
     *
     * Ligatures in typography are specific character combinations that are designed to improve the aesthetics and readability of certain letter pairs. For example, in some fonts, when you type certain combinations of letters like 'fi' or 'fl', they will be replaced with a single, joined glyph.
     *
     * Kerning in typography refers to the adjustment of space between characters in a proportional font. It's used to achieve a visually pleasing result by adjusting the spacing of specific character pairs. For example, in many fonts, the pair 'AV' is kerned so that the 'A' and 'V' are closer together than they would be by default.
     *
     * TextStyle.Default.EnableFontFeature(FontFeatures.StandardLigatures);
     *
     * TextStyle.Default.DisableFontFeature(FontFeatures.Kerning);
     *
     * @param value Provide font feature name or use the {@link FontFeatures} class.
     */
    enableFontFeature(featureName: string): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_enableFontFeature_0(this.nativeHandle, featureName)), NATIVE_HANDLE);
    }

    /**
     * Sets the font weight to "extra black" (equivalent to CSS 1000).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    extraBlack(): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_extraBlack_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the font weight to "extra bold" (equivalent to CSS 800).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    extraBold(): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_extraBold_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the font weight to "extra light" (equivalent to CSS 200).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    extraLight(): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_extraLight_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * @deprecated This setting is not supported since the 2024.3 version. Please use the FontFamilyFallback method or rely on the new automated fallback mechanism.
     */
    fallback(handler: (textStyle: TextStyle) => TextStyle): TextSpanDescriptor;
    /**
     * @deprecated This setting is not supported since the 2024.3 version. Please use the FontFamilyFallback method or rely on the new automated fallback mechanism.
     */
    fallback(value?: TextStyle | null): TextSpanDescriptor;
    fallback(...args: any[]): any {
        if (args.length === 1 && typeof args[0] === "function") {
            const handler = args[0] as (textStyle: TextStyle) => TextStyle;
            return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_fallback_1(this.nativeHandle, Native.retain(NativeCallbackJToJ, (p0: number) => Native.guard(0, () => (handler(new TextStyle(p0, NATIVE_HANDLE))).nativeHandle)))), NATIVE_HANDLE);
        }
        if (args.length <= 1 && (args.length <= 0 || (args[0] === null || args[0] === undefined || args[0] instanceof NativeObject))) {
            const value = (args.length > 0 && args[0] !== undefined ? args[0] : null) as TextStyle | null;
            return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_fallback_0(this.nativeHandle, (value?.nativeHandle ?? 0))), NATIVE_HANDLE);
        }
        throw new TypeError("No overload of 'fallback' matches the provided arguments.");
    }

    /**
     * Sets the font color.
     * The font color determines the color applied to text characters, affecting their visual appearance.
     *
     * It also influences the default color of text decorations, such as underlines.
     *
     * @param color Color in a [valid format](https://www.questpdf.com/concepts/colors.html) (like `#FF8800` for orange) or from the predefined {@link Colors} set (like `Colors.Red.Lighten1`).
     */
    fontColor(color: Color): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_fontColor_0(this.nativeHandle, color.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the font family of the text.
     * A font family is a collection of related fonts that share a consistent design style but may vary in weight, style, or width.
     * Examples of font families include Arial, Times New Roman, and Calibri.
     *
     * By default, the library searches all fonts available in the runtime environment.
     *
     * This may work well on the development environment but may fail in the cloud where fonts are usually not installed.
     *
     * It is safest deploy font files along with the application and then register them using the {@link FontManager} class.
     *
     * @param value Actual font family (e.g. "Times New Roman", "Calibri", "Lato") or custom identifier used when invoking the {@link FontManager.RegisterFontWithCustomName} method.
     */
    fontFamily(...values: string[]): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_fontFamily_0(this.nativeHandle, values, values.length)), NATIVE_HANDLE);
    }

    /**
     * Sets font size for the text.
     * Font size measures the height of text characters, determining how large or small the text appears.
     *
     * It's worth noting that different fonts may render text with distinct visual sizes, even when assigned the same numerical font size.
     */
    fontSize(value: number): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_fontSize_0(this.nativeHandle, value)), NATIVE_HANDLE);
    }

    /**
     * Renders text with an italic effect, where letters are slightly slanted to the right.
     * Commonly used for emphasis or to distinguish specific words.
     */
    italic(value: boolean = true): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_italic_0(this.nativeHandle, (value ? 1 : 0))), NATIVE_HANDLE);
    }

    /**
     * Adjusts the horizontal spacing between characters in the text, affecting readability and overall visual style.
     * The adjustment is proportional to the text size.
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#letter-spacing)
     *
     * @param factor Sets the proportion by which the horizontal space between characters is changed.  A value of 0 maintains the original spacing. When the value is positive, the text is more spread out. When it is negative, the text is more condensed.
     */
    letterSpacing(factor: number = 0): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_letterSpacing_0(this.nativeHandle, factor)), NATIVE_HANDLE);
    }

    /**
     * Sets the font weight to "light" (equivalent to CSS 300).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    light(): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_light_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Adjusts the vertical spacing between lines of text, affecting readability and overall text layout.
     * The added space is proportional to the text size.
     * A `factor` value of 1 retains the original spacing.
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#line-height)
     *
     * @param factor Sets the proportion of vertical spacing relative to the font size.  A value greater than 1 increases the spacing, while a value less than 1 decreases it. The value must be greater than 0.  A value of `1` sets the line height equal to the font size. This setting may result in insufficient vertical spacing around the text.  A value of `default` indicates that the font metrics should be used to calculate the line spacing, which is the default behavior.
     */
    lineHeight(factor: number | null): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_lineHeight_0(this.nativeHandle, (factor != null ? 1 : 0), (factor ?? 0))), NATIVE_HANDLE);
    }

    /**
     * Sets the font weight to "medium" (equivalent to CSS 500).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    medium(): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_medium_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Resets the text position and size to default, utilizing the full available line height.
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#subscript)
     */
    normalPosition(): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_normalPosition_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the font weight to "normal" or "regular (equivalent to CSS 400).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    normalWeight(): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_normalWeight_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Draws a line above the text.
     *
     * You can control the decoration visuals by setting color and style (solid, double, wavy, dotted, dashed) of the line.
     */
    overline(value: boolean = true): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_overline_0(this.nativeHandle, (value ? 1 : 0))), NATIVE_HANDLE);
    }

    /**
     * Sets the font weight to "semi bold" (equivalent to CSS 600).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    semiBold(): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_semiBold_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Draws a line through the middle of the text.
     *
     * You can control the decoration visuals by setting color and style (solid, double, wavy, dotted, dashed) of the line.
     */
    strikethrough(value: boolean = true): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_strikethrough_0(this.nativeHandle, (value ? 1 : 0))), NATIVE_HANDLE);
    }

    /**
     * Sets a font style using the typography pattern.
     * [Learn more](https://www.questpdf.com/api-reference/text/basics.html#typography-pattern)
     *
     * This API reduces the garbage collector pressure and offers the best performance.
     */
    style(style: TextStyle): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_style_0(this.nativeHandle, style.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the text style to subscript, making it smaller and positioning it below the baseline, e.g.: H₂0.
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#subscript)
     */
    subscript(): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_subscript_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the text style to subscript, making it smaller and positioning it above the baseline, e.g.: y² + x² = 1.
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#superscript)
     */
    superscript(): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_superscript_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the font weight to "thin" (equivalent to CSS 100).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    thin(): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_thin_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Draws a line under the text.
     *
     * You can control the decoration visuals by setting color and style (solid, double, wavy, dotted, dashed) of the line.
     */
    underline(value: boolean = true): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_underline_0(this.nativeHandle, (value ? 1 : 0))), NATIVE_HANDLE);
    }

    /**
     * Adjusts the horizontal spacing between words in the text, affecting readability and overall visual style.
     * The adjustment is proportional to the text size.
     *
     * @param factor Sets the proportion by which the horizontal space between words is changed.  A value of 0 maintains the original spacing. When the value is positive, the text is more spread out. When it is negative, the text is more condensed.
     */
    wordSpacing(factor: number = 0): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_wordSpacing_0(this.nativeHandle, factor)), NATIVE_HANDLE);
    }

    /**
     * Allows text to wrap at any character, not just spaces.
     *
     * @deprecated This setting is not supported since the 2024.3 version. This flag should be handled automatically by the layout engine.
     */
    wrapAnywhere(value: boolean = true): TextSpanDescriptor {
        return new TextSpanDescriptor(Native.checked(Native.lib.QP_TextSpanDescriptor_wrapAnywhere_0(this.nativeHandle, (value ? 1 : 0))), NATIVE_HANDLE);
    }
}
