// <auto-generated>
// Generated by QuestPDF.Interop.Generator from QuestPDF 2026.7.1.0.
// Do not edit — this file is wiped and recreated on every generator run.
// </auto-generated>

import { Native } from '../../../manual/native-bridge';
import { NATIVE_HANDLE } from '../../../manual/native-object';
import { NativeCallbackJToJ } from '../../interop/callback-shapes';
import { Color, TextSpanDescriptor, TextStyle, Unit } from '../../internal';

export class TextBlockDescriptor extends TextSpanDescriptor {
    /**
     * Aligns text horizontally to the center, ensuring equal space on both left and right sides.
     */
    alignCenter(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_alignCenter_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Aligns the text horizontally to the end of the container.
     * This method sets the horizontal alignment of the text to the end (right for left-to-right languages, left for right-to-left languages).
     */
    alignEnd(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_alignEnd_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Aligns text horizontally to the left side.
     */
    alignLeft(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_alignLeft_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Aligns content horizontally to the right side.
     */
    alignRight(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_alignRight_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Aligns the text horizontally to the start of the container.
     * This method sets the horizontal alignment of the text to the start (left for left-to-right languages, right for right-to-left languages).
     */
    alignStart(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_alignStart_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets a solid background color for the text.
     * This color fills the area behind the text or other elements, enhancing contrast and providing visual emphasis.
     *
     * @param color Color in a [valid format](https://www.questpdf.com/concepts/colors.html) (like `#FF8800` for orange) or from the predefined {@link Colors} set (like `Colors.Red.Lighten1`).
     */
    backgroundColor(color: Color): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_backgroundColor_0(this.nativeHandle, color.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the font weight to "black" (equivalent to CSS 900).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    black(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_black_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the font weight to "bold" (equivalent to CSS 700).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    bold(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_bold_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Limits the number of visible lines in a paragraph, truncating overflow text with an ellipsis or by hiding it to maintain layout consistency.
     */
    clampLines(maxLines: number, ellipsis: string = "…"): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_clampLines_0(this.nativeHandle, maxLines, ellipsis)), NATIVE_HANDLE);
    }

    /**
     * Sets the color of the text decoration.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    decorationColor(color: Color): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_decorationColor_0(this.nativeHandle, color.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the decoration line to dashes.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    decorationDashed(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_decorationDashed_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the decoration line to dots.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    decorationDotted(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_decorationDotted_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the decoration line to a solid double line.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    decorationDouble(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_decorationDouble_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the decoration line to a solid straight line.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    decorationSolid(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_decorationSolid_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Changess thickness of decoration line proportionally to the provided argument.
     * Value equal to 1 is the default thickness.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    decorationThickness(factor: number): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_decorationThickness_0(this.nativeHandle, factor)), NATIVE_HANDLE);
    }

    /**
     * Sets the decoration line to wave.
     *
     * Applies for the following text decorations: striketrough, underline, overline.
     */
    decorationWavy(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_decorationWavy_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Resets the text direction, enabling content to follow the automatically detected direction.
     */
    directionAuto(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_directionAuto_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Enforces a left-to-right text direction.
     */
    directionFromLeftToRight(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_directionFromLeftToRight_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Enforces a right-to-left text direction.
     */
    directionFromRightToLeft(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_directionFromRightToLeft_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Enables or disables font features defined by the OpenType standard, e.g. kernig, ligatures.
     *
     * Font features are always encoded as 4-character long strings. For example, the ligatures feature is encode as `liga`, while the kernig feature as `kern`.
     * For a list of available features, refer to the {@link FontFeatures} class.
     *
     * To better understand what font features are, please consider example definitions. Please note that there are many more various font features. Most fonts support only a handful of them, having some of them enabled by default:
     *
     * Ligatures in typography are specific character combinations that are designed to improve the aesthetics and readability of certain letter pairs. For example, in some fonts, when you type certain combinations of letters like 'fi' or 'fl', they will be replaced with a single, joined glyph.
     *
     * Kerning in typography refers to the adjustment of space between characters in a proportional font. It's used to achieve a visually pleasing result by adjusting the spacing of specific character pairs. For example, in many fonts, the pair 'AV' is kerned so that the 'A' and 'V' are closer together than they would be by default.
     *
     * TextStyle.Default.EnableFontFeature(FontFeatures.StandardLigatures);
     *
     * TextStyle.Default.DisableFontFeature(FontFeatures.Kerning);
     *
     * @param value Provide font feature name or use the {@link FontFeatures} class.
     */
    disableFontFeature(featureName: string): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_disableFontFeature_0(this.nativeHandle, featureName)), NATIVE_HANDLE);
    }

    /**
     * Enables or disables font features defined by the OpenType standard, e.g. kernig, ligatures.
     *
     * Font features are always encoded as 4-character long strings. For example, the ligatures feature is encode as `liga`, while the kernig feature as `kern`.
     * For a list of available features, refer to the {@link FontFeatures} class.
     *
     * To better understand what font features are, please consider example definitions. Please note that there are many more various font features. Most fonts support only a handful of them, having some of them enabled by default:
     *
     * Ligatures in typography are specific character combinations that are designed to improve the aesthetics and readability of certain letter pairs. For example, in some fonts, when you type certain combinations of letters like 'fi' or 'fl', they will be replaced with a single, joined glyph.
     *
     * Kerning in typography refers to the adjustment of space between characters in a proportional font. It's used to achieve a visually pleasing result by adjusting the spacing of specific character pairs. For example, in many fonts, the pair 'AV' is kerned so that the 'A' and 'V' are closer together than they would be by default.
     *
     * TextStyle.Default.EnableFontFeature(FontFeatures.StandardLigatures);
     *
     * TextStyle.Default.DisableFontFeature(FontFeatures.Kerning);
     *
     * @param value Provide font feature name or use the {@link FontFeatures} class.
     */
    enableFontFeature(featureName: string): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_enableFontFeature_0(this.nativeHandle, featureName)), NATIVE_HANDLE);
    }

    /**
     * Sets the font weight to "extra black" (equivalent to CSS 1000).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    extraBlack(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_extraBlack_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the font weight to "extra bold" (equivalent to CSS 800).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    extraBold(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_extraBold_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the font weight to "extra light" (equivalent to CSS 200).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    extraLight(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_extraLight_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * @deprecated This setting is not supported since the 2024.3 version. Please use the FontFamilyFallback method or rely on the new automated fallback mechanism.
     */
    fallback(handler: (textStyle: TextStyle) => TextStyle): TextBlockDescriptor;
    /**
     * @deprecated This setting is not supported since the 2024.3 version. Please use the FontFamilyFallback method or rely on the new automated fallback mechanism.
     */
    fallback(value?: TextStyle | null): TextBlockDescriptor;
    fallback(...args: any[]): any {
        if (args.length === 1 && typeof args[0] === "function") {
            const handler = args[0] as (textStyle: TextStyle) => TextStyle;
            return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_fallback_1(this.nativeHandle, Native.retain(NativeCallbackJToJ, (p0: number) => Native.guard(0, () => (handler(new TextStyle(p0, NATIVE_HANDLE))).nativeHandle)))), NATIVE_HANDLE);
        }
        if (args.length <= 1 && (args.length <= 0 || (args[0] === null || args[0] === undefined || args[0] instanceof TextStyle))) {
            const value = (args.length > 0 && args[0] !== undefined ? args[0] : null) as TextStyle | null;
            return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_fallback_0(this.nativeHandle, (value?.nativeHandle ?? 0))), NATIVE_HANDLE);
        }
        throw new TypeError("No overload of 'fallback' matches the provided arguments.");
    }

    /**
     * Sets the font color.
     * The font color determines the color applied to text characters, affecting their visual appearance.
     *
     * It also influences the default color of text decorations, such as underlines.
     *
     * @param color Color in a [valid format](https://www.questpdf.com/concepts/colors.html) (like `#FF8800` for orange) or from the predefined {@link Colors} set (like `Colors.Red.Lighten1`).
     */
    fontColor(color: Color): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_fontColor_0(this.nativeHandle, color.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the font family of the text.
     * A font family is a collection of related fonts that share a consistent design style but may vary in weight, style, or width.
     * Examples of font families include Arial, Times New Roman, and Calibri.
     *
     * By default, the library searches all fonts available in the runtime environment.
     *
     * This may work well on the development environment but may fail in the cloud where fonts are usually not installed.
     *
     * It is safest deploy font files along with the application and then register them using the {@link FontManager} class.
     *
     * @param value Actual font family (e.g. "Times New Roman", "Calibri", "Lato") or custom identifier used when invoking the {@link FontManager.RegisterFontWithCustomName} method.
     */
    fontFamily(...values: string[]): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_fontFamily_0(this.nativeHandle, values, values.length)), NATIVE_HANDLE);
    }

    /**
     * Sets font size for the text.
     * Font size measures the height of text characters, determining how large or small the text appears.
     *
     * It's worth noting that different fonts may render text with distinct visual sizes, even when assigned the same numerical font size.
     */
    fontSize(value: number): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_fontSize_0(this.nativeHandle, value)), NATIVE_HANDLE);
    }

    /**
     * Renders text with an italic effect, where letters are slightly slanted to the right.
     * Commonly used for emphasis or to distinguish specific words.
     */
    italic(value: boolean = true): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_italic_0(this.nativeHandle, (value ? 1 : 0))), NATIVE_HANDLE);
    }

    /**
     * Justifies the text within its container.
     *
     * This method sets the horizontal alignment of the text to be justified, meaning it aligns along both the left and right margins.
     * This is achieved by adjusting the spacing between words and characters as necessary so that each line of text stretches from one end of the text column to the other.
     * This creates a clean, block-like appearance for the text.
     */
    justify(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_justify_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Adjusts the horizontal spacing between characters in the text, affecting readability and overall visual style.
     * The adjustment is proportional to the text size.
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#letter-spacing)
     *
     * @param factor Sets the proportion by which the horizontal space between characters is changed.  A value of 0 maintains the original spacing. When the value is positive, the text is more spread out. When it is negative, the text is more condensed.
     */
    letterSpacing(factor: number = 0): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_letterSpacing_0(this.nativeHandle, factor)), NATIVE_HANDLE);
    }

    /**
     * Sets the font weight to "light" (equivalent to CSS 300).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    light(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_light_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Adjusts the vertical spacing between lines of text, affecting readability and overall text layout.
     * The added space is proportional to the text size.
     * A `factor` value of 1 retains the original spacing.
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#line-height)
     *
     * @param factor Sets the proportion of vertical spacing relative to the font size.  A value greater than 1 increases the spacing, while a value less than 1 decreases it. The value must be greater than 0.  A value of `1` sets the line height equal to the font size. This setting may result in insufficient vertical spacing around the text.  A value of `default` indicates that the font metrics should be used to calculate the line spacing, which is the default behavior.
     */
    lineHeight(factor: number | null): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_lineHeight_0(this.nativeHandle, (factor != null ? 1 : 0), (factor ?? 0))), NATIVE_HANDLE);
    }

    /**
     * Sets the font weight to "medium" (equivalent to CSS 500).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    medium(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_medium_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Resets the text position and size to default, utilizing the full available line height.
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#subscript)
     */
    normalPosition(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_normalPosition_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the font weight to "normal" or "regular (equivalent to CSS 400).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    normalWeight(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_normalWeight_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Draws a line above the text.
     *
     * You can control the decoration visuals by setting color and style (solid, double, wavy, dotted, dashed) of the line.
     */
    overline(value: boolean = true): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_overline_0(this.nativeHandle, (value ? 1 : 0))), NATIVE_HANDLE);
    }

    /**
     * Specifies the horizontal offset of the first line in a paragraph.
     * Commonly used to visually separate paragraphs in a block of text.
     */
    paragraphFirstLineIndentation(value: number, unit: Unit = Unit.Point): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_paragraphFirstLineIndentation_0(this.nativeHandle, value, unit)), NATIVE_HANDLE);
    }

    /**
     * Adjusts the vertical gap between successive paragraphs (separated by line breaks),
     * helping to visually separate blocks of text for improved readability.
     */
    paragraphSpacing(value: number, unit: Unit = Unit.Point): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_paragraphSpacing_0(this.nativeHandle, value, unit)), NATIVE_HANDLE);
    }

    /**
     * Sets the font weight to "semi bold" (equivalent to CSS 600).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    semiBold(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_semiBold_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Draws a line through the middle of the text.
     *
     * You can control the decoration visuals by setting color and style (solid, double, wavy, dotted, dashed) of the line.
     */
    strikethrough(value: boolean = true): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_strikethrough_0(this.nativeHandle, (value ? 1 : 0))), NATIVE_HANDLE);
    }

    /**
     * Sets a font style using the typography pattern.
     * [Learn more](https://www.questpdf.com/api-reference/text/basics.html#typography-pattern)
     *
     * This API reduces the garbage collector pressure and offers the best performance.
     */
    style(style: TextStyle): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_style_0(this.nativeHandle, style.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the text style to subscript, making it smaller and positioning it below the baseline, e.g.: H₂0.
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#subscript)
     */
    subscript(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_subscript_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the text style to subscript, making it smaller and positioning it above the baseline, e.g.: y² + x² = 1.
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#superscript)
     */
    superscript(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_superscript_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Sets the font weight to "thin" (equivalent to CSS 100).
     * [Learn more](https://www.questpdf.com/api-reference/text/text-style.html#font-weight)
     *
     * Determines the thickness of the text characters, ranging from light to bold, to create visual hierarchy or emphasis.
     *
     * Not all fonts support every weight.
     * If the specified weight isn't available, the library selects the closest available option.
     */
    thin(): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_thin_0(this.nativeHandle)), NATIVE_HANDLE);
    }

    /**
     * Draws a line under the text.
     *
     * You can control the decoration visuals by setting color and style (solid, double, wavy, dotted, dashed) of the line.
     */
    underline(value: boolean = true): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_underline_0(this.nativeHandle, (value ? 1 : 0))), NATIVE_HANDLE);
    }

    /**
     * Adjusts the horizontal spacing between words in the text, affecting readability and overall visual style.
     * The adjustment is proportional to the text size.
     *
     * @param factor Sets the proportion by which the horizontal space between words is changed.  A value of 0 maintains the original spacing. When the value is positive, the text is more spread out. When it is negative, the text is more condensed.
     */
    wordSpacing(factor: number = 0): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_wordSpacing_0(this.nativeHandle, factor)), NATIVE_HANDLE);
    }

    /**
     * Allows text to wrap at any character, not just spaces.
     *
     * @deprecated This setting is not supported since the 2024.3 version. This flag should be handled automatically by the layout engine.
     */
    wrapAnywhere(value: boolean = true): TextBlockDescriptor {
        return new TextBlockDescriptor(Native.checked(Native.lib.QP_TextBlockDescriptor_wrapAnywhere_0(this.nativeHandle, (value ? 1 : 0))), NATIVE_HANDLE);
    }
}
