// <auto-generated>
// Generated by QuestPDF.Interop.Generator from QuestPDF 2026.7.1.0.
// Do not edit — this file is wiped and recreated on every generator run.
// </auto-generated>

import { Native } from '../../../manual/native-bridge';
import { NATIVE_HANDLE, NativeObject } from '../../../manual/native-object';

export class Color extends NativeObject {
    /**
     * Creates a new color from a hex value following the ARGB format.
     * For example 0xFF0000FF represents a fully opaque blue color.
     */
    constructor(hex: number);
    /** Wraps an existing native handle. @internal */
    constructor(handle: number, marker: typeof NATIVE_HANDLE);
    constructor(...args: any[]) {
        if (args[1] === NATIVE_HANDLE) {
            super(args[0] as number, NATIVE_HANDLE);
            return;
        }
        const hex = args[0] as number;
        super(Native.checked(Native.lib.QP_Color_ctor_0(hex)), NATIVE_HANDLE);
    }

    get alpha(): number {
        return Native.checked(Native.lib.QP_Color_getAlpha_0(this.nativeHandle));
    }

    get blue(): number {
        return Native.checked(Native.lib.QP_Color_getBlue_0(this.nativeHandle));
    }

    get green(): number {
        return Native.checked(Native.lib.QP_Color_getGreen_0(this.nativeHandle));
    }

    get hex(): number {
        return Native.checked(Native.lib.QP_Color_getHex_0(this.nativeHandle));
    }

    get red(): number {
        return Native.checked(Native.lib.QP_Color_getRed_0(this.nativeHandle));
    }

    toUInt32(): number {
        return Native.checked(Native.lib.QP_Color_toUInt32_0(this.nativeHandle));
    }

    /**
     * Creates a new color instance with the specified alpha transparency value.
     * The alpha value should be within the range 0 to 255, where 0 represents fully transparent
     * and 255 represents fully opaque.
     *
     * @returns A new color instance with the adjusted alpha transparency.
     */
    withAlpha(alpha: number): Color {
        return new Color(Native.checked(Native.lib.QP_Color_withAlpha_0(this.nativeHandle, alpha)), NATIVE_HANDLE);
    }

    static from(hex: number): Color;
    static from(hex: string): Color;
    static from(...args: any[]): any {
        if (args.length === 1 && typeof args[0] === "number") {
            const hex = args[0] as number;
            return new Color(Native.checked(Native.lib.QP_Color_from_1(hex)), NATIVE_HANDLE);
        }
        if (args.length === 1 && typeof args[0] === "string") {
            const hex = args[0] as string;
            return new Color(Native.checked(Native.lib.QP_Color_from_0(hex)), NATIVE_HANDLE);
        }
        throw new TypeError("No overload of 'from' matches the provided arguments.");
    }

    /**
     * Creates a new color instance from the specified alpha, red, green, and blue component values.
     * Each component should be within the range 0 to 255.
     */
    static fromARGB(alpha: number, red: number, green: number, blue: number): Color {
        return new Color(Native.checked(Native.lib.QP_Color_fromARGB_0(alpha, red, green, blue)), NATIVE_HANDLE);
    }

    /**
     * Creates a new color instance from a hex string representation.
     * The string should follow the formats: #RGB, #ARGB, #RRGGBB, or #AARRGGBB.
     * The hash sign is optional; for example: RGB, ARGB, RRGGBB, or AARRGGBB are also valid.
     *
     * @param hex The hex string representing the color.
     * @returns A new color instance created from the hex string.
     */
    static fromHex(hex: string): Color {
        return new Color(Native.checked(Native.lib.QP_Color_fromHex_0(hex)), NATIVE_HANDLE);
    }

    /**
     * Creates a new color instance given the red, green, and blue component values.
     * Each component should be within the range 0 to 255.
     */
    static fromRGB(red: number, green: number, blue: number): Color {
        return new Color(Native.checked(Native.lib.QP_Color_fromRGB_0(red, green, blue)), NATIVE_HANDLE);
    }
}
